// src/curriculum/lessons/L2/S06.ts
// 🔢 درس S06: الضرب (2 × 2) — منهجية تاكاشي كوجيما المتقدمة للأطفال
// القاعدة الذهبية: أربع خطوات متعاقبة من المنزلة الكبيرة إلى الصغيرة (من اليسار إلى اليمين)

import type { LessonNode } from "../types";

export const S06_LESSON: LessonNode = {
  id: "S06",
  skillId: "S06",
  levelId: "L2",
  order: 2,
  title: { ar: "الضرب (2 × 2)", en: "Multiplication (2×2)" },
  emoji: "🔢",
  tags: ["multiplication", "kids", "L2", "2x2", "left-to-right", "takashi-kojima"],

  modules: [
    // ═══════════════════════════════════════════════════════════
    // m1 — الضرب المباشر (2 × 2)
    // ═══════════════════════════════════════════════════════════
    {
      id: "m1",
      ruleCategory: "direct",
      title: "الضرب المباشر | Direct Multiplication",
      titleEn: "Direct Multiplication",
      emoji: "✨",
      miniStory: {
        title: "حقول الفلاح السحرية | The Magic Farmer's Fields",
        emoji: "🌾",
        story: "يا أبطال! بنزرع 11 صف بـ 11 حبة.. أربع خطوات سهلة من المئات للآحاد والخرزات مفتوحة وجاهزة.. والناتج السحري: 121!",
        storyAudioText: "يا أبطال.. دعونا نحسب إحدى عشر في إحدى عشر.. نضرب العشرات في العشرات أولاً: واحد في واحد يساوي واحد في المئات.. ثم الآحاد في العشرات: واحد في واحد يساوي واحد في العشرات.. ثم العشرات في الآحاد: واحد في واحد يساوي واحد في العشرات.. واحد زائد واحد يساوي اثنين.. ثم الآحاد في الآحاد: واحد في واحد يساوي واحد في الآحاد.. والناتج: مئة وواحد وعشرون!",
        storyAudioId: null,
      },
      rule: {
        description: "خريطة الأبطال الأربعة من اليسار لليمين: 1. مئات (عشرات×عشرات) · 2. عشرات (آحاد×عشرات) · 3. إضافة للعشرات (عشرات×آحاد) · 4. آحاد (آحاد×آحاد) | Four steps Left-to-Right: 1. Hundreds (Tens×Tens) · 2. Tens (Units×Tens) · 3. Add to Tens (Tens×Units) · 4. Units (Units×Units)",
      },
      condition: {
        formula: "كل النواتج الجزئية مباشرة | All partial products direct",
        explanation: "الخرزات مفتوحة تماماً ولا نحتاج أصدقاء أو استعارة! | Beads are ready; no friends or carrying needed!",
      },
      discrimination: {
        steps: [
          {
            question: "هل تبدأ بالمنزلة الكبيرة (المئات) أولاً؟ | Do you start with the largest place value (Hundreds) first?",
            type: "yes-no",
            answer: "نعم → (عشرات × عشرات) تستقر في المئات | Yes → (Tens × Tens) lands in Hundreds",
          },
          {
            question: "هل الخرزات الفارغة في كل عمود تكفي؟ | Are there enough free beads in each rod?",
            type: "comparison",
            actual: "الخرزات ≥ الناتج | Beads ≥ Product",
            answer: "نعم → أضف مباشرة من اليسار لليمين | Yes → Add directly from left to right",
            hint: "افحص كل خطوة قبل تحريك الخرزات | Check each step before moving beads",
          },
        ],
        decision: "ضرب مباشر — أربع خطوات سريعة من المئات إلى الآحاد! | Direct Multiplication — 4 quick steps from Hundreds to Units!",
      },
      watchPhase: {
        examples: [
          {
            id: "S06-m1-E1",
            question: "11 × 11",
            discrimination: "1×1=1 (مئات) · 1×1=1 (عشرات) · 1×1=1 (تضاف للعشرات: 1+1=2) · 1×1=1 (آحاد) | All direct steps",
            rule: "أربع خطوات مباشرة | 4 direct steps",
            fingerMovement: "ارفع 1 بالمئات بالإبهام ⬆️، ثم 1 بالعشرات، ثم 1 إضافي بالعشرات (1+1=2)، ثم 1 بالآحاد | Set 1 in hundreds with thumb ⬆️, then 1 in tens, add 1 in tens, then 1 in units",
            steps: [
              "المئات: 1×1=1 → ضع 1 بعمود المئات | Hundreds: 1×1=1 → Set 1 in Hundreds rod",
              "العشرات: 1×1=1 → ضع 1 بعمود العشرات | Tens: 1×1=1 → Set 1 in Tens rod",
              "العشرات: 1×1=1 → أضف 1 للعشرات (1+1=2 مباشر) | Tens: 1×1=1 → Add 1 to Tens rod (1+1=2 direct)",
              "الآحاد: 1×1=1 → ضع 1 بعمود الآحاد | Units: 1×1=1 → Set 1 in Units rod",
              "الناتج النهائي: 121 | Final Result: 121",
            ],
            result: 121,
            beadVisual: "1 مئة + 2 عشرات + 1 آحاد = 121 | 1 Hundred + 2 Tens + 1 Unit = 121",
          },
          {
            id: "S06-m1-E2",
            question: "12 × 11",
            discrimination: "1 للمئات · 2 للعشرات · +1 للعشرات (2+1=3) · 2 للآحاد | Direct left-to-right",
            rule: "أربع خطوات مباشرة | 4 direct steps",
            fingerMovement: "ضع 1 للمئات، 2 للعشرات، أضف 1 للعشرات بالإبهام، 2 للآحاد | Set 1 hundreds, 2 tens, add 1 tens, 2 units",
            steps: [
              "المئات: 1×1=1 → ضع 1 | Hundreds: 1×1=1 → Set 1",
              "العشرات: 2×1=2 → ضع 2 | Tens: 2×1=2 → Set 2",
              "العشرات: 1×1=1 → أضف 1 (2+1=3 مباشر) | Tens: 1×1=1 → Add 1 (2+1=3 direct)",
              "الآحاد: 2×1=2 → ضع 2 | Units: 2×1=2 → Set 2",
              "الناتج النهائي: 132 | Final Result: 132",
            ],
            result: 132,
            beadVisual: "1 مئة + 3 عشرات + 2 آحاد = 132 | 1 Hundred + 3 Tens + 2 Units = 132",
          },
          {
            id: "S06-m1-E3",
            question: "13 × 11",
            discrimination: "1 للمئات · 3 للعشرات · +1 للعشرات (3+1=4) · 3 للآحاد | Direct left-to-right",
            rule: "أربع خطوات مباشرة | 4 direct steps",
            fingerMovement: "ضع 1 للمئات، 3 للعشرات، أضف 1 للعشرات بالإبهام، 3 للآحاد | Set 1 hundreds, 3 tens, add 1 tens, 3 units",
            steps: [
              "المئات: 1×1=1 → ضع 1 | Hundreds: 1×1=1 → Set 1",
              "العشرات: 3×1=3 → ضع 3 | Tens: 3×1=3 → Set 3",
              "العشرات: 1×1=1 → أضف 1 (3+1=4 مباشر) | Tens: 1×1=1 → Add 1 (3+1=4 direct)",
              "الآحاد: 3×1=3 → ضع 3 | Units: 3×1=3 → Set 3",
              "الناتج النهائي: 143 | Final Result: 143",
            ],
            result: 143,
            beadVisual: "1 مئة + 4 عشرات + 3 آحاد = 143 | 1 Hundred + 4 Tens + 3 Units = 143",
          },
          {
            id: "S06-m1-E4",
            question: "21 × 11",
            discrimination: "2 للمئات · 1 للعشرات · +2 للعشرات (1+2=3) · 1 للآحاد | Direct left-to-right",
            rule: "أربع خطوات مباشرة | 4 direct steps",
            fingerMovement: "ارفع 2 بالمئات، 1 بالعشرات، أضف 2 بالعشرات، 1 بالآحاد | Set 2 hundreds, 1 tens, add 2 tens, 1 units",
            steps: [
              "المئات: 2×1=2 → ضع 2 | Hundreds: 2×1=2 → Set 2",
              "العشرات: 1×1=1 → ضع 1 | Tens: 1×1=1 → Set 1",
              "العشرات: 2×1=2 → أضف 2 (1+2=3 مباشر) | Tens: 2×1=2 → Add 2 (1+2=3 direct)",
              "الآحاد: 1×1=1 → ضع 1 | Units: 1×1=1 → Set 1",
              "الناتج النهائي: 231 | Final Result: 231",
            ],
            result: 231,
            beadVisual: "2 مئات + 3 عشرات + 1 آحاد = 231 | 2 Hundreds + 3 Tens + 1 Unit = 231",
          },
          {
            id: "S06-m1-E5",
            question: "22 × 11",
            discrimination: "2 للمئات · 2 للعشرات · +2 للعشرات (2+2=4) · 2 للآحاد | Direct left-to-right",
            rule: "أربع خطوات مباشرة | 4 direct steps",
            fingerMovement: "ارفع 2 بالمئات، 2 بالعشرات، أضف 2 بالعشرات، 2 بالآحاد | Set 2 hundreds, 2 tens, add 2 tens, 2 units",
            steps: [
              "المئات: 2×1=2 → ضع 2 | Hundreds: 2×1=2 → Set 2",
              "العشرات: 2×1=2 → ضع 2 | Tens: 2×1=2 → Set 2",
              "العشرات: 2×1=2 → أضف 2 (2+2=4 مباشر) | Tens: 2×1=2 → Add 2 (2+2=4 direct)",
              "الآحاد: 2×1=2 → ضع 2 | Units: 2×1=2 → Set 2",
              "الناتج النهائي: 242 | Final Result: 242",
            ],
            result: 242,
            beadVisual: "2 مئات + 4 عشرات + 2 آحاد = 242 | 2 Hundreds + 4 Tens + 2 Units = 242",
          },
        ],
      },
      tryPhase: {
        exercises: [
          {
            id: "S06-m1-T1",
            question: "11 × 22",
            discrimination: "1×2=2 (مئات) · 1×2=2 (عشرات) · 1×2=2 (2+2=4) · 1×2=2 (آحاد) | Direct",
            steps: [
              "1×2=2 → المئات | Hundreds",
              "1×2=2 → العشرات | Tens",
              "1×2=2 → العشرات (2+2=4) | Tens (2+2=4)",
              "1×2=2 → الآحاد | Units",
              "الناتج النهائي: 242 | Final Result: 242",
            ],
            result: 242,
          },
          {
            id: "S06-m1-T2",
            question: "12 × 11",
            discrimination: "1 للمئات · 2 للعشرات · +1 (2+1=3) · 2 للآحاد | Direct",
            steps: [
              "1×1=1 → المئات | Hundreds",
              "2×1=2 → العشرات | Tens",
              "1×1=1 → العشرات (2+1=3) | Tens (2+1=3)",
              "2×1=2 → الآحاد | Units",
              "الناتج النهائي: 132 | Final Result: 132",
            ],
            result: 132,
          },
          {
            id: "S06-m1-T3",
            question: "21 × 11",
            discrimination: "2 للمئات · 1 للعشرات · +2 (1+2=3) · 1 للآحاد | Direct",
            steps: [
              "2×1=2 → المئات | Hundreds",
              "1×1=1 → العشرات | Tens",
              "2×1=2 → العشرات (1+2=3) | Tens (1+2=3)",
              "1×1=1 → الآحاد | Units",
              "الناتج النهائي: 231 | Final Result: 231",
            ],
            result: 231,
          },
          {
            id: "S06-m1-T4",
            question: "11 × 13",
            discrimination: "1 للمئات · 3 للعشرات · +1 (3+1=4) · 3 للآحاد | Direct",
            steps: [
              "1×1=1 → المئات | Hundreds",
              "1×3=3 → العشرات | Tens",
              "1×1=1 → العشرات (3+1=4) | Tens (3+1=4)",
              "1×3=3 → الآحاد | Units",
              "الناتج النهائي: 143 | Final Result: 143",
            ],
            result: 143,
          },
          {
            id: "S06-m1-T5",
            question: "11 × 31",
            discrimination: "3 للمئات · 1 للعشرات · +3 (1+3=4) · 1 للآحاد | Direct",
            steps: [
              "1×3=3 → المئات | Hundreds",
              "1×1=1 → العشرات | Tens",
              "1×3=3 → العشرات (1+3=4) | Tens (1+3=4)",
              "1×1=1 → الآحاد | Units",
              "الناتج النهائي: 341 | Final Result: 341",
            ],
            result: 341,
          },
        ],
      },
    },

    // ═══════════════════════════════════════════════════════════
    // m2 — الضرب بأصدقاء 5 (2 × 2)
    // ═══════════════════════════════════════════════════════════
    {
      id: "m2",
      ruleCategory: "small_friends",
      title: "الضرب بأصدقاء 5 | Friends of 5",
      titleEn: "Friends of 5",
      emoji: "🤝",
      miniStory: {
        title: "الجدة 5 تتدخل | Grandma 5 Helps",
        emoji: "👵",
        story: "13 صف بـ 12 شجرة! لما جمعنا خطوتي العشرات ازدحم العمود.. نزلت تيتا 5 الحنونة بالسبابة وطردت الصديق للإبهام.. والناتج: 156!",
        storyAudioText: "ثلاثة عشر في اثني عشر.. العشرات في العشرات: واحد في واحد يساوي واحد في المئات.. الآحاد في العشرات: ثلاثة في واحد يساوي ثلاثة في العشرات.. العشرات في الآحاد: واحد في اثنين يساوي اثنين.. نضيف اثنين لثلاثة بأصدقاء خمسة: أنزل خمسة واطرح ثلاثة.. الآحاد في الآحاد: ثلاثة في اثنين يساوي ستة.. الناتج: مئة وستة وخمسون!",
        storyAudioId: null,
      },
      rule: {
        description: "أصدقاء 5: عند ازدحام الخرزات السفلية في عمود العشرات، أنزل العلوية 5 بالسبابة ⬇️ واطرد صديق العدد بالإبهام ⬇️! | Small Friends: When lower beads are full in tens rod, lower top bead 5 with index ⬇️ and push down the friend with thumb ⬇️!",
        cases: [
          { from: 1, formula: "+1 = +5 − 4" },
          { from: 2, formula: "+2 = +5 − 3" },
          { from: 3, formula: "+3 = +5 − 2" },
          { from: 4, formula: "+4 = +5 − 1" },
        ],
      },
      condition: {
        formula: "السفليات غير كافية · خرزة 5 متاحة | Lower beads insufficient · Top bead 5 available",
        explanation: "نحتاج إضافة خرزات في العشرات والسفليات ممتلئة — الجدة 5 تتدخل! | Need to add tens, lower beads full — Grandma 5 steps in!",
      },
      friendsTable: {
        title: "جدول أصدقاء 5 الصغار | Friends of 5 Table",
        pairs: [
          { from: 1, to: 4 },
          { from: 2, to: 3 },
          { from: 3, to: 2 },
          { from: 4, to: 1 },
        ],
      },
      discrimination: {
        steps: [
          {
            question: "هل الخرزات السفلية في العشرات غير كافية لإضافة ناتج الخطوة الثالثة؟ | Are lower beads in Tens rod insufficient for step 3?",
            type: "comparison",
            actual: "السفليات < المطلوب | Lower beads < Required",
            answer: "نعم → نلجأ لأصدقاء 5 | Yes → Use Friends of 5",
            hint: "تأكد أن خرزة 5 العلوية غير مفعّلة | Ensure top bead 5 is available",
          },
          {
            question: "ما هو صديق العدد المطلوب لإتمامه إلى 5؟ | What is the friend needed to make 5?",
            type: "yes-no",
            actual: "+n = +5 − (5−n)",
            answer: "أنزل 5 بالسبابة واطرد الصديق لأسفل | Lower 5 with index, push friend down",
          },
        ],
        decision: "أصدقاء 5 — أنزل 5 واطرد الصديق! | Friends of 5 — Drop 5 and remove friend!",
      },
      watchPhase: {
        examples: [
          {
            id: "S06-m2-E1",
            question: "14 × 11",
            discrimination: "1 للمئات · 4 للعشرات · +1 للعشرات (4+1=5 بأصدقاء 5: +5−4) · 4 للآحاد | Friends of 5 (+1)",
            rule: "+1 = +5 − 4",
            fingerMovement: "أنزل الخرزة 5 العلوية بالسبابة ⬇️ واطرد 4 سفليات بالإبهام لأسفل ⬇️ | Lower top 5 with index ⬇️, push 4 lower beads down with thumb ⬇️",
            steps: [
              "المئات: 1×1=1 → ضع 1 بالمئات | Hundreds: 1×1=1 → Set 1",
              "العشرات: 4×1=4 → ضع 4 بالعشرات | Tens: 4×1=4 → Set 4",
              "العشرات: 1×1=1 → أضف 1 بأصدقاء 5 (+5−4) لتصبح 5 | Tens: 1×1=1 → Add 1 via Friends of 5 (+5−4) = 5",
              "الآحاد: 4×1=4 → ضع 4 بالآحاد | Units: 4×1=4 → Set 4",
              "الناتج النهائي: 154 | Final Result: 154",
            ],
            result: 154,
            beadVisual: "1 مئة + 5 عشرات + 4 آحاد = 154 | 1 Hundred + 5 Tens + 4 Units = 154",
          },
          {
            id: "S06-m2-E2",
            question: "13 × 12",
            discrimination: "1 للمئات · 3 للعشرات · +2 للعشرات (3+2=5 بأصدقاء 5: +5−3) · 6 للآحاد | Friends of 5 (+2)",
            rule: "+2 = +5 − 3",
            fingerMovement: "أنزل 5 بالسبابة ⬇️ واطرد 3 سفليات لأسفل ⬇️ | Drop 5 with index ⬇️, push 3 lower beads down ⬇️",
            steps: [
              "المئات: 1×1=1 → ضع 1 | Hundreds: 1×1=1 → Set 1",
              "العشرات: 3×1=3 → ضع 3 | Tens: 3×1=3 → Set 3",
              "العشرات: 1×2=2 → أضف 2 بأصدقاء 5 (+5−3) لتصبح 5 | Tens: 1×2=2 → Add 2 via Friends of 5 (+5−3) = 5",
              "الآحاد: 3×2=6 → ضع 6 بالآحاد | Units: 3×2=6 → Set 6",
              "الناتج النهائي: 156 | Final Result: 156",
            ],
            result: 156,
            beadVisual: "1 مئة + 5 عشرات + 6 آحاد = 156 | 1 Hundred + 5 Tens + 6 Units = 156",
          },
          {
            id: "S06-m2-E3",
            question: "12 × 13",
            discrimination: "1 للمئات · 2 للعشرات · +3 للعشرات (2+3=5 بأصدقاء 5: +5−2) · 6 للآحاد | Friends of 5 (+3)",
            rule: "+3 = +5 − 2",
            fingerMovement: "أنزل 5 بالسبابة ⬇️ واطرد 2 سفليات لأسفل ⬇️ | Drop 5 with index ⬇️, push 2 lower beads down ⬇️",
            steps: [
              "المئات: 1×1=1 → ضع 1 | Hundreds: 1×1=1 → Set 1",
              "العشرات: 2×1=2 → ضع 2 | Tens: 2×1=2 → Set 2",
              "العشرات: 1×3=3 → أضف 3 بأصدقاء 5 (+5−2) لتصبح 5 | Tens: 1×3=3 → Add 3 via Friends of 5 (+5−2) = 5",
              "الآحاد: 2×3=6 → ضع 6 بالآحاد | Units: 2×3=6 → Set 6",
              "الناتج النهائي: 156 | Final Result: 156",
            ],
            result: 156,
            beadVisual: "1 مئة + 5 عشرات + 6 آحاد = 156 | 1 Hundred + 5 Tens + 6 Units = 156",
          },
          {
            id: "S06-m2-E4",
            question: "23 × 12",
            discrimination: "2 للمئات · 3 للعشرات · +4 للعشرات (3+4=7 بأصدقاء 5: +5−1) · 6 للآحاد | Friends of 5 (+4)",
            rule: "+4 = +5 − 1",
            fingerMovement: "أنزل 5 بالسبابة ⬇️ واطرد 1 سفلي لأسفل ⬇️ | Drop 5 with index ⬇️, push 1 lower bead down ⬇️",
            steps: [
              "المئات: 2×1=2 → ضع 2 | Hundreds: 2×1=2 → Set 2",
              "العشرات: 3×1=3 → ضع 3 | Tens: 3×1=3 → Set 3",
              "العشرات: 2×2=4 → أضف 4 بأصدقاء 5 (+5−1) لتصبح 7 | Tens: 2×2=4 → Add 4 via Friends of 5 (+5−1) = 7",
              "الآحاد: 3×2=6 → ضع 6 بالآحاد | Units: 3×2=6 → Set 6",
              "الناتج النهائي: 276 | Final Result: 276",
            ],
            result: 276,
            beadVisual: "2 مئات + 7 عشرات + 6 آحاد = 276 | 2 Hundreds + 7 Tens + 6 Units = 276",
          },
          {
            id: "S06-m2-E5",
            question: "24 × 12",
            discrimination: "2 للمئات · 4 للعشرات · +4 للعشرات (4+4=8 بأصدقاء 5: +5−1) · 8 للآحاد | Friends of 5 (+4)",
            rule: "+4 = +5 − 1",
            fingerMovement: "أنزل 5 بالسبابة ⬇️ واطرد 1 سفلي لأسفل ⬇️ | Drop 5 with index ⬇️, push 1 lower bead down ⬇️",
            steps: [
              "المئات: 2×1=2 → ضع 2 | Hundreds: 2×1=2 → Set 2",
              "العشرات: 4×1=4 → ضع 4 | Tens: 4×1=4 → Set 4",
              "العشرات: 2×2=4 → أضف 4 بأصدقاء 5 (+5−1) لتصبح 8 | Tens: 2×2=4 → Add 4 via Friends of 5 (+5−1) = 8",
              "الآحاد: 4×2=8 → ضع 8 بالآحاد | Units: 4×2=8 → Set 8",
              "الناتج النهائي: 288 | Final Result: 288",
            ],
            result: 288,
            beadVisual: "2 مئات + 8 عشرات + 8 آحاد = 288 | 2 Hundreds + 8 Tens + 8 Units = 288",
          },
        ],
      },
      tryPhase: {
        exercises: [
          {
            id: "S06-m2-T1",
            question: "14 × 12",
            discrimination: "4+2=6 بأصدقاء 5 (+5−3) | +2 = +5 − 3",
            steps: [
              "1×1=1 → المئات | Hundreds",
              "4×1=4 → العشرات | Tens",
              "1×2=2 → العشرات (4+2=6 بأصدقاء 5: +5−3) | Tens (4+2=6 via +5−3)",
              "4×2=8 → الآحاد | Units",
              "الناتج النهائي: 168 | Final Result: 168",
            ],
            result: 168,
          },
          {
            id: "S06-m2-T2",
            question: "13 × 13",
            discrimination: "3+3=6 بأصدقاء 5 (+5−2) | +3 = +5 − 2",
            steps: [
              "1×1=1 → المئات | Hundreds",
              "3×1=3 → العشرات | Tens",
              "1×3=3 → العشرات (3+3=6 بأصدقاء 5: +5−2) | Tens (3+3=6 via +5−2)",
              "3×3=9 → الآحاد | Units",
              "الناتج النهائي: 169 | Final Result: 169",
            ],
            result: 169,
          },
          {
            id: "S06-m2-T3",
            question: "14 × 11",
            discrimination: "4+1=5 بأصدقاء 5 (+5−4) | +1 = +5 − 4",
            steps: [
              "1×1=1 → المئات | Hundreds",
              "4×1=4 → العشرات | Tens",
              "1×1=1 → العشرات (4+1=5 بأصدقاء 5: +5−4) | Tens (4+1=5 via +5−4)",
              "4×1=4 → الآحاد | Units",
              "الناتج النهائي: 154 | Final Result: 154",
            ],
            result: 154,
          },
          {
            id: "S06-m2-T4",
            question: "23 × 12",
            discrimination: "3+4=7 بأصدقاء 5 (+5−1) | +4 = +5 − 1",
            steps: [
              "2×1=2 → المئات | Hundreds",
              "3×1=3 → العشرات | Tens",
              "2×2=4 → العشرات (3+4=7 بأصدقاء 5: +5−1) | Tens (3+4=7 via +5−1)",
              "3×2=6 → الآحاد | Units",
              "الناتج النهائي: 276 | Final Result: 276",
            ],
            result: 276,
          },
          {
            id: "S06-m2-T5",
            question: "24 × 11",
            discrimination: "4+2=6 بأصدقاء 5 (+5−3) | +2 = +5 − 3",
            steps: [
              "2×1=2 → المئات | Hundreds",
              "4×1=4 → العشرات | Tens",
              "2×1=2 → العشرات (4+2=6 بأصدقاء 5: +5−3) | Tens (4+2=6 via +5−3)",
              "4×1=4 → الآحاد | Units",
              "الناتج النهائي: 264 | Final Result: 264",
            ],
            result: 264,
          },
        ],
      },
    },

    // ═══════════════════════════════════════════════════════════
    // m3 — الضرب بأصدقاء 10 (2 × 2)
    // ═══════════════════════════════════════════════════════════
    {
      id: "m3",
      ruleCategory: "big_friends",
      title: "الضرب بأصدقاء 10 | Friends of 10",
      titleEn: "Friends of 10",
      emoji: "🌟",
      miniStory: {
        title: "العملاق 10 يطير للمئات | Giant 10 Leaps to Hundreds",
        emoji: "🦶",
        story: "19 صف بـ 11 زهرة! مجموع العشرات وصل 10 وما فوق؟ طلع العملاق 10 ليطرح المتمّم ويطير خرزة للمئات.. والناتج: 209!",
        storyAudioText: "تسعة عشر في أحد عشر.. العشرات في العشرات: واحد في واحد يساوي واحد في المئات.. الآحاد في العشرات: تسعة في واحد يساوي تسعة في العشرات.. العشرات في الآحاد: واحد في واحد يساوي واحد.. تسعة زائد واحد يساوي عشرة.. العملاق عشرة يتدخل: اطرح تسعة وأضف خرزة في المئات.. الآحاد في الآحاد: تسعة في واحد يساوي تسعة.. الناتج: مئتان وتسعة!",
        storyAudioId: null,
      },
      rule: {
        description: "أصدقاء 10: عندما يتجاوز مجموع عمود العشرات 9، اطرح المتمّم بالسبابة ⬇️ وأضف 1 لعمود المئات الأيسر بالإبهام ⬆️! | Big Friends: When tens sum exceeds 9, subtract complement with index ⬇️ and leap 1 bead to Hundreds rod with thumb ⬆️!",
        cases: [
          { from: 1, formula: "+1 = −9 + 10" },
          { from: 2, formula: "+2 = −8 + 10" },
          { from: 3, formula: "+3 = −7 + 10" },
          { from: 4, formula: "+4 = −6 + 10" },
          { from: 5, formula: "+5 = −5 + 10" },
          { from: 6, formula: "+6 = −4 + 10" },
          { from: 7, formula: "+7 = −3 + 10" },
          { from: 8, formula: "+8 = −2 + 10" },
          { from: 9, formula: "+9 = −1 + 10" },
        ],
      },
      condition: {
        formula: "مجموع العشرات ≥ 10 | Tens sum ≥ 10",
        explanation: "تجاوز العمود العدد 9 — نقفز لعمود المئات الأيسر مباشرة! | Column exceeded 9 — leap directly to Hundreds rod on the left!",
      },
      friendsTable: {
        title: "جدول أصدقاء 10 الكبار | Friends of 10 Table",
        pairs: [
          { from: 1, to: 9 },
          { from: 2, to: 8 },
          { from: 3, to: 7 },
          { from: 4, to: 6 },
          { from: 5, to: 5 },
          { from: 6, to: 4 },
          { from: 7, to: 3 },
          { from: 8, to: 2 },
          { from: 9, to: 1 },
        ],
      },
      discrimination: {
        steps: [
          {
            question: "هل مجموع خطوتي العشرات يصل إلى 10 أو أكثر؟ | Does the sum of tens steps reach 10 or more?",
            type: "yes-no",
            actual: "المجموع ≥ 10 | Sum ≥ 10",
            answer: "نعم → نلجأ لأصدقاء 10 | Yes → Use Friends of 10",
            hint: "اطرح المتمّم وقفز بـ 1 للمئات | Subtract complement and add 1 to Hundreds",
          },
          {
            question: "هل الخرزات المفعّلة تكفي لطرح المتمّم مباشرة؟ | Are active beads sufficient to subtract complement directly?",
            type: "yes-no",
            actual: "الخرزات ≥ المتمّم | Active beads ≥ Complement",
            answer: "نعم → اطرح المتمّم وأضف 1 يساراً | Yes → Subtract complement and add 1 to Hundreds",
          },
        ],
        decision: "أصدقاء 10 — اطرح المتمّم واقفز 1 للمئات! | Friends of 10 — Subtract complement and leap 1 to Hundreds!",
      },
      watchPhase: {
        examples: [
          {
            id: "S06-m3-E1",
            question: "19 × 11",
            discrimination: "1 للمئات · 9 للعشرات · +1 للعشرات (9+1=10 بأصدقاء 10: −9+10) · 9 للآحاد | Friends of 10 (+1)",
            rule: "+1 = −9 + 10",
            fingerMovement: "اطرح 9 من العشرات بالسبابة ⬇️ وأضف 1 للمئات بالإبهام ⬆️ | Clear 9 from Tens with index ⬇️, add 1 to Hundreds with thumb ⬆️",
            steps: [
              "المئات: 1×1=1 → ضع 1 بعمود المئات | Hundreds: 1×1=1 → Set 1",
              "العشرات: 9×1=9 → ضع 9 بعمود العشرات | Tens: 9×1=9 → Set 9",
              "العشرات: 1×1=1 → (9+1=10): اطرح 9 من العشرات وأضف 1 للمئات (تصبح 2) | Tens: 1×1=1 → (9+1=10): Clear 9 in Tens, add 1 to Hundreds (becomes 2)",
              "الآحاد: 9×1=9 → ضع 9 بعمود الآحاد | Units: 9×1=9 → Set 9",
              "الناتج النهائي: 209 | Final Result: 209",
            ],
            result: 209,
            beadVisual: "2 مئات + 0 عشرات + 9 آحاد = 209 | 2 Hundreds + 0 Tens + 9 Units = 209",
          },
          {
            id: "S06-m3-E2",
            question: "17 × 12",
            discrimination: "1 للمئات · 7 للعشرات · +2 للعشرات (7+2=9) · الآحاد (7×2=14: 4 للآحاد، و+1 للعشرات: 9+1=10) | Friends of 10 (+1)",
            rule: "+1 = −9 + 10",
            fingerMovement: "من خطوة ترحيل الآحاد: اطرح 9 بالعشرات ⬇️ وأضف 1 للمئات ⬆️ | From units carry: Clear 9 in Tens ⬇️, add 1 to Hundreds ⬆️",
            steps: [
              "المئات: 1×1=1 → ضع 1 | Hundreds: 1×1=1 → Set 1",
              "العشرات: 7×1=7 → ضع 7 | Tens: 7×1=7 → Set 7",
              "العشرات: 1×2=2 → 7+2=9 مباشر بالعشرات | Tens: 1×2=2 → 7+2=9 direct in Tens",
              "الآحاد: 7×2=14 → ضع 4 بالآحاد، والمتبقي 1 للعشرات (9+1=10: اطرح 9 وأضف 1 للمئات لتصبح 2) | Units: 7×2=14 → Set 4 in Units, 1 to Tens (9+1=10: Clear 9, add 1 to Hundreds)",
              "الناتج النهائي: 204 | Final Result: 204",
            ],
            result: 204,
            beadVisual: "2 مئات + 0 عشرات + 4 آحاد = 204 | 2 Hundreds + 0 Tens + 4 Units = 204",
          },
          {
            id: "S06-m3-E3",
            question: "16 × 13",
            discrimination: "1 للمئات · 6 للعشرات · +3 للعشرات (6+3=9) · الآحاد (6×3=18: 8 للآحاد، و+1 للعشرات: 9+1=10) | Friends of 10 (+1)",
            rule: "+1 = −9 + 10",
            fingerMovement: "اطرح 9 بالعشرات بالسبابة ⬇️ وأضف 1 للمئات بالإبهام ⬆️ | Clear 9 in Tens ⬇️, add 1 to Hundreds ⬆️",
            steps: [
              "المئات: 1×1=1 → ضع 1 | Hundreds: 1×1=1 → Set 1",
              "العشرات: 6×1=6 → ضع 6 | Tens: 6×1=6 → Set 6",
              "العشرات: 1×3=3 → 6+3=9 مباشر | Tens: 1×3=3 → 6+3=9 direct",
              "الآحاد: 6×3=18 → ضع 8 بالآحاد، و+1 للعشرات (9+1=10: اطرح 9 وأضف 1 للمئات لتصبح 2) | Units: 6×3=18 → Set 8 in Units, +1 to Tens (9+1=10: Clear 9, add 1 to Hundreds)",
              "الناتج النهائي: 208 | Final Result: 208",
            ],
            result: 208,
            beadVisual: "2 مئات + 0 عشرات + 8 آحاد = 208 | 2 Hundreds + 0 Tens + 8 Units = 208",
          },
          {
            id: "S06-m3-E4",
            question: "18 × 12",
            discrimination: "1 للمئات · 8 للعشرات · +2 للعشرات (8+2=10: −8+10) · الآحاد 16 | Friends of 10 (+2)",
            rule: "+2 = −8 + 10",
            fingerMovement: "اطرح 8 بالعشرات بالسبابة ⬇️ وأضف 1 للمئات بالإبهام ⬆️ | Clear 8 in Tens ⬇️, add 1 to Hundreds ⬆️",
            steps: [
              "المئات: 1×1=1 → ضع 1 | Hundreds: 1×1=1 → Set 1",
              "العشرات: 8×1=8 → ضع 8 | Tens: 8×1=8 → Set 8",
              "العشرات: 1×2=2 → (8+2=10): اطرح 8 من العشرات وأضف 1 للمئات (تصبح 2) | Tens: 1×2=2 → (8+2=10): Clear 8 in Tens, add 1 to Hundreds",
              "الآحاد: 8×2=16 → أضف 1 للعشرات (0+1=1) وضارب 6 بالآحاد | Units: 8×2=16 → Add 1 to Tens (0+1=1), set 6 in Units",
              "الناتج النهائي: 216 | Final Result: 216",
            ],
            result: 216,
            beadVisual: "2 مئات + 1 عشرات + 6 آحاد = 216 | 2 Hundreds + 1 Ten + 6 Units = 216",
          },
          {
            id: "S06-m3-E5",
            question: "29 × 11",
            discrimination: "2 للمئات · 9 للعشرات · +2 للعشرات (9+2=11: −8+10) · 9 للآحاد | Friends of 10 (+2)",
            rule: "+2 = −8 + 10",
            fingerMovement: "اطرح 8 بالعشرات بالسبابة ⬇️ وأضف 1 للمئات بالإبهام ⬆️ | Clear 8 in Tens ⬇️, add 1 to Hundreds ⬆️",
            steps: [
              "المئات: 2×1=2 → ضع 2 | Hundreds: 2×1=2 → Set 2",
              "العشرات: 9×1=9 → ضع 9 | Tens: 9×1=9 → Set 9",
              "العشرات: 2×1=2 → (9+2=11): اطرح 8 من العشرات وأضف 1 للمئات (تصبح 3) | Tens: 2×1=2 → (9+2=11): Clear 8 in Tens (remains 1), add 1 to Hundreds (becomes 3)",
              "الآحاد: 9×1=9 → ضع 9 بالآحاد | Units: 9×1=9 → Set 9",
              "الناتج النهائي: 319 | Final Result: 319",
            ],
            result: 319,
            beadVisual: "3 مئات + 1 عشرات + 9 آحاد = 319 | 3 Hundreds + 1 Ten + 9 Units = 319",
          },
        ],
      },
      tryPhase: {
        exercises: [
          {
            id: "S06-m3-T1",
            question: "23 × 33",
            discrimination: "9+6=15 بأصدقاء 10 (−4+10) | +6 = −4 + 10",
            steps: [
              "2×3=6 → المئات | Hundreds",
              "3×3=9 → العشرات | Tens",
              "2×3=6 → العشرات (9+6=15 بأصدقاء 10: −4+10) | Tens (9+6=15 via −4+10)",
              "3×3=9 → الآحاد | Units",
              "الناتج النهائي: 759 | Final Result: 759",
            ],
            result: 759,
          },
          {
            id: "S06-m3-T2",
            question: "22 × 44",
            discrimination: "8+8=16 بأصدقاء 10 (−2+10) | +8 = −2 + 10",
            steps: [
              "2×4=8 → المئات | Hundreds",
              "2×4=8 → العشرات | Tens",
              "2×4=8 → العشرات (8+8=16 بأصدقاء 10: −2+10) | Tens (8+8=16 via −2+10)",
              "2×4=8 → الآحاد | Units",
              "الناتج النهائي: 968 | Final Result: 968",
            ],
            result: 968,
          },
          {
            id: "S06-m3-T3",
            question: "13 × 31",
            discrimination: "9+1=10 بأصدقاء 10 (−9+10) | +1 = −9 + 10",
            steps: [
              "1×3=3 → المئات | Hundreds",
              "3×3=9 → العشرات | Tens",
              "1×1=1 → العشرات (9+1=10 بأصدقاء 10: −9+10) | Tens (9+1=10 via −9+10)",
              "3×1=3 → الآحاد | Units",
              "الناتج النهائي: 403 | Final Result: 403",
            ],
            result: 403,
          },
          {
            id: "S06-m3-T4",
            question: "13 × 32",
            discrimination: "9+2=11 بأصدقاء 10 (−8+10) | +2 = −8 + 10",
            steps: [
              "1×3=3 → المئات | Hundreds",
              "3×3=9 → العشرات | Tens",
              "1×2=2 → العشرات (9+2=11 بأصدقاء 10: −8+10) | Tens (9+2=11 via −8+10)",
              "3×2=6 → الآحاد | Units",
              "الناتج النهائي: 416 | Final Result: 416",
            ],
            result: 416,
          },
          {
            id: "S06-m3-T5",
            question: "23 × 31",
            discrimination: "9+2=11 بأصدقاء 10 (−8+10) | +2 = −8 + 10",
            steps: [
              "2×3=6 → المئات | Hundreds",
              "3×3=9 → العشرات | Tens",
              "2×1=2 → العشرات (9+2=11 بأصدقاء 10: −8+10) | Tens (9+2=11 via −8+10)",
              "3×1=3 → الآحاد | Units",
              "الناتج النهائي: 713 | Final Result: 713",
            ],
            result: 713,
          },
        ],
      },
    },

    // ═══════════════════════════════════════════════════════════
    // m4 — الضرب المركّب (2 × 2)
    // ═══════════════════════════════════════════════════════════
    {
      id: "m4",
      ruleCategory: "combined",
      title: "الضرب المركّب | Compound Multiplication",
      titleEn: "Compound Multiplication",
      emoji: "🎯",
      miniStory: {
        title: "التحالف المزدوج الخارق | The Super Double Alliance",
        emoji: "👑",
        story: "التحدي الكبير! 23 بـ 23! العمود مليان والسفليات ما بتكفي؟ بتتحالف تيتا 5 مع العملاق 10: بنشيل 5، بنرفع 1، وبنطير للمئات.. الناتج الخارق: 529!",
        storyAudioText: "ثلاثة وعشرون في ثلاثة وعشرين.. العشرات في العشرات: اثنان في اثنين يساوي أربعة في المئات.. الآحاد في العشرات: ثلاثة في اثنين يساوي ستة في العشرات.. العشرات في الآحاد: اثنان في ثلاثة يساوي ستة.. ستة زائد ستة يساوي اثني عشر.. التحالف المزدوج: أزل خمسة، أضف واحداً، وأضف خرزة في المئات.. الآحاد في الآحاد: ثلاثة في ثلاثة يساوي تسعة.. الناتج: خمسمائة وتسعة وعشرون!",
        storyAudioId: null,
      },
      rule: {
        description: "التحالف المزدوج: عندما تحتاج لترحيل 10 والمتمّم غير متوفر بالسفليات، أزل 5 بالسبابة ⬆️، أضف المكمّل بالإبهام ⬆️، وأقفز بـ 1 لعمود المئات بالإبهام ⬆️! | Double Alliance: When carrying 10 and complement is not available in lower beads, clear 5 with index ⬆️, add remainder with thumb ⬆️, and leap 1 to Hundreds rod with thumb ⬆️!",
        cases: [
          { from: 5, formula: "+5 = −5 + 10 (إلغاء 5 والقفز بـ 10 للمئات) | +5 = −5 + 10 (Cancel 5 and leap 10 to Hundreds)" },
          { from: 6, formula: "+6 = −5 + 1 + 10 (أزل 5، أضف 1، أضف 10 للمئات) | +6 = −5 + 1 + 10 (Remove 5, add 1, add 10 to Hundreds)" },
          { from: 7, formula: "+7 = −5 + 2 + 10 (أزل 5، أضف 2، أضف 10 للمئات) | +7 = −5 + 2 + 10 (Remove 5, add 2, add 10 to Hundreds)" },
          { from: 8, formula: "+8 = −5 + 3 + 10 (أزل 5، أضف 3، أضف 10 للمئات) | +8 = −5 + 3 + 10 (Remove 5, add 3, add 10 to Hundreds)" },
          { from: 9, formula: "+9 = −5 + 4 + 10 (أزل 5، أضف 4، أضف 10 للمئات) | +9 = −5 + 4 + 10 (Remove 5, add 4, add 10 to Hundreds)" },
        ],
      },
      condition: {
        formula: "مجموع العشرات ≥ 10 · 5 مفعّلة · السفليات < المتمّم | Tens sum ≥ 10 · 5 active · Lower beads < Complement",
        explanation: "الجدة 5 والعملاق 10 يتعاونان معاً لفك ازدحام العمود! | Grandma 5 and Giant 10 ally together to clear column traffic!",
      },
      discrimination: {
        steps: [
          {
            question: "هل نحتاج ترحيل للمئات (المجموع ≥ 10)؟ | Do we need to carry to Hundreds (Sum ≥ 10)?",
            type: "yes-no",
            actual: "المجموع ≥ 10 | Sum ≥ 10",
            answer: "نعم → نحتاج أصدقاء 10 | Yes → Need Friends of 10",
          },
          {
            question: "هل الخرزات السفلية المفعّلة أقل من المتمّم المطلوب طرحه؟ | Are active lower beads less than the complement to subtract?",
            type: "yes-no",
            actual: "السفليات < المتمّم | Lower beads < Complement",
            answer: "نعم → استخدم التحالف المزدوج (−5 + المكمّل + 10) | Yes → Use Double Alliance (−5 + Remainder + 10)",
            hint: "أزل 5 بالسبابة، أضف المكمّل، واقفز 1 للمئات | Clear 5 with index, add remainder, leap 1 to Hundreds",
          },
        ],
        decision: "ضرب مركّب! أزل 5، أضف المكمّل، أضف 10! | Compound Multiplication! Clear 5, add remainder, add 10!",
      },
      watchPhase: {
        examples: [
          {
            id: "S06-m4-E1",
            question: "23 × 23",
            discrimination: "4 بالمئات · 6 بالعشرات · +6 للعشرات (6+6=12: تحالف مركّب −5+1+10) · 9 بالآحاد | Combined Alliance (+6)",
            rule: "+6 = −5 + 1 + 10",
            fingerMovement: "أزل العلوية 5 بالعشرات بالسبابة ⬆️، أضف 1 سفلي بالإبهام ⬆️، وأضف 1 للمئات بالإبهام ⬆️ | Clear top 5 with index ⬆️, add 1 lower bead with thumb ⬆️, add 1 to Hundreds with thumb ⬆️",
            steps: [
              "المئات: 2×2=4 → ضع 4 بعمود المئات | Hundreds: 2×2=4 → Set 4",
              "العشرات: 3×2=6 → ضع 6 بعمود العشرات | Tens: 3×2=6 → Set 6",
              "العشرات: 2×3=6 → (6+6=12): أزل 5 من العشرات (تبقى 1)، أضف 1 سفلي (تصبح 2)، وأضف 1 للمئات (تصبح 5) | Tens: 2×3=6 → (6+6=12): Clear 5, add 1 lower (becomes 2), add 1 to Hundreds (becomes 5)",
              "الآحاد: 3×3=9 → ضع 9 بعمود الآحاد | Units: 3×3=9 → Set 9",
              "الناتج النهائي: 529 | Final Result: 529",
            ],
            result: 529,
            beadVisual: "5 مئات + 2 عشرات + 9 آحاد = 529 | 5 Hundreds + 2 Tens + 9 Units = 529",
          },
          {
            id: "S06-m4-E2",
            question: "24 × 23",
            discrimination: "4 بالمئات · 8 بالعشرات · +6 للعشرات (8+6=14: تحالف مركّب −5+1+10) · الآحاد (4×3=12: 2 للآحاد و+1 للعشرات: 4+1=5) | Combined Alliance (+6)",
            rule: "+6 = −5 + 1 + 10",
            fingerMovement: "أزل العلوية 5 بالعشرات بالسبابة ⬆️، أضف 1 بالإبهام ⬆️، وأضف 1 للمئات بالإبهام ⬆️ | Clear top 5 with index ⬆️, add 1 with thumb ⬆️, add 1 to Hundreds with thumb ⬆️",
            steps: [
              "المئات: 2×2=4 → ضع 4 | Hundreds: 2×2=4 → Set 4",
              "العشرات: 4×2=8 → ضع 8 | Tens: 4×2=8 → Set 8",
              "العشرات: 2×3=6 → (8+6=14): أزل 5 من العشرات، أضف 1 (تصبح 4)، وأضف 1 للمئات (تصبح 5) | Tens: 2×3=6 → (8+6=14): Clear 5, add 1 (becomes 4), add 1 to Hundreds (becomes 5)",
              "الآحاد: 4×3=12 → ضع 2 بالآحاد، و+1 للعشرات (4+1=5) | Units: 4×3=12 → Set 2 in Units, +1 to Tens (4+1=5)",
              "الناتج النهائي: 552 | Final Result: 552",
            ],
            result: 552,
            beadVisual: "5 مئات + 5 عشرات + 2 آحاد = 552 | 5 Hundreds + 5 Tens + 2 Units = 552",
          },
          {
            id: "S06-m4-E3",
            question: "33 × 22",
            discrimination: "6 بالمئات · 6 بالعشرات · +6 للعشرات (6+6=12: تحالف مركّب −5+1+10) · 6 بالآحاد | Combined Alliance (+6)",
            rule: "+6 = −5 + 1 + 10",
            fingerMovement: "أزل 5 بالعشرات بالسبابة ⬆️، أضف 1 بالإبهام ⬆️، وأضف 1 للمئات بالإبهام ⬆️ | Clear 5 with index ⬆️, add 1 with thumb ⬆️, add 1 to Hundreds ⬆️",
            steps: [
              "المئات: 3×2=6 → ضع 6 | Hundreds: 3×2=6 → Set 6",
              "العشرات: 3×2=6 → ضع 6 | Tens: 3×2=6 → Set 6",
              "العشرات: 3×2=6 → (6+6=12): أزل 5 من العشرات، أضف 1 (تصبح 2)، وأضف 1 للمئات (تصبح 7) | Tens: 3×2=6 → (6+6=12): Clear 5, add 1 (becomes 2), add 1 to Hundreds (becomes 7)",
              "الآحاد: 3×2=6 → ضع 6 | Units: 3×2=6 → Set 6",
              "الناتج النهائي: 726 | Final Result: 726",
            ],
            result: 726,
            beadVisual: "7 مئات + 2 عشرات + 6 آحاد = 726 | 7 Hundreds + 2 Tens + 6 Units = 726",
          },
          {
            id: "S06-m4-E4",
            question: "23 × 24",
            discrimination: "4 بالمئات · 6 بالعشرات · +8 للعشرات (6+8=14: تحالف مركّب −5+3+10) · الآحاد (3×4=12: 2 للآحاد و+1 للعشرات: 4+1=5) | Combined Alliance (+8)",
            rule: "+8 = −5 + 3 + 10",
            fingerMovement: "أزل العلوية 5 بالعشرات بالسبابة ⬆️، أضف 3 بالإبهام ⬆️، وأضف 1 للمئات بالإبهام ⬆️ | Clear top 5 with index ⬆️, add 3 with thumb ⬆️, add 1 to Hundreds with thumb ⬆️",
            steps: [
              "المئات: 2×2=4 → ضع 4 | Hundreds: 2×2=4 → Set 4",
              "العشرات: 3×2=6 → ضع 6 | Tens: 3×2=6 → Set 6",
              "العشرات: 2×4=8 → (6+8=14): أزل 5 من العشرات، أضف 3 (تصبح 4)، وأضف 1 للمئات (تصبح 5) | Tens: 2×4=8 → (6+8=14): Clear 5, add 3 (becomes 4), add 1 to Hundreds (becomes 5)",
              "الآحاد: 3×4=12 → ضع 2 بالآحاد، و+1 للعشرات (4+1=5) | Units: 3×4=12 → Set 2 in Units, +1 to Tens (4+1=5)",
              "الناتج النهائي: 552 | Final Result: 552",
            ],
            result: 552,
            beadVisual: "5 مئات + 5 عشرات + 2 آحاد = 552 | 5 Hundreds + 5 Tens + 2 Units = 552",
          },
          {
            id: "S06-m4-E5",
            question: "34 × 22",
            discrimination: "6 بالمئات · 8 بالعشرات · +6 للعشرات (8+6=14: أزل 5، أضف 1 للعشرات تصبح 4، وأضف 1 للمئات) · 8 بالآحاد | Combined Alliance (+6)",
            rule: "+6 = −5 + 1 + 10",
            fingerMovement: "أزل 5 بالعشرات بالسبابة ⬆️، أضف 1 بالإبهام ⬆️ (تصبح 4)، وأضف 1 للمئات بالإبهام ⬆️ | Clear 5 with index ⬆️, add 1 lower ⬆️ (becomes 4), add 1 to Hundreds ⬆️",
            steps: [
              "المئات: 3×2=6 → ضع 6 | Hundreds: 3×2=6 → Set 6",
              "العشرات: 4×2=8 → ضع 8 | Tens: 4×2=8 → Set 8",
              "العشرات: 3×2=6 → (8+6=14): أزل 5 من العشرات، أضف 1 (تصبح 4)، وأضف 1 للمئات (تصبح 7) | Tens: 3×2=6 → (8+6=14): Clear 5, add 1 (becomes 4), add 1 to Hundreds (becomes 7)",
              "الآحاد: 4×2=8 → ضع 8 | Units: 4×2=8 → Set 8",
              "الناتج النهائي: 748 | Final Result: 748",
            ],
            result: 748,
            beadVisual: "7 مئات + 4 عشرات + 8 آحاد = 748 | 7 Hundreds + 4 Tens + 8 Units = 748",
          },
        ],
      },
      tryPhase: {
        exercises: [
          {
            id: "S06-m4-T1",
            question: "23 × 23",
            discrimination: "6+6=12 → تحالف (−5+1+10) | +6 = −5 + 1 + 10",
            steps: [
              "2×2=4 → المئات | Hundreds",
              "3×2=6 → العشرات | Tens",
              "2×3=6 → العشرات (6+6=12 → أزل 5، أضف 1، وأضف 1 للمئات) | Tens (6+6=12 → Clear 5, add 1, add 1 to Hundreds)",
              "3×3=9 → الآحاد | Units",
              "الناتج النهائي: 529 | Final Result: 529",
            ],
            result: 529,
          },
          {
            id: "S06-m4-T2",
            question: "24 × 23",
            discrimination: "8+6=14 → تحالف (−5+1+10) | +6 = −5 + 1 + 10",
            steps: [
              "2×2=4 → المئات | Hundreds",
              "4×2=8 → العشرات | Tens",
              "2×3=6 → العشرات (8+6=14 → أزل 5، أضف 1، وأضف 1 للمئات) | Tens (8+6=14 → Clear 5, add 1, add 1 to Hundreds)",
              "4×3=12 → الآحاد (ضع 2، و+1 للعشرات) | Units (Set 2, +1 to Tens)",
              "الناتج النهائي: 552 | Final Result: 552",
            ],
            result: 552,
          },
          {
            id: "S06-m4-T3",
            question: "33 × 22",
            discrimination: "6+6=12 → تحالف (−5+1+10) | +6 = −5 + 1 + 10",
            steps: [
              "3×2=6 → المئات | Hundreds",
              "3×2=6 → العشرات | Tens",
              "3×2=6 → العشرات (6+6=12 → أزل 5، أضف 1، وأضف 1 للمئات) | Tens (6+6=12 → Clear 5, add 1, add 1 to Hundreds)",
              "3×2=6 → الآحاد | Units",
              "الناتج النهائي: 726 | Final Result: 726",
            ],
            result: 726,
          },
          {
            id: "S06-m4-T4",
            question: "23 × 24",
            discrimination: "6+8=14 → تحالف (−5+3+10) | +8 = −5 + 3 + 10",
            steps: [
              "2×2=4 → المئات | Hundreds",
              "3×2=6 → العشرات | Tens",
              "2×4=8 → العشرات (6+8=14 → أزل 5، أضف 3، وأضف 1 للمئات) | Tens (6+8=14 → Clear 5, add 3, add 1 to Hundreds)",
              "3×4=12 → الآحاد (ضع 2، و+1 للعشرات) | Units (Set 2, +1 to Tens)",
              "الناتج النهائي: 552 | Final Result: 552",
            ],
            result: 552,
          },
          {
            id: "S06-m4-T5",
            question: "43 × 22",
            discrimination: "6+8=14 → تحالف (−5+3+10) | +8 = −5 + 3 + 10",
            steps: [
              "4×2=8 → المئات | Hundreds",
              "3×2=6 → العشرات | Tens",
              "4×2=8 → العشرات (6+8=14 → أزل 5، أضف 3، وأضف 1 للمئات) | Tens (6+8=14 → Clear 5, add 3, add 1 to Hundreds)",
              "3×2=6 → الآحاد | Units",
              "الناتج النهائي: 946 | Final Result: 946",
            ],
            result: 946,
          },
        ],
      },
    },
  ],

  outro: {
    summary: "أتقنت الضرب (2×2) بأربع خطوات سحرية متتابعة من اليسار لليمين وفهمت كافة قواعد التمكّن والترحيل! | You mastered 2x2 multiplication with 4 left-to-right magic steps and all carry rules!",
    encouragement: "🎉 أنت بطل السوروبان الخارق ومستعد لأصعب التحديات! | 🎉 You are a Soroban Super Champion ready for the greatest challenges!",
    totalExamples: 20,
  },

  estimatedMinutes: 20,
  xpReward: 15,
};

export default S06_LESSON;
