// src/curriculum/lessons/L2/S06.ts
// 🔢 درس S06: الضرب (2 × 2) — منهجية تاكاشي كوجيما المتقدمة للأطفال
// القاعدة الذهبية: أربع خطوات متعاقبة من المنزلة الكبيرة إلى الصغيرة (من اليسار إلى اليمين)

import type { LessonNode } from "../types";

export const S06_LESSON: LessonNode = {
  id: "S06",
  skillId: "S06",
  levelId: "L2",
  order: 2,
  title: { ar: "الضرب (2 × 2)", en: "Multiplication (2×2)" },
  emoji: "🔢",
  tags: ["multiplication", "kids", "L2", "2x2", "left-to-right", "takashi-kojima"],

  modules: [
    // ═══════════════════════════════════════════════════════════
    // m1 — الضرب المباشر (2 × 2)
    // ═══════════════════════════════════════════════════════════
    {
      id: "m1",
      ruleCategory: "direct",
      title: "الضرب المباشر | Direct Multiplication",
      titleEn: "Direct Multiplication",
      emoji: "✨",
      miniStory: {
        title: "حقول الفلاح السحرية | The Magic Farmer's Fields",
        emoji: "🌾",
        story: "يا أبطال! بنزرع 11 صف بـ 11 حبة.. أربع خطوات سهلة من المئات للآحاد والخرزات مفتوحة وجاهزة.. والناتج السحري: 121! | Champions! We plant 11 rows × 11 seeds. 4 easy steps from hundreds to units, beads are ready, magic result: 121!",
        storyAudioText: "يا أبطال.. دعونا نحسب إحدى عشر في إحدى عشر.. نضرب العشرات في العشرات أولاً: واحد في واحد يساوي واحد في المئات.. ثم الآحاد في العشرات: واحد في واحد يساوي واحد في العشرات.. ثم العشرات في الآحاد: واحد في واحد يساوي واحد في العشرات.. واحد زائد واحد يساوي اثنين.. ثم الآحاد في الآحاد: واحد في واحد يساوي واحد في الآحاد.. والناتج: مئة وواحد وعشرون! | Champions.. let's calculate 11 times 11.. Multiply tens by tens first: 1 times 1 equals 1 in hundreds.. Then units by tens: 1 times 1 equals 1 in tens.. Then tens by units: 1 times 1 equals 1 in tens.. 1 plus 1 equals 2.. Then units by units: 1 times 1 equals 1 in units.. Result is 121!",
        storyAudioId: 25,
      },
      rule: {
        description: "خريطة الأبطال الأربعة من اليسار لليمين: 1. مئات (عشرات×عشرات) · 2. عشرات (آحاد×عشرات) · 3. إضافة للعشرات (عشرات×آحاد) · 4. آحاد (آحاد×آحاد) | Four steps Left-to-Right: 1. Hundreds (Tens×Tens) · 2. Tens (Units×Tens) · 3. Add to Tens (Tens×Units) · 4. Units (Units×Units)",
      },
      condition: {
        formula: "كل النواتج الجزئية مباشرة | All partial products direct",
        explanation: "الخرزات مفتوحة تماماً ولا نحتاج أصدقاء أو استعارة! | Beads are ready; no friends or carrying needed!",
      },
      discrimination: {
        steps: [
          {
            question: "هل تبدأ بالمنزلة الكبيرة (المئات) أولاً؟ | Do you start with the largest place value (Hundreds) first?",
            type: "yes-no",
            actual: "المئات = عشرات × عشرات | Hundreds = Tens × Tens",
            answer: "نعم → (عشرات × عشرات) تستقر في المئات بالإبهام 👍⬆️ | Yes → (Tens × Tens) lands in Hundreds with thumb 👍⬆️",
            hint: "ابدأ دائماً من جهة اليسار | Always start from the left",
          },
          {
            question: "هل الخرزات الفارغة في كل عمود تكفي؟ | Are there enough free beads in each rod?",
            type: "comparison",
            actual: "الخرزات ≥ الناتج | Beads ≥ Product",
            answer: "نعم → أضف مباشرة بالإبهام 👍⬆️ أو بكماشة مغلقة 🗜️ | Yes → Add directly with thumb 👍⬆️ or closed pinch 🗜️",
            hint: "افحص كل خطوة قبل تحريك الخرزات | Check each step before moving beads",
          },
        ],
        decision: "ضرب مباشر — أربع خطوات سريعة من المئات إلى الآحاد! | Direct Multiplication — 4 quick steps from Hundreds to Units!",
      },
      watchPhase: {
        examples: [
          {
            id: "S06-m1-E1",
            question: "11 × 11",
            discrimination: "المئات: 1×1=1 · العشرات: 1×1=1 · إضافة العشرات: 1×1=1 (1+1=2) · الآحاد: 1×1=1 | Direct 4 steps",
            rule: "أربع خطوات مباشرة من اليسار إلى اليمين | 4 direct steps left-to-right",
            fingerMovement: "ضع 1 للمئات بالإبهام 👍⬆️ · ضع 1 للعشرات بالإبهام 👍⬆️ · أضف 1 للعشرات بالإبهام 👍⬆️ · ضع 1 للآحاد بالإبهام 👍⬆️ | Set 1 in hundreds with thumb 👍⬆️ · Set 1 in tens with thumb 👍⬆️ · Add 1 to tens with thumb 👍⬆️ · Set 1 in units with thumb 👍⬆️",
            steps: [
              "المئات: 1 × 1 = 1 → ارفع 1 خرزة بالمئات بالإبهام 👍⬆️ | Hundreds: 1 × 1 = 1 → Lift 1 bead in Hundreds with thumb 👍⬆️",
              "العشرات: 1 × 1 = 1 → ارفع 1 خرزة بالعشرات بالإبهام 👍⬆️ | Tens: 1 × 1 = 1 → Lift 1 bead in Tens with thumb 👍⬆️",
              "العشرات: 1 × 1 = 1 → أضف 1 للعشرات بالإبهام 👍⬆️ → العشرات = 2 | Tens: 1 × 1 = 1 → Add 1 to Tens with thumb 👍⬆️ → Tens = 2",
              "الآحاد: 1 × 1 = 1 → ارفع 1 خرزة بالآحاد بالإبهام 👍⬆️ | Units: 1 × 1 = 1 → Lift 1 bead in Units with thumb 👍⬆️",
              "الناتج النهائي: 1 مئة + 2 عشرات + 1 آحاد = 121 | Final Result: 1 hundred + 2 tens + 1 unit = 121",
            ],
            result: 121,
            beadVisual: "1 مئة + 2 عشرات + 1 آحاد = 121 | 1 Hundred + 2 Tens + 1 Unit = 121",
          },
          {
            id: "S06-m1-E2",
            question: "12 × 11",
            discrimination: "المئات: 1×1=1 · العشرات: 2×1=2 · إضافة العشرات: 1×1=1 (2+1=3) · الآحاد: 2×1=2 | Direct 4 steps",
            rule: "أربع خطوات مباشرة من اليسار إلى اليمين | 4 direct steps left-to-right",
            fingerMovement: "ضع 1 للمئات بالإبهام 👍⬆️ · ضع 2 للعشرات بالإبهام 👍⬆️ · أضف 1 للعشرات بالإبهام 👍⬆️ · ضع 2 للآحاد بالإبهام 👍⬆️ | Set 1 in hundreds with thumb 👍⬆️ · Set 2 in tens with thumb 👍⬆️ · Add 1 to tens with thumb 👍⬆️ · Set 2 in units with thumb 👍⬆️",
            steps: [
              "المئات: 1 × 1 = 1 → ارفع 1 بالمئات بالإبهام 👍⬆️ | Hundreds: 1 × 1 = 1 → Lift 1 in Hundreds with thumb 👍⬆️",
              "العشرات: 2 × 1 = 2 → ارفع 2 بالعشرات بالإبهام 👍⬆️ | Tens: 2 × 1 = 2 → Lift 2 in Tens with thumb 👍⬆️",
              "العشرات: 1 × 1 = 1 → أضف 1 للعشرات بالإبهام 👍⬆️ → العشرات = 3 | Tens: 1 × 1 = 1 → Add 1 to Tens with thumb 👍⬆️ → Tens = 3",
              "الآحاد: 2 × 1 = 2 → ارفع 2 بالآحاد بالإبهام 👍⬆️ | Units: 2 × 1 = 2 → Lift 2 in Units with thumb 👍⬆️",
              "الناتج النهائي: 1 مئة + 3 عشرات + 2 آحاد = 132 | Final Result: 1 hundred + 3 tens + 2 units = 132",
            ],
            result: 132,
            beadVisual: "1 مئة + 3 عشرات + 2 آحاد = 132 | 1 Hundred + 3 Tens + 2 Units = 132",
          },
          {
            id: "S06-m1-E3",
            question: "13 × 11",
            discrimination: "المئات: 1×1=1 · العشرات: 3×1=3 · إضافة العشرات: 1×1=1 (3+1=4) · الآحاد: 3×1=3 | Direct 4 steps",
            rule: "أربع خطوات مباشرة من اليسار إلى اليمين | 4 direct steps left-to-right",
            fingerMovement: "ضع 1 للمئات بالإبهام 👍⬆️ · ضع 3 للعشرات بالإبهام 👍⬆️ · أضف 1 للعشرات بالإبهام 👍⬆️ · ضع 3 للآحاد بالإبهام 👍⬆️ | Set 1 in hundreds with thumb 👍⬆️ · Set 3 in tens with thumb 👍⬆️ · Add 1 to tens with thumb 👍⬆️ · Set 3 in units with thumb 👍⬆️",
            steps: [
              "المئات: 1 × 1 = 1 → ارفع 1 بالمئات بالإبهام 👍⬆️ | Hundreds: 1 × 1 = 1 → Lift 1 in Hundreds with thumb 👍⬆️",
              "العشرات: 3 × 1 = 3 → ارفع 3 بالعشرات بالإبهام 👍⬆️ | Tens: 3 × 1 = 3 → Lift 3 in Tens with thumb 👍⬆️",
              "العشرات: 1 × 1 = 1 → أضف 1 للعشرات بالإبهام 👍⬆️ → العشرات = 4 | Tens: 1 × 1 = 1 → Add 1 to Tens with thumb 👍⬆️ → Tens = 4",
              "الآحاد: 3 × 1 = 3 → ارفع 3 بالآحاد بالإبهام 👍⬆️ | Units: 3 × 1 = 3 → Lift 3 in Units with thumb 👍⬆️",
              "الناتج النهائي: 1 مئة + 4 عشرات + 3 آحاد = 143 | Final Result: 1 hundred + 4 tens + 3 units = 143",
            ],
            result: 143,
            beadVisual: "1 مئة + 4 عشرات + 3 آحاد = 143 | 1 Hundred + 4 Tens + 3 Units = 143",
          },
          {
            id: "S06-m1-E4",
            question: "21 × 11",
            discrimination: "المئات: 2×1=2 · العشرات: 1×1=1 · إضافة العشرات: 2×1=2 (1+2=3) · الآحاد: 1×1=1 | Direct 4 steps",
            rule: "أربع خطوات مباشرة من اليسار إلى اليمين | 4 direct steps left-to-right",
            fingerMovement: "ضع 2 للمئات بالإبهام 👍⬆️ · ضع 1 للعشرات بالإبهام 👍⬆️ · أضف 2 للعشرات بالإبهام 👍⬆️ · ضع 1 للآحاد بالإبهام 👍⬆️ | Set 2 in hundreds with thumb 👍⬆️ · Set 1 in tens with thumb 👍⬆️ · Add 2 to tens with thumb 👍⬆️ · Set 1 in units with thumb 👍⬆️",
            steps: [
              "المئات: 2 × 1 = 2 → ارفع 2 بالمئات بالإبهام 👍⬆️ | Hundreds: 2 × 1 = 2 → Lift 2 in Hundreds with thumb 👍⬆️",
              "العشرات: 1 × 1 = 1 → ارفع 1 بالعشرات بالإبهام 👍⬆️ | Tens: 1 × 1 = 1 → Lift 1 in Tens with thumb 👍⬆️",
              "العشرات: 2 × 1 = 2 → أضف 2 للعشرات بالإبهام 👍⬆️ → العشرات = 3 | Tens: 2 × 1 = 2 → Add 2 to Tens with thumb 👍⬆️ → Tens = 3",
              "الآحاد: 1 × 1 = 1 → ارفع 1 بالآحاد بالإبهام 👍⬆️ | Units: 1 × 1 = 1 → Lift 1 in Units with thumb 👍⬆️",
              "الناتج النهائي: 2 مئات + 3 عشرات + 1 آحاد = 231 | Final Result: 2 hundreds + 3 tens + 1 unit = 231",
            ],
            result: 231,
            beadVisual: "2 مئات + 3 عشرات + 1 آحاد = 231 | 2 Hundreds + 3 Tens + 1 Unit = 231",
          },
          {
            id: "S06-m1-E5",
            question: "22 × 11",
            discrimination: "المئات: 2×1=2 · العشرات: 2×1=2 · إضافة العشرات: 2×1=2 (2+2=4) · الآحاد: 2×1=2 | Direct 4 steps",
            rule: "أربع خطوات مباشرة من اليسار إلى اليمين | 4 direct steps left-to-right",
            fingerMovement: "ضع 2 للمئات بالإبهام 👍⬆️ · ضع 2 للعشرات بالإبهام 👍⬆️ · أضف 2 للعشرات بالإبهام 👍⬆️ · ضع 2 للآحاد بالإبهام 👍⬆️ | Set 2 in hundreds with thumb 👍⬆️ · Set 2 in tens with thumb 👍⬆️ · Add 2 to tens with thumb 👍⬆️ · Set 2 in units with thumb 👍⬆️",
            steps: [
              "المئات: 2 × 1 = 2 → ارفع 2 بالمئات بالإبهام 👍⬆️ | Hundreds: 2 × 1 = 2 → Lift 2 in Hundreds with thumb 👍⬆️",
              "العشرات: 2 × 1 = 2 → ارفع 2 بالعشرات بالإبهام 👍⬆️ | Tens: 2 × 1 = 2 → Lift 2 in Tens with thumb 👍⬆️",
              "العشرات: 2 × 1 = 2 → أضف 2 للعشرات بالإبهام 👍⬆️ → العشرات = 4 | Tens: 2 × 1 = 2 → Add 2 to Tens with thumb 👍⬆️ → Tens = 4",
              "الآحاد: 2 × 1 = 2 → ارفع 2 بالآحاد بالإبهام 👍⬆️ | Units: 2 × 1 = 2 → Lift 2 in Units with thumb 👍⬆️",
              "الناتج النهائي: 2 مئات + 4 عشرات + 2 آحاد = 242 | Final Result: 2 hundreds + 4 tens + 2 units = 242",
            ],
            result: 242,
            beadVisual: "2 مئات + 4 عشرات + 2 آحاد = 242 | 2 Hundreds + 4 Tens + 2 Units = 242",
          },
        ],
      },
      tryPhase: {
        exercises: [
          {
            id: "S06-m1-T1",
            question: "11 × 22",
            discrimination: "المئات: 1×2=2 · العشرات: 1×2=2 · إضافة العشرات: 1×2=2 (2+2=4) · الآحاد: 1×2=2 | Direct",
            steps: [
              "المئات: 1 × 2 = 2 → ارفع 2 بالمئات بالإبهام 👍⬆️ | Hundreds: 1 × 2 = 2 → Lift 2 in Hundreds with thumb 👍⬆️",
              "العشرات: 1 × 2 = 2 → ارفع 2 بالعشرات بالإبهام 👍⬆️ | Tens: 1 × 2 = 2 → Lift 2 in Tens with thumb 👍⬆️",
              "العشرات: 1 × 2 = 2 → أضف 2 للعشرات بالإبهام 👍⬆️ (2+2=4) | Tens: 1 × 2 = 2 → Add 2 to Tens with thumb 👍⬆️ (2+2=4)",
              "الآحاد: 1 × 2 = 2 → ارفع 2 بالآحاد بالإبهام 👍⬆️ | Units: 1 × 2 = 2 → Lift 2 in Units with thumb 👍⬆️",
              "الناتج النهائي: 242 | Final Result: 242",
            ],
            result: 242,
          },
          {
            id: "S06-m1-T2",
            question: "12 × 11",
            discrimination: "المئات: 1×1=1 · العشرات: 2×1=2 · إضافة العشرات: 1×1=1 (2+1=3) · الآحاد: 2×1=2 | Direct",
            steps: [
              "المئات: 1 × 1 = 1 → ارفع 1 بالمئات بالإبهام 👍⬆️ | Hundreds: 1 × 1 = 1 → Lift 1 in Hundreds with thumb 👍⬆️",
              "العشرات: 2 × 1 = 2 → ارفع 2 بالعشرات بالإبهام 👍⬆️ | Tens: 2 × 1 = 2 → Lift 2 in Tens with thumb 👍⬆️",
              "العشرات: 1 × 1 = 1 → أضف 1 للعشرات بالإبهام 👍⬆️ (2+1=3) | Tens: 1 × 1 = 1 → Add 1 to Tens with thumb 👍⬆️ (2+1=3)",
              "الآحاد: 2 × 1 = 2 → ارفع 2 بالآحاد بالإبهام 👍⬆️ | Units: 2 × 1 = 2 → Lift 2 in Units with thumb 👍⬆️",
              "الناتج النهائي: 132 | Final Result: 132",
            ],
            result: 132,
          },
          {
            id: "S06-m1-T3",
            question: "21 × 11",
            discrimination: "المئات: 2×1=2 · العشرات: 1×1=1 · إضافة العشرات: 2×1=2 (1+2=3) · الآحاد: 1×1=1 | Direct",
            steps: [
              "المئات: 2 × 1 = 2 → ارفع 2 بالمئات بالإبهام 👍⬆️ | Hundreds: 2 × 1 = 2 → Lift 2 in Hundreds with thumb 👍⬆️",
              "العشرات: 1 × 1 = 1 → ارفع 1 بالعشرات بالإبهام 👍⬆️ | Tens: 1 × 1 = 1 → Lift 1 in Tens with thumb 👍⬆️",
              "العشرات: 2 × 1 = 2 → أضف 2 للعشرات بالإبهام 👍⬆️ (1+2=3) | Tens: 2 × 1 = 2 → Add 2 to Tens with thumb 👍⬆️ (1+2=3)",
              "الآحاد: 1 × 1 = 1 → ارفع 1 بالآحاد بالإبهام 👍⬆️ | Units: 1 × 1 = 1 → Lift 1 in Units with thumb 👍⬆️",
              "الناتج النهائي: 231 | Final Result: 231",
            ],
            result: 231,
          },
          {
            id: "S06-m1-T4",
            question: "11 × 13",
            discrimination: "المئات: 1×1=1 · العشرات: 1×3=3 · إضافة العشرات: 1×1=1 (3+1=4) · الآحاد: 1×3=3 | Direct",
            steps: [
              "المئات: 1 × 1 = 1 → ارفع 1 بالمئات بالإبهام 👍⬆️ | Hundreds: 1 × 1 = 1 → Lift 1 in Hundreds with thumb 👍⬆️",
              "العشرات: 1 × 3 = 3 → ارفع 3 بالعشرات بالإبهام 👍⬆️ | Tens: 1 × 3 = 3 → Lift 3 in Tens with thumb 👍⬆️",
              "العشرات: 1 × 1 = 1 → أضف 1 للعشرات بالإبهام 👍⬆️ (3+1=4) | Tens: 1 × 1 = 1 → Add 1 to Tens with thumb 👍⬆️ (3+1=4)",
              "الآحاد: 1 × 3 = 3 → ارفع 3 بالآحاد بالإبهام 👍⬆️ | Units: 1 × 3 = 3 → Lift 3 in Units with thumb 👍⬆️",
              "الناتج النهائي: 143 | Final Result: 143",
            ],
            result: 143,
          },
          {
            id: "S06-m1-T5",
            question: "11 × 31",
            discrimination: "المئات: 1×3=3 · العشرات: 1×1=1 · إضافة العشرات: 1×3=3 (1+3=4) · الآحاد: 1×1=1 | Direct",
            steps: [
              "المئات: 1 × 3 = 3 → ارفع 3 بالمئات بالإبهام 👍⬆️ | Hundreds: 1 × 3 = 3 → Lift 3 in Hundreds with thumb 👍⬆️",
              "العشرات: 1 × 1 = 1 → ارفع 1 بالعشرات بالإبهام 👍⬆️ | Tens: 1 × 1 = 1 → Lift 1 in Tens with thumb 👍⬆️",
              "العشرات: 1 × 3 = 3 → أضف 3 للعشرات بالإبهام 👍⬆️ (1+3=4) | Tens: 1 × 3 = 3 → Add 3 to Tens with thumb 👍⬆️ (1+3=4)",
              "الآحاد: 1 × 1 = 1 → ارفع 1 بالآحاد بالإبهام 👍⬆️ | Units: 1 × 1 = 1 → Lift 1 in Units with thumb 👍⬆️",
              "الناتج النهائي: 341 | Final Result: 341",
            ],
            result: 341,
          },
        ],
      },
    },

    // ═══════════════════════════════════════════════════════════
    // m2 — الضرب بأصدقاء 5 (2 × 2)
    // ═══════════════════════════════════════════════════════════
    {
      id: "m2",
      ruleCategory: "small_friends",
      title: "الضرب بأصدقاء 5 | Friends of 5",
      titleEn: "Friends of 5",
      emoji: "🤝",
      miniStory: {
        title: "الجدة 5 تتدخل | Grandma 5 Helps",
        emoji: "👵",
        story: "13 صف بـ 12 شجرة! لما جمعنا خطوتي العشرات ازدحم العمود.. نزلت تيتا 5 الحنونة بالسبابة وطردت الصديق للإبهام بنزول مزدوج.. والناتج: 156! | 13 rows × 12 trees! When adding tens steps, the column got crowded.. Grandma 5 came down with index & pushed friend down with thumb in a Double Drop.. Result: 156!",
        storyAudioText: "ثلاثة عشر في اثني عشر.. العشرات في العشرات: واحد في واحد يساوي واحد في المئات.. الآحاد في العشرات: ثلاثة في واحد يساوي ثلاثة في العشرات.. العشرات في الآحاد: واحد في اثنين يساوي اثنين.. نضيف اثنين لثلاثة بأصدقاء خمسة: أنزل خمسة واطرح ثلاثة بنزول مزدوج.. الآحاد في الآحاد: ثلاثة في اثنين يساوي ستة.. الناتج: مئة وستة وخمسون! | 13 times 12.. Tens by tens: 1 times 1 equals 1 in hundreds.. Units by tens: 3 times 1 equals 3 in tens.. Tens by units: 1 times 2 equals 2.. Add 2 to 3 via Friends of 5: drop 5 and subtract 3 with Double Drop.. Units by units: 3 times 2 equals 6.. Result is 156!",
        storyAudioId: 26,
      },
      rule: {
        description: "أصدقاء 5 👵: عندما لا تكفي الخرزات السفلية في عمود العشرات، أنزل 5 بالسبابة ⬇️ واطرد صديق العدد بالإبهام ⬇️ بنزول مزدوج ⬇️⬇️! | Friends of 5 👵: When lower beads are full in tens rod, lower top bead 5 with index ⬇️ and push down the friend with thumb ⬇️ in a Double Drop ⬇️⬇️!",
        cases: [
          { from: 1, formula: "+1 = +5 − 4 (صديق 1 هو 4) | +1 = +5 − 4 (1's friend is 4)" },
          { from: 2, formula: "+2 = +5 − 3 (صديق 2 هو 3) | +2 = +5 − 3 (2's friend is 3)" },
          { from: 3, formula: "+3 = +5 − 2 (صديق 3 هو 2) | +3 = +5 − 2 (3's friend is 2)" },
          { from: 4, formula: "+4 = +5 − 1 (صديق 4 هو 1) | +4 = +5 − 1 (4's friend is 1)" },
        ],
      },
      condition: {
        formula: "السفليات غير كافية · خرزة 5 متاحة | Lower beads insufficient · Top bead 5 available",
        explanation: "نحتاج إضافة خرزات في العشرات والسفليات ممتلئة — الجدة 5 تتدخل بنزول مزدوج! | Need to add tens, lower beads full — Grandma 5 steps in with a Double Drop!",
      },
      friendsTable: {
        title: "أصدقاء 5 الصغار | Small Friends of 5",
        pairs: [
          { from: 1, to: 4 },
          { from: 2, to: 3 },
          { from: 3, to: 2 },
          { from: 4, to: 1 },
        ],
      },
      discrimination: {
        steps: [
          {
            question: "هل الخرزات السفلية في العشرات غير كافية لإضافة ناتج الخطوة الثالثة؟ | Are lower beads in Tens rod insufficient for step 3?",
            type: "comparison",
            actual: "السفليات < المطلوب | Lower beads < Required",
            answer: "نعم → نلجأ لأصدقاء 5 | Yes → Use Friends of 5",
            hint: "تأكد أن خرزة 5 العلوية غير مفعّلة | Ensure top bead 5 is available",
          },
          {
            question: "هل خرزة 5 متاحة للنزول؟ | Is bead 5 available to drop?",
            type: "yes-no",
            actual: "خرزة 5 غير مفعّلة | Bead 5 inactive",
            answer: "نعم → نفّذ نزول مزدوج ⬇️⬇️ | Yes → Perform Double Drop ⬇️⬇️",
            hint: "+n = +5 − (5−n)",
          },
        ],
        decision: "أصدقاء 5 — نزول مزدوج ⬇️⬇️: السبابة تفعّل 5 ⬇️ والإبهام يطرد الصديق ⬇️! | Friends of 5 — Double Drop ⬇️⬇️: Index activates 5 ⬇️ & thumb pushes friend down ⬇️!",
      },
      watchPhase: {
        examples: [
          {
            id: "S06-m2-E1",
            question: "14 × 11",
            discrimination: "المئات: 1×1=1 · العشرات: 4×1=4 · إضافة العشرات: 1×1=1 (4+1=5 بأصدقاء 5) · الآحاد: 4×1=4 | Friends of 5 (+1)",
            rule: "+1 = +5 − 4 (صديق 1 هو 4) | +1 = +5 − 4 (1's friend is 4)",
            fingerMovement: "ضع 1 للمئات بالإبهام 👍⬆️ · ضع 4 للعشرات بالإبهام 👍⬆️ · نزول مزدوج ⬇️⬇️ على العشرات (سبابة تفعّل 5 ⬇️ + إبهام يطرد 4 ⬇️) · ضع 4 للآحاد بالإبهام 👍⬆️ | Set 1 in hundreds with thumb 👍⬆️ · Set 4 in tens with thumb 👍⬆️ · Double Drop ⬇️⬇️ on tens (index activates 5 ⬇️ + thumb pushes 4 down ⬇️) · Set 4 in units with thumb 👍⬆️",
            steps: [
              "المئات: 1 × 1 = 1 → ارفع 1 بالمئات بالإبهام 👍⬆️ | Hundreds: 1 × 1 = 1 → Lift 1 in Hundreds with thumb 👍⬆️",
              "العشرات: 4 × 1 = 4 → ارفع 4 بالعشرات بالإبهام 👍⬆️ | Tens: 4 × 1 = 4 → Lift 4 in Tens with thumb 👍⬆️",
              "العشرات: 1 × 1 = 1 → إضافة 1 للعشرات بأصدقاء 5 (+1 = +5 − 4) بنزول مزدوج ⬇️⬇️ (السبابة تفعّل 5 ⬇️ والإبهام يطرد 4 ⬇️) → العشرات = 5 | Tens: 1 × 1 = 1 → Add 1 to Tens (+1 = +5 − 4) with Double Drop ⬇️⬇️ (index activates 5 ⬇️ & thumb pushes 4 down ⬇️) → Tens = 5",
              "الآحاد: 4 × 1 = 4 → ارفع 4 بالآحاد بالإبهام 👍⬆️ | Units: 4 × 1 = 4 → Lift 4 in Units with thumb 👍⬆️",
              "الناتج النهائي: 1 مئة + 5 عشرات + 4 آحاد = 154 | Final Result: 1 hundred + 5 tens + 4 units = 154",
            ],
            result: 154,
            beadVisual: "1 مئة + 5 عشرات + 4 آحاد = 154 | 1 Hundred + 5 Tens + 4 Units = 154",
          },
          {
            id: "S06-m2-E2",
            question: "13 × 12",
            discrimination: "المئات: 1×1=1 · العشرات: 3×1=3 · إضافة العشرات: 1×2=2 (3+2=5 بأصدقاء 5) · الآحاد: 3×2=6 | Friends of 5 (+2)",
            rule: "+2 = +5 − 3 (صديق 2 هو 3) | +2 = +5 − 3 (2's friend is 3)",
            fingerMovement: "ضع 1 للمئات بالإبهام 👍⬆️ · ضع 3 للعشرات بالإبهام 👍⬆️ · نزول مزدوج ⬇️⬇️ على العشرات (سبابة تفعّل 5 ⬇️ + إبهام يطرد 3 ⬇️) · ضع 6 للآحاد بكماشة مغلقة 🗜️ | Set 1 in hundreds with thumb 👍⬆️ · Set 3 in tens with thumb 👍⬆️ · Double Drop ⬇️⬇️ on tens (index activates 5 ⬇️ + thumb pushes 3 down ⬇️) · Set 6 in units with closed pinch 🗜️",
            steps: [
              "المئات: 1 × 1 = 1 → ارفع 1 بالمئات بالإبهام 👍⬆️ | Hundreds: 1 × 1 = 1 → Lift 1 in Hundreds with thumb 👍⬆️",
              "العشرات: 3 × 1 = 3 → ارفع 3 بالعشرات بالإبهام 👍⬆️ | Tens: 3 × 1 = 3 → Lift 3 in Tens with thumb 👍⬆️",
              "العشرات: 1 × 2 = 2 → إضافة 2 للعشرات بأصدقاء 5 (+2 = +5 − 3) بنزول مزدوج ⬇️⬇️ (السبابة تفعّل 5 ⬇️ والإبهام يطرد 3 ⬇️) → العشرات = 5 | Tens: 1 × 2 = 2 → Add 2 to Tens (+2 = +5 − 3) with Double Drop ⬇️⬇️ (index activates 5 ⬇️ & thumb pushes 3 down ⬇️) → Tens = 5",
              "الآحاد: 3 × 2 = 6 → ضع 6 بالآحاد بكماشة مغلقة 🗜️ | Units: 3 × 2 = 6 → Set 6 in Units with closed pinch 🗜️",
              "الناتج النهائي: 1 مئة + 5 عشرات + 6 آحاد = 156 | Final Result: 1 hundred + 5 tens + 6 units = 156",
            ],
            result: 156,
            beadVisual: "1 مئة + 5 عشرات + 6 آحاد = 156 | 1 Hundred + 5 Tens + 6 Units = 156",
          },
          {
            id: "S06-m2-E3",
            question: "12 × 13",
            discrimination: "المئات: 1×1=1 · العشرات: 2×1=2 · إضافة العشرات: 1×3=3 (2+3=5 بأصدقاء 5) · الآحاد: 2×3=6 | Friends of 5 (+3)",
            rule: "+3 = +5 − 2 (صديق 3 هو 2) | +3 = +5 − 2 (3's friend is 2)",
            fingerMovement: "ضع 1 للمئات بالإبهام 👍⬆️ · ضع 2 للعشرات بالإبهام 👍⬆️ · نزول مزدوج ⬇️⬇️ على العشرات (سبابة تفعّل 5 ⬇️ + إبهام يطرد 2 ⬇️) · ضع 6 للآحاد بكماشة مغلقة 🗜️ | Set 1 in hundreds with thumb 👍⬆️ · Set 2 in tens with thumb 👍⬆️ · Double Drop ⬇️⬇️ on tens (index activates 5 ⬇️ + thumb pushes 2 down ⬇️) · Set 6 in units with closed pinch 🗜️",
            steps: [
              "المئات: 1 × 1 = 1 → ارفع 1 بالمئات بالإبهام 👍⬆️ | Hundreds: 1 × 1 = 1 → Lift 1 in Hundreds with thumb 👍⬆️",
              "العشرات: 2 × 1 = 2 → ارفع 2 بالعشرات بالإبهام 👍⬆️ | Tens: 2 × 1 = 2 → Lift 2 in Tens with thumb 👍⬆️",
              "العشرات: 1 × 3 = 3 → إضافة 3 للعشرات بأصدقاء 5 (+3 = +5 − 2) بنزول مزدوج ⬇️⬇️ (السبابة تفعّل 5 ⬇️ والإبهام يطرد 2 ⬇️) → العشرات = 5 | Tens: 1 × 3 = 3 → Add 3 to Tens (+3 = +5 − 2) with Double Drop ⬇️⬇️ (index activates 5 ⬇️ & thumb pushes 2 down ⬇️) → Tens = 5",
              "الآحاد: 2 × 3 = 6 → ضع 6 بالآحاد بكماشة مغلقة 🗜️ | Units: 2 × 3 = 6 → Set 6 in Units with closed pinch 🗜️",
              "الناتج النهائي: 1 مئة + 5 عشرات + 6 آحاد = 156 | Final Result: 1 hundred + 5 tens + 6 units = 156",
            ],
            result: 156,
            beadVisual: "1 مئة + 5 عشرات + 6 آحاد = 156 | 1 Hundred + 5 Tens + 6 Units = 156",
          },
          {
            id: "S06-m2-E4",
            question: "23 × 12",
            discrimination: "المئات: 2×1=2 · العشرات: 3×1=3 · إضافة العشرات: 2×2=4 (3+4=7 بأصدقاء 5) · الآحاد: 3×2=6 | Friends of 5 (+4)",
            rule: "+4 = +5 − 1 (صديق 4 هو 1) | +4 = +5 − 1 (4's friend is 1)",
            fingerMovement: "ضع 2 للمئات بالإبهام 👍⬆️ · ضع 3 للعشرات بالإبهام 👍⬆️ · نزول مزدوج ⬇️⬇️ على العشرات (سبابة تفعّل 5 ⬇️ + إبهام يطرد 1 ⬇️) · ضع 6 للآحاد بكماشة مغلقة 🗜️ | Set 2 in hundreds with thumb 👍⬆️ · Set 3 in tens with thumb 👍⬆️ · Double Drop ⬇️⬇️ on tens (index activates 5 ⬇️ + thumb pushes 1 down ⬇️) · Set 6 in units with closed pinch 🗜️",
            steps: [
              "المئات: 2 × 1 = 2 → ارفع 2 بالمئات بالإبهام 👍⬆️ | Hundreds: 2 × 1 = 2 → Lift 2 in Hundreds with thumb 👍⬆️",
              "العشرات: 3 × 1 = 3 → ارفع 3 بالعشرات بالإبهام 👍⬆️ | Tens: 3 × 1 = 3 → Lift 3 in Tens with thumb 👍⬆️",
              "العشرات: 2 × 2 = 4 → إضافة 4 للعشرات بأصدقاء 5 (+4 = +5 − 1) بنزول مزدوج ⬇️⬇️ (السبابة تفعّل 5 ⬇️ والإبهام يطرد 1 ⬇️) → العشرات = 7 | Tens: 2 × 2 = 4 → Add 4 to Tens (+4 = +5 − 1) with Double Drop ⬇️⬇️ (index activates 5 ⬇️ & thumb pushes 1 down ⬇️) → Tens = 7",
              "الآحاد: 3 × 2 = 6 → ضع 6 بالآحاد بكماشة مغلقة 🗜️ | Units: 3 × 2 = 6 → Set 6 in Units with closed pinch 🗜️",
              "الناتج النهائي: 2 مئات + 7 عشرات + 6 آحاد = 276 | Final Result: 2 hundreds + 7 tens + 6 units = 276",
            ],
            result: 276,
            beadVisual: "2 مئات + 7 عشرات + 6 آحاد = 276 | 2 Hundreds + 7 Tens + 6 Units = 276",
          },
          {
            id: "S06-m2-E5",
            question: "24 × 12",
            discrimination: "المئات: 2×1=2 · العشرات: 4×1=4 · إضافة العشرات: 2×2=4 (4+4=8 بأصدقاء 5) · الآحاد: 4×2=8 | Friends of 5 (+4)",
            rule: "+4 = +5 − 1 (صديق 4 هو 1) | +4 = +5 − 1 (4's friend is 1)",
            fingerMovement: "ضع 2 للمئات بالإبهام 👍⬆️ · ضع 4 للعشرات بالإبهام 👍⬆️ · نزول مزدوج ⬇️⬇️ على العشرات (سبابة تفعّل 5 ⬇️ + إبهام يطرد 1 ⬇️) · ضع 8 للآحاد بكماشة مغلقة 🗜️ | Set 2 in hundreds with thumb 👍⬆️ · Set 4 in tens with thumb 👍⬆️ · Double Drop ⬇️⬇️ on tens (index activates 5 ⬇️ + thumb pushes 1 down ⬇️) · Set 8 in units with closed pinch 🗜️",
            steps: [
              "المئات: 2 × 1 = 2 → ارفع 2 بالمئات بالإبهام 👍⬆️ | Hundreds: 2 × 1 = 2 → Lift 2 in Hundreds with thumb 👍⬆️",
              "العشرات: 4 × 1 = 4 → ارفع 4 بالعشرات بالإبهام 👍⬆️ | Tens: 4 × 1 = 4 → Lift 4 in Tens with thumb 👍⬆️",
              "العشرات: 2 × 2 = 4 → إضافة 4 للعشرات بأصدقاء 5 (+4 = +5 − 1) بنزول مزدوج ⬇️⬇️ (السبابة تفعّل 5 ⬇️ والإبهام يطرد 1 ⬇️) → العشرات = 8 | Tens: 2 × 2 = 4 → Add 4 to Tens (+4 = +5 − 1) with Double Drop ⬇️⬇️ (index activates 5 ⬇️ & thumb pushes 1 down ⬇️) → Tens = 8",
              "الآحاد: 4 × 2 = 8 → ضع 8 بالآحاد بكماشة مغلقة 🗜️ | Units: 4 × 2 = 8 → Set 8 in Units with closed pinch 🗜️",
              "الناتج النهائي: 2 مئات + 8 عشرات + 8 آحاد = 288 | Final Result: 2 hundreds + 8 tens + 8 units = 288",
            ],
            result: 288,
            beadVisual: "2 مئات + 8 عشرات + 8 آحاد = 288 | 2 Hundreds + 8 Tens + 8 Units = 288",
          },
        ],
      },
      tryPhase: {
        exercises: [
          {
            id: "S06-m2-T1",
            question: "14 × 12",
            discrimination: "4+2=6 بأصدقاء 5 (+2 = +5 − 3) | +2 = +5 − 3",
            steps: [
              "المئات: 1 × 1 = 1 → ارفع 1 بالمئات بالإبهام 👍⬆️ | Hundreds: 1 × 1 = 1 → Lift 1 in Hundreds with thumb 👍⬆️",
              "العشرات: 4 × 1 = 4 → ارفع 4 بالعشرات بالإبهام 👍⬆️ | Tens: 4 × 1 = 4 → Lift 4 in Tens with thumb 👍⬆️",
              "العشرات: 1 × 2 = 2 → إضافة 2 للعشرات بنزول مزدوج ⬇️⬇️ (+2 = +5 − 3) | Tens: 1 × 2 = 2 → Add 2 to Tens with Double Drop ⬇️⬇️ (+2 = +5 − 3)",
              "الآحاد: 4 × 2 = 8 → ضع 8 بكماشة مغلقة 🗜️ | Units: 4 × 2 = 8 → Set 8 with closed pinch 🗜️",
              "الناتج النهائي: 168 | Final Result: 168",
            ],
            result: 168,
          },
          {
            id: "S06-m2-T2",
            question: "13 × 13",
            discrimination: "3+3=6 بأصدقاء 5 (+3 = +5 − 2) | +3 = +5 − 2",
            steps: [
              "المئات: 1 × 1 = 1 → ارفع 1 بالمئات بالإبهام 👍⬆️ | Hundreds: 1 × 1 = 1 → Lift 1 in Hundreds with thumb 👍⬆️",
              "العشرات: 3 × 1 = 3 → ارفع 3 بالعشرات بالإبهام 👍⬆️ | Tens: 3 × 1 = 3 → Lift 3 in Tens with thumb 👍⬆️",
              "العشرات: 1 × 3 = 3 → إضافة 3 للعشرات بنزول مزدوج ⬇️⬇️ (+3 = +5 − 2) | Tens: 1 × 3 = 3 → Add 3 to Tens with Double Drop ⬇️⬇️ (+3 = +5 − 2)",
              "الآحاد: 3 × 3 = 9 → ضع 9 بكماشة مغلقة 🗜️ | Units: 3 × 3 = 9 → Set 9 with closed pinch 🗜️",
              "الناتج النهائي: 169 | Final Result: 169",
            ],
            result: 169,
          },
          {
            id: "S06-m2-T3",
            question: "14 × 11",
            discrimination: "4+1=5 بأصدقاء 5 (+1 = +5 − 4) | +1 = +5 − 4",
            steps: [
              "المئات: 1 × 1 = 1 → ارفع 1 بالمئات بالإبهام 👍⬆️ | Hundreds: 1 × 1 = 1 → Lift 1 in Hundreds with thumb 👍⬆️",
              "العشرات: 4 × 1 = 4 → ارفع 4 بالعشرات بالإبهام 👍⬆️ | Tens: 4 × 1 = 4 → Lift 4 in Tens with thumb 👍⬆️",
              "العشرات: 1 × 1 = 1 → إضافة 1 للعشرات بنزول مزدوج ⬇️⬇️ (+1 = +5 − 4) | Tens: 1 × 1 = 1 → Add 1 to Tens with Double Drop ⬇️⬇️ (+1 = +5 − 4)",
              "الآحاد: 4 × 1 = 4 → ارفع 4 بالإبهام 👍⬆️ | Units: 4 × 1 = 4 → Lift 4 with thumb 👍⬆️",
              "الناتج النهائي: 154 | Final Result: 154",
            ],
            result: 154,
          },
          {
            id: "S06-m2-T4",
            question: "23 × 12",
            discrimination: "3+4=7 بأصدقاء 5 (+4 = +5 − 1) | +4 = +5 − 1",
            steps: [
              "المئات: 2 × 1 = 2 → ارفع 2 بالمئات بالإبهام 👍⬆️ | Hundreds: 2 × 1 = 2 → Lift 2 in Hundreds with thumb 👍⬆️",
              "العشرات: 3 × 1 = 3 → ارفع 3 بالعشرات بالإبهام 👍⬆️ | Tens: 3 × 1 = 3 → Lift 3 in Tens with thumb 👍⬆️",
              "العشرات: 2 × 2 = 4 → إضافة 4 للعشرات بنزول مزدوج ⬇️⬇️ (+4 = +5 − 1) | Tens: 2 × 2 = 4 → Add 4 to Tens with Double Drop ⬇️⬇️ (+4 = +5 − 1)",
              "الآحاد: 3 × 2 = 6 → ضع 6 بكماشة مغلقة 🗜️ | Units: 3 × 2 = 6 → Set 6 with closed pinch 🗜️",
              "الناتج النهائي: 276 | Final Result: 276",
            ],
            result: 276,
          },
          {
            id: "S06-m2-T5",
            question: "24 × 11",
            discrimination: "4+2=6 بأصدقاء 5 (+2 = +5 − 3) | +2 = +5 − 3",
            steps: [
              "المئات: 2 × 1 = 2 → ارفع 2 بالمئات بالإبهام 👍⬆️ | Hundreds: 2 × 1 = 2 → Lift 2 in Hundreds with thumb 👍⬆️",
              "العشرات: 4 × 1 = 4 → ارفع 4 بالعشرات بالإبهام 👍⬆️ | Tens: 4 × 1 = 4 → Lift 4 in Tens with thumb 👍⬆️",
              "العشرات: 2 × 1 = 2 → إضافة 2 للعشرات بنزول مزدوج ⬇️⬇️ (+2 = +5 − 3) | Tens: 2 × 1 = 2 → Add 2 to Tens with Double Drop ⬇️⬇️ (+2 = +5 − 3)",
              "الآحاد: 4 × 1 = 4 → ارفع 4 بالإبهام 👍⬆️ | Units: 4 × 1 = 4 → Lift 4 with thumb 👍⬆️",
              "الناتج النهائي: 264 | Final Result: 264",
            ],
            result: 264,
          },
        ],
      },
    },

    // ═══════════════════════════════════════════════════════════
    // m3 — الضرب بأصدقاء 10 (2 × 2)
    // ═══════════════════════════════════════════════════════════
    {
      id: "m3",
      ruleCategory: "big_friends",
      title: "الضرب بأصدقاء 10 | Multiplication with Friends of 10",
      titleEn: "Multiplication with Friends of 10",
      emoji: "🌟",
      miniStory: {
        title: "العملاق 10 يطير للمئات | Giant 10 Leaps to Hundreds",
        emoji: "🦶",
        story: "19 صف بـ 11 زهرة! مجموع العشرات وصل 10 وما فوق؟ طلع العملاق 10 ليطرح المتمّم 9 بالسبابة ⬇️ ويطير خرزة للمئات بالإبهام ⬆️.. والناتج: 209! | 19 rows × 11 flowers! Tens sum reached 10 or more? Giant 10 steps in to subtract complement 9 with index ⬇️ & leap a bead to hundreds with thumb ⬆️.. Result: 209!",
        storyAudioText: "تسعة عشر في أحد عشر.. العشرات في العشرات: واحد في واحد يساوي واحد في المئات.. الآحاد في العشرات: تسعة في واحد يساوي تسعة في العشرات.. العشرات في الآحاد: واحد في واحد يساوي واحد.. تسعة زائد واحد يساوي عشرة.. العملاق عشرة يتدخل: اطرح تسعة وأضف خرزة في المئات.. الآحاد في الآحاد: تسعة في واحد يساوي تسعة.. الناتج: مئتان وتسعة! | 19 times 11.. Tens by tens: 1 times 1 equals 1 in hundreds.. Units by tens: 9 times 1 equals 9 in tens.. Tens by units: 1 times 1 equals 1.. 9 plus 1 equals 10.. Giant 10 steps in: subtract 9 and add 1 bead to hundreds.. Units by units: 9 times 1 equals 9.. Result is 209!",
        storyAudioId: 27,
      },
      rule: {
        description: "أصدقاء 10 🌟: عندما يتجاوز مجموع عمود العشرات 9، اطرح المتمّم بالسبابة ⬇️ وأضف 1 لعمود المئات الأيسر بالإبهام 👍⬆️! | Friends of 10 🌟: When tens sum exceeds 9, subtract complement with index ⬇️ and leap 1 bead to Hundreds rod with thumb 👍⬆️!",
        cases: [
          { from: 1, formula: "+1 = −9 + 10 (صديق 1 هو 9) | +1 = −9 + 10 (1's friend is 9)" },
          { from: 2, formula: "+2 = −8 + 10 (صديق 2 هو 8) | +2 = −8 + 10 (2's friend is 8)" },
          { from: 3, formula: "+3 = −7 + 10 (صديق 3 هو 7) | +3 = −7 + 10 (3's friend is 7)" },
          { from: 4, formula: "+4 = −6 + 10 (صديق 4 هو 6) | +4 = −6 + 10 (4's friend is 6)" },
          { from: 5, formula: "+5 = −5 + 10 (صديق 5 هو 5) | +5 = −5 + 10 (5's friend is 5)" },
          { from: 6, formula: "+6 = −4 + 10 (صديق 6 هو 4) | +6 = −4 + 10 (6's friend is 4)" },
          { from: 7, formula: "+7 = −3 + 10 (صديق 7 هو 3) | +7 = −3 + 10 (7's friend is 3)" },
          { from: 8, formula: "+8 = −2 + 10 (صديق 8 هو 2) | +8 = −2 + 10 (8's friend is 2)" },
          { from: 9, formula: "+9 = −1 + 10 (صديق 9 هو 1) | +9 = −1 + 10 (9's friend is 1)" },
        ],
      },
      condition: {
        formula: "مجموع العشرات ≥ 10 | Tens sum ≥ 10",
        explanation: "تجاوز العمود العدد 9 — نقفز لعمود المئات الأيسر مباشرة! | Column exceeded 9 — leap directly to Hundreds rod on the left!",
      },
      friendsTable: {
        title: "أصدقاء 10 الكبار | Big Friends of 10",
        pairs: [
          { from: 1, to: 9 },
          { from: 2, to: 8 },
          { from: 3, to: 7 },
          { from: 4, to: 6 },
          { from: 5, to: 5 },
          { from: 6, to: 4 },
          { from: 7, to: 3 },
          { from: 8, to: 2 },
          { from: 9, to: 1 },
        ],
      },
      discrimination: {
        steps: [
          {
            question: "هل مجموع خطوتي العشرات يصل إلى 10 أو أكثر؟ | Does the sum of tens steps reach 10 or more?",
            type: "yes-no",
            actual: "المجموع ≥ 10 | Sum ≥ 10",
            answer: "نعم → نلجأ لأصدقاء 10 | Yes → Use Friends of 10",
            hint: "اطرح المتمّم وقفز بـ 1 للمئات | Subtract complement and add 1 to Hundreds",
          },
          {
            question: "هل الخرزات المفعّلة تكفي لطرح المتمّم مباشرة؟ | Are active beads sufficient to subtract complement directly?",
            type: "yes-no",
            actual: "الخرزات المفعّلة ≥ المتمّم | Active beads ≥ Complement",
            answer: "نعم → اطرح المتمّم بالسبابة ⬇️ وأضف 1 للمئات بالإبهام 👍⬆️ | Yes → Subtract complement with index ⬇️ & add 1 to hundreds with thumb 👍⬆️",
            hint: "+n = −k + 10",
          },
        ],
        decision: "أصدقاء 10 — اطرح المتمّم بالسبابة واقفز 1 لعمود المئات بالإبهام! | Friends of 10 — Subtract complement with index & leap 1 bead to hundreds with thumb!",
      },
      watchPhase: {
        examples: [
          {
            id: "S06-m3-E1",
            question: "19 × 11",
            discrimination: "المئات: 1×1=1 · العشرات: 9×1=9 · إضافة العشرات: 1×1=1 (9+1=10) · الآحاد: 9×1=9 | Friends of 10 (+1)",
            rule: "+1 = −9 + 10 (صديق 1 هو 9) | +1 = −9 + 10 (1's friend is 9)",
            fingerMovement: "ضع 1 للمئات بالإبهام 👍⬆️ · ضع 9 للعشرات بكماشة مغلقة 🗜️ · اطرح 9 من العشرات بكماشة مفتوحة وأضف 1 للمئات بالإبهام 👍⬆️ · ضع 9 للآحاد بكماشة مغلقة 🗜️ | Set 1 in hundreds with thumb 👍⬆️ · Set 9 in tens with closed pinch 🗜️ · Subtract 9 from tens with open pinch & add 1 to hundreds with thumb 👍⬆️ · Set 9 in units with closed pinch 🗜️",
            steps: [
              "المئات: 1 × 1 = 1 → ارفع 1 بالمئات بالإبهام 👍⬆️ | Hundreds: 1 × 1 = 1 → Lift 1 in Hundreds with thumb 👍⬆️",
              "العشرات: 9 × 1 = 9 → ضع 9 بالعشرات بكماشة مغلقة 🗜️ | Tens: 9 × 1 = 9 → Set 9 in Tens with closed pinch 🗜️",
              "العشرات: 1 × 1 = 1 → إضافة 1 للعشرات بأصدقاء 10 (+1 = −9 + 10): اطرح 9 من العشرات بكماشة مفتوحة، وأضف 1 للمئات بالإبهام 👍⬆️ → العشرات = 0، المئات = 2 | Tens: 1 × 1 = 1 → Add 1 to Tens (+1 = −9 + 10): Subtract 9 from tens with open pinch, and add 1 to hundreds with thumb 👍⬆️ → Tens = 0, Hundreds = 2",
              "الآحاد: 9 × 1 = 9 → ضع 9 بالآحاد بكماشة مغلقة 🗜️ | Units: 9 × 1 = 9 → Set 9 in Units with closed pinch 🗜️",
              "الناتج النهائي: 2 مئات + 0 عشرات + 9 آحاد = 209 | Final Result: 2 hundreds + 0 tens + 9 units = 209",
            ],
            result: 209,
            beadVisual: "2 مئات + 0 عشرات + 9 آحاد = 209 | 2 Hundreds + 0 Tens + 9 Units = 209",
          },
          {
            id: "S06-m3-E2",
            question: "17 × 12",
            discrimination: "المئات: 1×1=1 · العشرات: 7×1=7 · إضافة العشرات: 1×2=2 (7+2=9) · الآحاد: 7×2=14 (4 للآحاد، +1 للعشرات: 9+1=10) | Friends of 10 (+1)",
            rule: "+1 = −9 + 10 (صديق 1 هو 9) | +1 = −9 + 10 (1's friend is 9)",
            fingerMovement: "ضع 1 للمئات بالإبهام 👍⬆️ · ضع 7 للعشرات بكماشة مغلقة 🗜️ · أضف 2 للعشرات بالإبهام 👍⬆️ (العشرات = 9) · ضع 4 بالآحاد بالإبهام 👍⬆️، واطرح 9 بالعشرات بكماشة مفتوحة وأضف 1 للمئات بالإبهام 👍⬆️ | Set 1 in hundreds with thumb 👍⬆️ · Set 7 in tens with closed pinch 🗜️ · Add 2 to tens with thumb 👍⬆️ (Tens = 9) · Set 4 in units with thumb 👍⬆️, subtract 9 from tens with open pinch & add 1 to hundreds with thumb 👍⬆️",
            steps: [
              "المئات: 1 × 1 = 1 → ارفع 1 بالمئات بالإبهام 👍⬆️ | Hundreds: 1 × 1 = 1 → Lift 1 in Hundreds with thumb 👍⬆️",
              "العشرات: 7 × 1 = 7 → ضع 7 بالعشرات بكماشة مغلقة 🗜️ | Tens: 7 × 1 = 7 → Set 7 in Tens with closed pinch 🗜️",
              "العشرات: 1 × 2 = 2 → 7+2=9 مباشر بالعشرات بالإبهام 👍⬆️ | Tens: 1 × 2 = 2 → 7+2=9 direct in Tens with thumb 👍⬆️",
              "الآحاد: 7 × 2 = 14 → ضع 4 بالآحاد بالإبهام 👍⬆️، والمتبقي 1 للعشرات (9+1=10): اطرح 9 بكماشة مفتوحة، وأضف 1 للمئات بالإبهام 👍⬆️ → العشرات = 0، المئات = 2 | Units: 7 × 2 = 14 → Set 4 in units with thumb 👍⬆️, 1 to tens (9+1=10): Clear 9 with open pinch, add 1 to hundreds with thumb 👍⬆️ → Tens = 0, Hundreds = 2",
              "الناتج النهائي: 2 مئات + 0 عشرات + 4 آحاد = 204 | Final Result: 2 hundreds + 0 tens + 4 units = 204",
            ],
            result: 204,
            beadVisual: "2 مئات + 0 عشرات + 4 آحاد = 204 | 2 Hundreds + 0 Tens + 4 Units = 204",
          },
          {
            id: "S06-m3-E3",
            question: "16 × 13",
            discrimination: "المئات: 1×1=1 · العشرات: 6×1=6 · إضافة العشرات: 1×3=3 (6+3=9) · الآحاد: 6×3=18 (8 للآحاد، +1 للعشرات: 9+1=10) | Friends of 10 (+1)",
            rule: "+1 = −9 + 10 (صديق 1 هو 9) | +1 = −9 + 10 (1's friend is 9)",
            fingerMovement: "ضع 1 للمئات بالإبهام 👍⬆️ · ضع 6 للعشرات بكماشة مغلقة 🗜️ · أضf 3 للعشرات بالإبهام 👍⬆️ · ضع 8 بالآحاد بكماشة مغلقة 🗜️، واطرح 9 بالعشرات بكماشة مفتوحة وأضف 1 للمئات بالإبهام 👍⬆️ | Set 1 in hundreds with thumb 👍⬆️ · Set 6 in tens with closed pinch 🗜️ · Add 3 to tens with thumb 👍⬆️ · Set 8 in units with closed pinch 🗜️, subtract 9 from tens with open pinch & add 1 to hundreds with thumb 👍⬆️",
            steps: [
              "المئات: 1 × 1 = 1 → ارفع 1 بالمئات بالإبهام 👍⬆️ | Hundreds: 1 × 1 = 1 → Lift 1 in Hundreds with thumb 👍⬆️",
              "العشرات: 6 × 1 = 6 → ضع 6 بالعشرات بكماشة مغلقة 🗜️ | Tens: 6 × 1 = 6 → Set 6 in Tens with closed pinch 🗜️",
              "العشرات: 1 × 3 = 3 → 6+3=9 مباشر بالعشرات بالإبهام 👍⬆️ | Tens: 1 × 3 = 3 → 6+3=9 direct in Tens with thumb 👍⬆️",
              "الآحاد: 6 × 3 = 18 → ضع 8 بالآحاد بكماشة مغلقة 🗜️، والمتبقي 1 للعشرات (9+1=10): اطرح 9 بكماشة مفتوحة، وأضف 1 للمئات بالإبهام 👍⬆️ → العشرات = 0، المئات = 2 | Units: 6 × 3 = 18 → Set 8 in units with closed pinch 🗜️, +1 to tens (9+1=10): Clear 9 with open pinch, add 1 to hundreds with thumb 👍⬆️ → Tens = 0, Hundreds = 2",
              "الناتج النهائي: 2 مئات + 0 عشرات + 8 آحاد = 208 | Final Result: 2 hundreds + 0 tens + 8 units = 208",
            ],
            result: 208,
            beadVisual: "2 مئات + 0 عشرات + 8 آحاد = 208 | 2 Hundreds + 0 Tens + 8 Units = 208",
          },
          {
            id: "S06-m3-E4",
            question: "18 × 12",
            discrimination: "المئات: 1×1=1 · العشرات: 8×1=8 · إضافة العشرات: 1×2=2 (8+2=10 بأصدقاء 10) · الآحاد: 8×2=16 | Friends of 10 (+2)",
            rule: "+2 = −8 + 10 (صديق 2 هو 8) | +2 = −8 + 10 (2's friend is 8)",
            fingerMovement: "ضع 1 للمئات بالإبهام 👍⬆️ · ضع 8 للعشرات بكماشة مغلقة 🗜️ · اطرح 8 من العشرات بكماشة مفتوحة وأضف 1 للمئات بالإبهام 👍⬆️ · أضف 1 للعشرات بالإبهام 👍⬆️ وضاعف 6 بالآحاد بكماشة مغلقة 🗜️ | Set 1 in hundreds with thumb 👍⬆️ · Set 8 in tens with closed pinch 🗜️ · Subtract 8 from tens with open pinch & add 1 to hundreds with thumb 👍⬆️ · Add 1 to tens with thumb 👍⬆️ & set 6 in units with closed pinch 🗜️",
            steps: [
              "المئات: 1 × 1 = 1 → ارفع 1 بالمئات بالإبهام 👍⬆️ | Hundreds: 1 × 1 = 1 → Lift 1 in Hundreds with thumb 👍⬆️",
              "العشرات: 8 × 1 = 8 → ضع 8 بالعشرات بكماشة مغلقة 🗜️ | Tens: 8 × 1 = 8 → Set 8 in Tens with closed pinch 🗜️",
              "العشرات: 1 × 2 = 2 → إضافة 2 للعشرات بأصدقاء 10 (+2 = −8 + 10): اطرح 8 من العشرات بكماشة مفتوحة، وأضف 1 للمئات بالإبهام 👍⬆️ → العشرات = 0، المئات = 2 | Tens: 1 × 2 = 2 → Add 2 to Tens (+2 = −8 + 10): Subtract 8 from tens with open pinch, and add 1 to hundreds with thumb 👍⬆️ → Tens = 0, Hundreds = 2",
              "الآحاد: 8 × 2 = 16 → أضف 1 للعشرات بالإبهام 👍⬆️ (0+1=1)، وضارب 6 بالآحاد بكماشة مغلقة 🗜️ | Units: 8 × 2 = 16 → Add 1 to Tens with thumb 👍⬆️ (0+1=1), set 6 in units with closed pinch 🗜️",
              "الناتج النهائي: 2 مئات + 1 عشرات + 6 آحاد = 216 | Final Result: 2 hundreds + 1 ten + 6 units = 216",
            ],
            result: 216,
            beadVisual: "2 مئات + 1 عشرات + 6 آحاد = 216 | 2 Hundreds + 1 Ten + 6 Units = 216",
          },
          {
            id: "S06-m3-E5",
            question: "29 × 11",
            discrimination: "المئات: 2×1=2 · العشرات: 9×1=9 · إضافة العشرات: 2×1=2 (9+2=11 بأصدقاء 10) · الآحاد: 9×1=9 | Friends of 10 (+2)",
            rule: "+2 = −8 + 10 (صديق 2 هو 8) | +2 = −8 + 10 (2's friend is 8)",
            fingerMovement: "ضع 2 للمئات بالإبهام 👍⬆️ · ضع 9 للعشرات بكماشة مغلقة 🗜️ · اطرح 8 من العشرات بكماشة مفتوحة وأضف 1 للمئات بالإبهام 👍⬆️ · ضع 9 للآحاد بكماشة مغلقة 🗜️ | Set 2 in hundreds with thumb 👍⬆️ · Set 9 in tens with closed pinch 🗜️ · Subtract 8 from tens with open pinch & add 1 to hundreds with thumb 👍⬆️ · Set 9 in units with closed pinch 🗜️",
            steps: [
              "المئات: 2 × 1 = 2 → ارفع 2 بالمئات بالإبهام 👍⬆️ | Hundreds: 2 × 1 = 2 → Lift 2 in Hundreds with thumb 👍⬆️",
              "العشرات: 9 × 1 = 9 → ضع 9 بالعشرات بكماشة مغلقة 🗜️ | Tens: 9 × 1 = 9 → Set 9 in Tens with closed pinch 🗜️",
              "العشرات: 2 × 1 = 2 → إضافة 2 للعشرات بأصدقاء 10 (+2 = −8 + 10): اطرح 8 من العشرات بكماشة مفتوحة، وأضف 1 للمئات بالإبهام 👍⬆️ → العشرات = 1، المئات = 3 | Tens: 2 × 1 = 2 → Add 2 to Tens (+2 = −8 + 10): Subtract 8 from tens with open pinch, and add 1 to hundreds with thumb 👍⬆️ → Tens = 1, Hundreds = 3",
              "الآحاد: 9 × 1 = 9 → ضع 9 بالآحاد بكماشة مغلقة 🗜️ | Units: 9 × 1 = 9 → Set 9 in Units with closed pinch 🗜️",
              "الناتج النهائي: 3 مئات + 1 عشرات + 9 آحاد = 319 | Final Result: 3 hundreds + 1 ten + 9 units = 319",
            ],
            result: 319,
            beadVisual: "3 مئات + 1 عشرات + 9 آحاد = 319 | 3 Hundreds + 1 Ten + 9 Units = 319",
          },
        ],
      },
      tryPhase: {
        exercises: [
          {
            id: "S06-m3-T1",
            question: "23 × 33",
            discrimination: "9+6=15 بأصدقاء 10 (+6 = −4 + 10) | +6 = −4 + 10",
            steps: [
              "المئات: 2 × 3 = 6 → ضع 6 بالمئات بكماشة مغلقة 🗜️ | Hundreds: 2 × 3 = 6 → Set 6 in Hundreds with closed pinch 🗜️",
              "العشرات: 3 × 3 = 9 → ضع 9 بالعشرات بكماشة مغلقة 🗜️ | Tens: 3 × 3 = 9 → Set 9 in Tens with closed pinch 🗜️",
              "العشرات: 2 × 3 = 6 → إضافة 6 للعشرات (+6 = −4 + 10): اطرح 4 بالعشرات بالسبابة ⬇️ وأضف 1 للمئات بالإبهام 👍⬆️ | Tens: 2 × 3 = 6 → Add 6 to Tens (+6 = −4 + 10): Subtract 4 with index ⬇️ & add 1 to Hundreds with thumb 👍⬆️",
              "الآحاد: 3 × 3 = 9 → ضع 9 بالآحاد بكماشة مغلقة 🗜️ | Units: 3 × 3 = 9 → Set 9 in Units with closed pinch 🗜️",
              "الناتج النهائي: 759 | Final Result: 759",
            ],
            result: 759,
          },
          {
            {
  {
  id: "S06-m3-T2",
  question: "22 × 44",
  discrimination: "8+8=16 بأصدقاء 10 (+8 = −2 + 10) | +8 = −2 + 10",
  steps: [
    "المئات: 2 × 4 = 8 → ضع 8 بالمئات بكماشة مغلقة 🗜️ | Hundreds: 2 × 4 = 8 → Set 8 in Hundreds with closed pinch 🗜️",
    "العشرات: 2 × 4 = 8 → ضع 8 بالعشرات بكماشة مغلقة 🗜️ | Tens: 2 × 4 = 8 → Set 8 in Tens with closed pinch 🗜️",
    "العشرات: 2 × 4 = 8 → إضافة 8 للعشرات (+8 = −2 + 10): اطرح 2 بالعشرات بالسبابة ⬇️ (سحبة سبابة) وأضف 1 للمئات بالإبهام 👍⬆️ | Tens: 2 × 4 = 8 → Add 8 to Tens (+8 = −2 + 10): Subtract 2 with index ⬇️ (index pull) & add 1 to Hundreds with thumb 👍⬆️",
    "الآحاد: 2 × 4 = 8 → ضع 8 بالآحاد بكماشة مغلقة 🗜️ | Units: 2 × 4 = 8 → Set 8 in Units with closed pinch 🗜️",
    "الناتج النهائي: 968 | Final Result: 968",
  ],
  result: 968,
},
          {
            id: "S06-m3-T3",
            question: "13 × 31",
            discrimination: "9+1=10 بأصدقاء 10 (+1 = −9 + 10) | +1 = −9 + 10",
            steps: [
              "المئات: 1 × 3 = 3 → ارفع 3 بالمئات بالإبهام 👍⬆️ | Hundreds: 1 × 3 = 3 → Lift 3 in Hundreds with thumb 👍⬆️",
              "العشرات: 3 × 3 = 9 → ضع 9 بالعشرات بكماشة مغلقة 🗜️ | Tens: 3 × 3 = 9 → Set 9 in Tens with closed pinch 🗜️",
              "العشرات: 1 × 1 = 1 → إضافة 1 للعشرات (+1 = −9 + 10): اطرح 9 بكماشة مفتوحة وأضف 1 للمئات بالإبهام 👍⬆️ | Tens: 1 × 1 = 1 → Add 1 to Tens (+1 = −9 + 10): Subtract 9 with open pinch & add 1 to Hundreds with thumb 👍⬆️",
              "الآحاد: 3 × 1 = 3 → ارفع 3 بالآحاد بالإبهام 👍⬆️ | Units: 3 × 1 = 3 → Lift 3 in Units with thumb 👍⬆️",
              "الناتج النهائي: 403 | Final Result: 403",
            ],
            result: 403,
          },
          {
            id: "S06-m3-T4",
            question: "13 × 32",
            discrimination: "9+2=11 بأصدقاء 10 (+2 = −8 + 10) | +2 = −8 + 10",
            steps: [
              "المئات: 1 × 3 = 3 → ارفع 3 بالمئات بالإبهام 👍⬆️ | Hundreds: 1 × 3 = 3 → Lift 3 in Hundreds with thumb 👍⬆️",
              "العشرات: 3 × 3 = 9 → ضع 9 بالعشرات بكماشة مغلقة 🗜️ | Tens: 3 × 3 = 9 → Set 9 in Tens with closed pinch 🗜️",
              "العشرات: 1 × 2 = 2 → إضافة 2 للعشرات (+2 = −8 + 10): اطرح 8 بكماشة مفتوحة وأضف 1 للمئات بالإبهام 👍⬆️ | Tens: 1 × 2 = 2 → Add 2 to Tens (+2 = −8 + 10): Subtract 8 with open pinch & add 1 to Hundreds with thumb 👍⬆️",
              "الآحاد: 3 × 2 = 6 → ضع 6 بالآحاد بكماشة مغلقة 🗜️ | Units: 3 × 2 = 6 → Set 6 in Units with closed pinch 🗜️",
              "الناتج النهائي: 416 | Final Result: 416",
            ],
            result: 416,
          },
          {
            id: "S06-m3-T5",
            question: "23 × 31",
            discrimination: "9+2=11 بأصدقاء 10 (+2 = −8 + 10) | +2 = −8 + 10",
            steps: [
              "المئات: 2 × 3 = 6 → ضع 6 بالمئات بكماشة مغلقة 🗜️ | Hundreds: 2 × 3 = 6 → Set 6 in Hundreds with closed pinch 🗜️",
              "العشرات: 3 × 3 = 9 → ضع 9 بالعشرات بكماشة مغلقة 🗜️ | Tens: 3 × 3 = 9 → Set 9 in Tens with closed pinch 🗜️",
              "العشرات: 2 × 1 = 2 → إضافة 2 للعشرات (+2 = −8 + 10): اطرح 8 بكماشة مفتوحة وأضف 1 للمئات بالإبهام 👍⬆️ | Tens: 2 × 1 = 2 → Add 2 to Tens (+2 = −8 + 10): Subtract 8 with open pinch & add 1 to Hundreds with thumb 👍⬆️",
              "الآحاد: 3 × 1 = 3 → ارفع 3 بالآحاد بالإبهام 👍⬆️ | Units: 3 × 1 = 3 → Lift 3 in Units with thumb 👍⬆️",
              "الناتج النهائي: 713 | Final Result: 713",
            ],
            result: 713,
          },
        ],
      },
    },

    // ═══════════════════════════════════════════════════════════
    // m4 — الضرب المركّب (2 × 2)
    // ═══════════════════════════════════════════════════════════
    {
      id: "m4",
      ruleCategory: "combined",
      title: "الضرب المركّب | Compound Multiplication",
      titleEn: "Compound Multiplication",
      emoji: "🎯",
      miniStory: {
        title: "التحالف المزدوج الخارق | The Super Double Alliance",
        emoji: "👑",
        story: "التحدي الكبير! 23 بـ 23! العمود مليان والسفليات ما بتكفي؟ بتتحالف تيتا 5 مع العملاق 10: بنرفع رفعة مزدوجة ⬆️⬆️ بنشيل 5 بالسبابة، بنرفع 1 بالإبهام، وبنطير للمئات.. الناتج الخارق: 529! | The big challenge! 23 × 23! Column is full & lower beads aren't enough? Grandma 5 allies with Giant 10: Double Lift ⬆️⬆️ clearing 5 with index, lifting 1 with thumb, & leaping to hundreds.. Super result: 529!",
        storyAudioText: "ثلاثة وعشرون في ثلاثة وعشرين.. العشرات في العشرات: اثنان في اثنين يساوي أربعة في المئات.. الآحاد في العشرات: ثلاثة في اثنين يساوي ستة في العشرات.. العشرات في الآحاد: اثنان في ثلاثة يساوي ستة.. ستة زائد ستة يساوي اثني عشر.. التحالف المزدوج: أزل خمسة، أضف واحداً، وأضف خرزة في المئات.. الآحاد في الآحاد: ثلاثة في ثلاثة يساوي تسعة.. الناتج: خمسمائة وتسعة وعشرون! | 23 times 23.. Tens by tens: 2 times 2 equals 4 in hundreds.. Units by tens: 3 times 2 equals 6 in tens.. Tens by units: 2 times 3 equals 6.. 6 plus 6 equals 12.. Double Alliance: remove 5, add 1, and add 1 bead in hundreds.. Units by units: 3 times 3 equals 9.. Result is 529!",
        storyAudioId: 28,
      },
      rule: {
        description: "التحالف المزدوج 👑: عندما تكون 5 مفعّلة والسفليات لا تكفي لطرح المتمّم، نفّذ رفع مزدوج ⬆️⬆️ على العشرات (إلغاء 5 بالسبابة ⬆️ وإضافة المكمل بالإبهام ⬆️)، ثم أضف 1 لعمود المئات بالإبهام 👍⬆️! | Double Alliance 👑: When 5 is active and lower beads are insufficient to subtract complement, perform Double Lift ⬆️⬆️ on tens (cancel 5 with index ⬆️ & add remainder with thumb ⬆️), then add 1 to hundreds with thumb 👍⬆️!",
        cases: [
          { from: 5, formula: "+5 = −5 + 10 (إلغاء 5 بالسبابة ⬆️ والقفز بـ 10 للمئات بالإبهام ⬆️) | +5 = −5 + 10 (Cancel 5 with index ⬆️ and leap 10 to Hundreds with thumb ⬆️)" },
          { from: 6, formula: "+6 = −5 + 1 + 10 (رفع مزدوج ⬆️⬆️: إلغاء 5 + إضافة 1، ثم +10 للمئات) | +6 = −5 + 1 + 10 (Double Lift ⬆️⬆️: cancel 5 + add 1, then +10 to Hundreds)" },
          { from: 7, formula: "+7 = −5 + 2 + 10 (رفع مزدوج ⬆️⬆️: إلغاء 5 + إضافة 2، ثم +10 للمئات) | +7 = −5 + 2 + 10 (Double Lift ⬆️⬆️: cancel 5 + add 2, then +10 to Hundreds)" },
          { from: 8, formula: "+8 = −5 + 3 + 10 (رفع مزدوج ⬆️⬆️: إلغاء 5 + إضافة 3، ثم +10 للمئات) | +8 = −5 + 3 + 10 (Double Lift ⬆️⬆️: cancel 5 + add 3, then +10 to Hundreds)" },
          { from: 9, formula: "+9 = −5 + 4 + 10 (رفع مزدوج ⬆️⬆️: إلغاء 5 + إضافة 4، ثم +10 للمئات) | +9 = −5 + 4 + 10 (Double Lift ⬆️⬆️: cancel 5 + add 4, then +10 to Hundreds)" },
        ],
      },
      condition: {
        formula: "مجموع العشرات ≥ 10 · 5 مفعّلة · السفليات < المتمّم | Tens sum ≥ 10 · 5 active · Lower beads < Complement",
        explanation: "الجدة 5 والعملاق 10 يتعاونان معاً لفك ازدحام العمود! | Grandma 5 and Giant 10 ally together to clear column traffic!",
      },
      discrimination: {
        steps: [
          {
            question: "هل نحتاج ترحيل للمئات (المجموع ≥ 10)؟ | Do we need to carry to Hundreds (Sum ≥ 10)?",
            type: "yes-no",
            actual: "المجموع ≥ 10 | Sum ≥ 10",
            answer: "نعم → نحتاج ترحيل للمئات | Yes → Need carrying to Hundreds",
            hint: "المجموع يتجاوز سعة العمود الحالية | Sum exceeds current column capacity",
          },
          {
            question: "هل الخرزات السفلية < المتمّم المطلوب؟ | Are lower beads < required complement?",
            type: "yes-no",
            actual: "السفليات < المتمّم | Lower beads < Complement",
            answer: "نعم → استخدم التحالف المزدوج: رفع مزدوج ⬆️⬆️ +10 للمئات | Yes → Use Dual Alliance: Double Lift ⬆️⬆️ +10 to Hundreds",
            hint: "إلغاء 5 بالسبابة ⬆️ + إضافة المكمّل بالإبهام ⬆️ + إضافة 1 للمئات ⬆️",
          },
        ],
        decision: "ضرب مركّب! رفع مزدوج ⬆️⬆️ على العشرات وإضافة 1 لعمود المئات بالإبهام ⬆️! | Compound Multiplication! Double Lift ⬆️⬆️ on tens & add 1 to Hundreds with thumb ⬆️!",
      },
      watchPhase: {
        examples: [
          {
            id: "S06-m4-E1",
            question: "23 × 23",
            discrimination: "المئات: 2×2=4 · العشرات: 3×2=6 · إضافة العشرات: 2×3=6 (6+6=12: تحالف مركّب −5+1+10) · الآحاد: 3×3=9 | Combined Alliance (+6)",
            rule: "+6 = −5 + 1 + 10 | Compound: +6 = −5 + 1 + 10",
            fingerMovement: "ضع 4 للمئات بالإبهام 👍⬆️ · ضع 6 للعشرات بكماشة مغلقة 🗜️ · رفع مزدوج ⬆️⬆️ على العشرات (سبابة ترفع 5 ⬆️ + إبهام يرفع 1 ⬆️) + أضف 1 للمئات بالإبهام 👍⬆️ · ضع 9 للآحاد بكماشة مغلقة 🗜️ | Set 4 in hundreds with thumb 👍⬆️ · Set 6 in tens with closed pinch 🗜️ · Double Lift ⬆️⬆️ on tens (index lifts 5 ⬆️ + thumb lifts 1 ⬆️) + Add 1 to hundreds with thumb 👍⬆️ · Set 9 in units with closed pinch 🗜️",
            steps: [
              "المئات: 2 × 2 = 4 → ارفع 4 بالمئات بالإبهام 👍⬆️ | Hundreds: 2 × 2 = 4 → Lift 4 in Hundreds with thumb 👍⬆️",
              "العشرات: 3 × 2 = 6 → ضع 6 بالعشرات بكماشة مغلقة 🗜️ | Tens: 3 × 2 = 6 → Set 6 in Tens with closed pinch 🗜️",
              "العشرات: 2 × 3 = 6 → إضافة 6 للعشرات (6+6=12): «رفع مزدوج» ⬆️⬆️ على العشرات (إلغاء 5 بالسبابة ⬆️ وإضافة 1 بالإبهام ⬆️) ثم إضافة 1 للمئات بالإبهام 👍⬆️ → العشرات = 2، المئات = 5 | Tens: 2 × 3 = 6 → Add 6 to Tens (6+6=12): «Double Lift» ⬆️⬆️ on tens (cancel 5 with index ⬆️ & add 1 with thumb ⬆️) then add 1 to hundreds with thumb 👍⬆️ → Tens = 2, Hundreds = 5",
              "الآحاد: 3 × 3 = 9 → ضع 9 بالآحاد بكماشة مغلقة 🗜️ | Units: 3 × 3 = 9 → Set 9 in Units with closed pinch 🗜️",
              "الناتج النهائي: 5 مئات + 2 عشرات + 9 آحاد = 529 | Final Result: 5 hundreds + 2 tens + 9 units = 529",
            ],
            result: 529,
            beadVisual: "5 مئات + 2 عشرات + 9 آحاد = 529 | 5 Hundreds + 2 Tens + 9 Units = 529",
          },
          {
            id: "S06-m4-E2",
            question: "24 × 23",
            discrimination: "المئات: 2×2=4 · العشرات: 4×2=8 · إضافة العشرات: 2×3=6 (8+6=14: تحالف مركّب) · الآحاد: 4×3=12 (2 للآحاد و+1 للعشرات) | Combined Alliance (+6)",
            rule: "+6 = −5 + 1 + 10 | Compound: +6 = −5 + 1 + 10",
            fingerMovement: "ضع 4 للمئات بالإبهام 👍⬆️ · ضع 8 للعشرات بكماشة مغلقة 🗜️ · رفع مزدوج ⬆️⬆️ على العشرات + أضف 1 للمئات بالإبهام 👍⬆️ · ضع 2 بالآحاد بالإبهام 👍⬆️، أضف 1 للعشرات بنزول مزدوج ⬇️⬇️ | Set 4 in hundreds with thumb 👍⬆️ · Set 8 in tens with closed pinch 🗜️ · Double Lift ⬆️⬆️ on tens + Add 1 to hundreds with thumb 👍⬆️ · Set 2 in units with thumb 👍⬆️, add 1 to tens with Double Drop ⬇️⬇️",
            steps: [
              "المئات: 2 × 2 = 4 → ارفع 4 بالمئات بالإبهام 👍⬆️ | Hundreds: 2 × 2 = 4 → Lift 4 in Hundreds with thumb 👍⬆️",
              "العشرات: 4 × 2 = 8 → ضع 8 بالعشرات بكماشة مغلقة 🗜️ | Tens: 4 × 2 = 8 → Set 8 in Tens with closed pinch 🗜️",
              "العشرات: 2 × 3 = 6 → إضافة 6 للعشرات (8+6=14): «رفع مزدوج» ⬆️⬆️ على العشرات (إلغاء 5 بالسبابة ⬆️ وإضافة 1 بالإبهام ⬆️) ثم إضافة 1 للمئات بالإبهام 👍⬆️ → العشرات = 4، المئات = 5 | Tens: 2 × 3 = 6 → Add 6 to Tens (8+6=14): «Double Lift» ⬆️⬆️ on tens (cancel 5 with index ⬆️ & add 1 with thumb ⬆️) then add 1 to hundreds with thumb 👍⬆️ → Tens = 4, Hundreds = 5",
              "الآحاد: 4 × 3 = 12 → ضع 2 بالآحاد بالإبهام 👍⬆️، و+1 للعشرات (4+1=5) بأصدقاء 5: بنزول مزدوج ⬇️⬇️ → العشرات = 5 | Units: 4 × 3 = 12 → Set 2 in units with thumb 👍⬆️, +1 to tens (4+1=5) via Friends of 5: Double Drop ⬇️⬇️ → Tens = 5",
              "الناتج النهائي: 5 مئات + 5 عشرات + 2 آحاد = 552 | Final Result: 5 hundreds + 5 tens + 2 units = 552",
            ],
            result: 552,
            beadVisual: "5 مئات + 5 عشرات + 2 آحاد = 552 | 5 Hundreds + 5 Tens + 2 Units = 552",
          },
          {
            id: "S06-m4-E3",
            question: "33 × 22",
            discrimination: "المئات: 3×2=6 · العشرات: 3×2=6 · إضافة العشرات: 3×2=6 (6+6=12: تحالف مركّب −5+1+10) · الآحاد: 3×2=6 | Combined Alliance (+6)",
            rule: "+6 = −5 + 1 + 10 | Compound: +6 = −5 + 1 + 10",
            fingerMovement: "ضع 6 للمئات بكماشة مغلقة 🗜️ · ضع 6 للعشرات بكماشة مغلقة 🗜️ · رفع مزدوج ⬆️⬆️ على العشرات + أضف 1 للمئات بالإبهام 👍⬆️ · ضع 6 للآحاد بكماشة مغلقة 🗜️ | Set 6 in hundreds with closed pinch 🗜️ · Set 6 in tens with closed pinch 🗜️ · Double Lift ⬆️⬆️ on tens + Add 1 to hundreds with thumb 👍⬆️ · Set 6 in units with closed pinch 🗜️",
            steps: [
              "المئات: 3 × 2 = 6 → ضع 6 بالمئات بكماشة مغلقة 🗜️ | Hundreds: 3 × 2 = 6 → Set 6 in Hundreds with closed pinch 🗜️",
              "العشرات: 3 × 2 = 6 → ضع 6 بالعشرات بكماشة مغلقة 🗜️ | Tens: 3 × 2 = 6 → Set 6 in Tens with closed pinch 🗜️",
              "العشرات: 3 × 2 = 6 → إضافة 6 للعشرات (6+6=12): «رفع مزدوج» ⬆️⬆️ على العشرات (إلغاء 5 بالسبابة ⬆️ وإضافة 1 بالإبهام ⬆️) ثم إضافة 1 للمئات بالإبهام 👍⬆️ → العشرات = 2، المئات = 7 | Tens: 3 × 2 = 6 → Add 6 to Tens (6+6=12): «Double Lift» ⬆️⬆️ on tens (cancel 5 with index ⬆️ & add 1 with thumb ⬆️) then add 1 to hundreds with thumb 👍⬆️ → Tens = 2, Hundreds = 7",
              "الآحاد: 3 × 2 = 6 → ضع 6 بالآحاد بكماشة مغلقة 🗜️ | Units: 3 × 2 = 6 → Set 6 in Units with closed pinch 🗜️",
              "الناتج النهائي: 7 مئات + 2 عشرات + 6 آحاد = 726 | Final Result: 7 hundreds + 2 tens + 6 units = 726",
            ],
            result: 726,
            beadVisual: "7 مئات + 2 عشرات + 6 آحاد = 726 | 7 Hundreds + 2 Tens + 6 Units = 726",
          },
          {
            id: "S06-m4-E4",
            question: "23 × 24",
            discrimination: "المئات: 2×2=4 · العشرات: 3×2=6 · إضافة العشرات: 2×4=8 (6+8=14: تحالف مركّب −5+3+10) · الآحاد: 3×4=12 (2 للآحاد و+1 للعشرات) | Combined Alliance (+8)",
            rule: "+8 = −5 + 3 + 10 | Compound: +8 = −5 + 3 + 10",
            fingerMovement: "ضع 4 للمئات بالإبهام 👍⬆️ · ضع 6 للعشرات بكماشة مغلقة 🗜️ · رفع مزدوج ⬆️⬆️ على العشرات (سبابة ترفع 5 ⬆️ + إبهام يرفع 3 ⬆️) + أضف 1 للمئات بالإبهام 👍⬆️ · ضع 2 بالآحاد بالإبهام 👍⬆️، أضف 1 للعشرات بنزول مزدوج ⬇️⬇️ | Set 4 in hundreds with thumb 👍⬆️ · Set 6 in tens with closed pinch 🗜️ · Double Lift ⬆️⬆️ on tens (index lifts 5 ⬆️ + thumb lifts 3 ⬆️) + Add 1 to hundreds with thumb 👍⬆️ · Set 2 in units with thumb 👍⬆️, add 1 to tens with Double Drop ⬇️⬇️",
            steps: [
              "المئات: 2 × 2 = 4 → ارفع 4 بالمئات بالإبهام 👍⬆️ | Hundreds: 2 × 2 = 4 → Lift 4 in Hundreds with thumb 👍⬆️",
              "العشرات: 3 × 2 = 6 → ضع 6 بالعشرات بكماشة مغلقة 🗜️ | Tens: 3 × 2 = 6 → Set 6 in Tens with closed pinch 🗜️",
              "العشرات: 2 × 4 = 8 → إضافة 8 للعشرات (6+8=14): «رفع مزدوج» ⬆️⬆️ على العشرات (إلغاء 5 بالسبابة ⬆️ وإضافة 3 بالإبهام ⬆️) ثم إضافة 1 للمئات بالإبهام 👍⬆️ → العشرات = 4، المئات = 5 | Tens: 2 × 4 = 8 → Add 8 to Tens (6+8=14): «Double Lift» ⬆️⬆️ on tens (cancel 5 with index ⬆️ & add 3 with thumb ⬆️) then add 1 to hundreds with thumb 👍⬆️ → Tens = 4, Hundreds = 5",
              "الآحاد: 3 × 4 = 12 → ضع 2 بالآحاد بالإبهام 👍⬆️، و+1 للعشرات (4+1=5) بأصدقاء 5: بنزول مزدوج ⬇️⬇️ → العشرات = 5 | Units: 3 × 4 = 12 → Set 2 in units with thumb 👍⬆️, +1 to tens (4+1=5) via Friends of 5: Double Drop ⬇️⬇️ → Tens = 5",
              "الناتج النهائي: 5 مئات + 5 عشرات + 2 آحاد = 552 | Final Result: 5 hundreds + 5 tens + 2 units = 552",
            ],
            result: 552,
            beadVisual: "5 مئات + 5 عشرات + 2 آحاد = 552 | 5 Hundreds + 5 Tens + 2 Units = 552",
          },
          {
            id: "S06-m4-E5",
            question: "34 × 22",
            discrimination: "المئات: 3×2=6 · العشرات: 4×2=8 · إضافة العشرات: 3×2=6 (8+6=14: تحالف مركّب −5+1+10) · الآحاد: 4×2=8 | Combined Alliance (+6)",
            rule: "+6 = −5 + 1 + 10 | Compound: +6 = −5 + 1 + 10",
            fingerMovement: "ضع 6 للمئات بكماشة مغلقة 🗜️ · ضع 8 للعشرات بكماشة مغلقة 🗜️ · رفع مزدوج ⬆️⬆️ على العشرات + أضف 1 للمئات بالإبهام 👍⬆️ · ضع 8 للآحاد بكماشة مغلقة 🗜️ | Set 6 in hundreds with closed pinch 🗜️ · Set 8 in tens with closed pinch 🗜️ · Double Lift ⬆️⬆️ on tens + Add 1 to hundreds with thumb 👍⬆️ · Set 8 in units with closed pinch 🗜️",
            steps: [
              "المئات: 3 × 2 = 6 → ضع 6 بالمئات بكماشة مغلقة 🗜️ | Hundreds: 3 × 2 = 6 → Set 6 in Hundreds with closed pinch 🗜️",
              "العشرات: 4 × 2 = 8 → ضع 8 بالعشرات بكماشة مغلقة 🗜️ | Tens: 4 × 2 = 8 → Set 8 in Tens with closed pinch 🗜️",
              "العشرات: 3 × 2 = 6 → إضافة 6 للعشرات (8+6=14): «رفع مزدوج» ⬆️⬆️ على العشرات (إلغاء 5 بالسبابة ⬆️ وإضافة 1 بالإبهام ⬆️) ثم إضافة 1 للمئات بالإبهام 👍⬆️ → العشرات = 4، المئات = 7 | Tens: 3 × 2 = 6 → Add 6 to Tens (8+6=14): «Double Lift» ⬆️⬆️ on tens (cancel 5 with index ⬆️ & add 1 with thumb ⬆️) then add 1 to hundreds with thumb 👍⬆️ → Tens = 4, Hundreds = 7",
              "الآحاد: 4 × 2 = 8 → ضع 8 بالآحاد بكماشة مغلقة 🗜️ | Units: 4 × 2 = 8 → Set 8 in Units with closed pinch 🗜️",
              "الناتج النهائي: 7 مئات + 4 عشرات + 8 آحاد = 748 | Final Result: 7 hundreds + 4 tens + 8 units = 748",
            ],
            result: 748,
            beadVisual: "7 مئات + 4 عشرات + 8 آحاد = 748 | 7 Hundreds + 4 Tens + 8 Units = 748",
          },
        ],
      },
      tryPhase: {
        exercises: [
          {
            id: "S06-m4-T1",
            question: "23 × 23",
            discrimination: "6+6=12 → تحالف (−5+1+10) | Compound: +6 = −5 + 1 + 10",
            steps: [
              "المئات: 2 × 2 = 4 → ارفع 4 بالمئات بالإبهام 👍⬆️ | Hundreds: 2 × 2 = 4 → Lift 4 in Hundreds with thumb 👍⬆️",
              "العشرات: 3 × 2 = 6 → ضع 6 بالعشرات بكماشة مغلقة 🗜️ | Tens: 3 × 2 = 6 → Set 6 in Tens with closed pinch 🗜️",
              "العشرات: 2 × 3 = 6 → إضافة 6 للعشرات (6+6=12) برفع مزدوج ⬆️⬆️ (إلغاء 5 بالسبابة ⬆️ وإضافة 1 بالإبهام ⬆️) وأضف 1 للمئات بالإبهام 👍⬆️ | Tens: 2 × 3 = 6 → Add 6 to Tens with Double Lift ⬆️⬆️ (cancel 5 & add 1) & add 1 to Hundreds with thumb 👍⬆️",
              "الآحاد: 3 × 3 = 9 → ضع 9 بالآحاد بكماشة مغلقة 🗜️ | Units: 3 × 3 = 9 → Set 9 in Units with closed pinch 🗜️",
              "الناتج النهائي: 529 | Final Result: 529",
            ],
            result: 529,
          },
          {
            id: "S06-m4-T2",
            question: "24 × 23",
            discrimination: "8+6=14 → تحالف (−5+1+10) | Compound: +6 = −5 + 1 + 10",
            steps: [
              "المئات: 2 × 2 = 4 → ارفع 4 بالمئات بالإبهام 👍⬆️ | Hundreds: 2 × 2 = 4 → Lift 4 in Hundreds with thumb 👍⬆️",
              "العشرات: 4 × 2 = 8 → ضع 8 بالعشرات بكماشة مغلقة 🗜️ | Tens: 4 × 2 = 8 → Set 8 in Tens with closed pinch 🗜️",
              "العشرات: 2 × 3 = 6 → إضافة 6 للعشرات (8+6=14) برفع مزدوج ⬆️⬆️ (إلغاء 5 بالسبابة ⬆️ وإضافة 1 بالإبهام ⬆️) وأضف 1 للمئات بالإبهام 👍⬆️ | Tens: 2 × 3 = 6 → Add 6 to Tens with Double Lift ⬆️⬆️ (cancel 5 & add 1) & add 1 to Hundreds with thumb 👍⬆️",
              "الآحاد: 4 × 3 = 12 → ضع 2 بالآحاد بالإبهام 👍⬆️، و+1 للعشرات بنزول مزدوج ⬇️⬇️ | Units: 4 × 3 = 12 → Set 2 in units with thumb 👍⬆️, +1 to Tens with Double Drop ⬇️⬇️",
              "الناتج النهائي: 552 | Final Result: 552",
            ],
            result: 552,
          },
          {
            id: "S06-m4-T3",
            question: "33 × 22",
            discrimination: "6+6=12 → تحالف (−5+1+10) | Compound: +6 = −5 + 1 + 10",
            steps: [
              "المئات: 3 × 2 = 6 → ضع 6 بالمئات بكماشة مغلقة 🗜️ | Hundreds: 3 × 2 = 6 → Set 6 in Hundreds with closed pinch 🗜️",
              "العشرات: 3 × 2 = 6 → ضع 6 بالعشرات بكماشة مغلقة 🗜️ | Tens: 3 × 2 = 6 → Set 6 in Tens with closed pinch 🗜️",
              "العشرات: 3 × 2 = 6 → إضافة 6 للعشرات (6+6=12) برفع مزدوج ⬆️⬆️ (إلغاء 5 بالسبابة ⬆️ وإضافة 1 بالإبهام ⬆️) وأضف 1 للمئات بالإبهام 👍⬆️ | Tens: 3 × 2 = 6 → Add 6 to Tens with Double Lift ⬆️⬆️ (cancel 5 & add 1) & add 1 to Hundreds with thumb 👍⬆️",
              "الآحاد: 3 × 2 = 6 → ضع 6 بالآحاد بكماشة مغلقة 🗜️ | Units: 3 × 2 = 6 → Set 6 in Units with closed pinch 🗜️",
              "الناتج النهائي: 726 | Final Result: 726",
            ],
            result: 726,
          },
          {
            id: "S06-m4-T4",
            question: "23 × 24",
            discrimination: "6+8=14 → تحالف (−5+3+10) | Compound: +8 = −5 + 3 + 10",
            steps: [
              "المئات: 2 × 2 = 4 → ارفع 4 بالمئات بالإبهام 👍⬆️ | Hundreds: 2 × 2 = 4 → Lift 4 in Hundreds with thumb 👍⬆️",
              "العشرات: 3 × 2 = 6 → ضع 6 بالعشرات بكماشة مغلقة 🗜️ | Tens: 3 × 2 = 6 → Set 6 in Tens with closed pinch 🗜️",
              "العشرات: 2 × 4 = 8 → إضافة 8 للعشرات (6+8=14) برفع مزدوج ⬆️⬆️ (إلغاء 5 بالسبابة ⬆️ وإضافة 3 بالإبهام ⬆️) وأضف 1 للمئات بالإبهام 👍⬆️ | Tens: 2 × 4 = 8 → Add 8 to Tens with Double Lift ⬆️⬆️ (cancel 5 & add 3) & add 1 to Hundreds with thumb 👍⬆️",
              "الآحاد: 3 × 4 = 12 → ضع 2 بالآحاد بالإبهام 👍⬆️، و+1 للعشرات بنزول مزدوج ⬇️⬇️ | Units: 3 × 4 = 12 → Set 2 in units with thumb 👍⬆️, +1 to Tens with Double Drop ⬇️⬇️",
              "الناتج النهائي: 552 | Final Result: 552",
            ],
            result: 552,
          },
          {
            id: "S06-m4-T5",
            question: "43 × 22",
            discrimination: "6+8=14 → تحالف (−5+3+10) | Compound: +8 = −5 + 3 + 10",
            steps: [
              "المئات: 4 × 2 = 8 → ضع 8 بالمئات بكماشة مغلقة 🗜️ | Hundreds: 4 × 2 = 8 → Set 8 in Hundreds with closed pinch 🗜️",
              "العشرات: 3 × 2 = 6 → ضع 6 بالعشرات بكماشة مغلقة 🗜️ | Tens: 3 × 2 = 6 → Set 6 in Tens with closed pinch 🗜️",
              "العشرات: 4 × 2 = 8 → إضافة 8 للعشرات (6+8=14) برفع مزدوج ⬆️⬆️ (إلغاء 5 بالسبابة ⬆️ وإضافة 3 بالإبهام ⬆️) وأضف 1 للمئات بالإبهام 👍⬆️ | Tens: 4 × 2 = 8 → Add 8 to Tens with Double Lift ⬆️⬆️ (cancel 5 & add 3) & add 1 to Hundreds with thumb 👍⬆️",
              "الآحاد: 3 × 2 = 6 → ضع 6 بالآحاد بكماشة مغلقة 🗜️ | Units: 3 × 2 = 6 → Set 6 in Units with closed pinch 🗜️",
              "الناتج النهائي: 946 | Final Result: 946",
            ],
            result: 946,
          },
        ],
      },
    },
  ],

  outro: {
    summary: "أتقنت الضرب (2×2) بأربع خطوات سحرية متتابعة من اليسار لليمين وفهمت كافة قواعد التمكّن والترحيل! | You mastered 2x2 multiplication with 4 left-to-right magic steps and all carry rules!",
    encouragement: "🎉 أنت بطل السوروبان الخارق ومستعد لأصعب التحديات! | 🎉 You are a Soroban Super Champion ready for the greatest challenges!",
    totalExamples: 20,
  },

  estimatedMinutes: 20,
  xpReward: 15,
};

export default S06_LESSON;
