// src/curriculum/lessons/L3/S07.ts
// ➗ درس S07: القسمة على رقم واحد — منهجية كوجيما
// القاعدة الذهبية: ابدأ من العشرات، ثم انتقل إلى الآحاد

import type { LessonNode } from "../types";

export const S07_LESSON: LessonNode = {
  id: "S07",
  skillId: "S07",
  levelId: "L3",
  order: 1,
  title: { ar: "القسمة على رقم واحد", en: "Division by One Digit" },
  emoji: "➗",
  tags: ["division", "kids", "L3", "left-to-right", "takashi-kojima"],

  modules: [
    // ═══════════════════════════════════════════════════════════
    // m1 — القسمة البسيطة
    // ═══════════════════════════════════════════════════════════
    {
      id: "m1",
      ruleCategory: "direct",
      title: "القسمة البسيطة | Direct Division",
      titleEn: "Direct Division",
      emoji: "✨",
      miniStory: {
        title: "مفتاح البداية - التوزيع المباشر | Beginning Key - Direct Distribution",
        emoji: "🧙",
        story: "في قلعة السوروبان، يوزع الحكيم معداد مفاتيح الكنز بالعدل. سألته البطلة بانة: كيف نوزع 84 حلوى على صديقين؟ قال: نقسم العشرات أولاً ثم الآحاد مباشرة دون استعارة! | In Soroban Castle, Master Abacus distributes treasure keys fairly. Hero Bana asked: How do we share 84 candies between 2 friends? He said: Divide tens first, then units directly without borrowing!",
        storyAudioText: "في قلعة السوروبان، يوزع الحكيم معداد الحلوى بالعدل. ثمانية قسمة اثنين تساوي أربعة في عشرات الخارج، وأربعة قسمة اثنين تساوي اثنين في آحاد الخارج. الناتج اثنان وأربعون. | In Soroban Castle, Master Abacus shares candies fairly. 8 divided by 2 equals 4 in tens quotient, 4 divided by 2 equals 2 in units quotient. Result is 42.",
        storyAudioId: null,
      },
      rule: {
        description: "القاعدة الذهبية 🧙: اقسم العشرات ضع الناتج، اطرح مباشرة بالإبهام والسبابة، ثم كرر مع الآحاد! | Golden Rule 🧙: Divide tens and place quotient, subtract directly using thumb and index, then repeat with units!",
      },
      condition: {
        formula: "قسمة تامة · طرح مباشر | Exact division · Direct subtraction",
        explanation: "جميع الخرزات متاحة للطرح المباشر ولا نحتاج لأصدقاء 5 أو 10! | All beads are available for direct subtraction; no friends of 5 or 10 needed!",
      },
      discrimination: {
        steps: [
          {
            question: "هل العشرات تكفي للقسمة على المقسوم عليه؟ | Is tens digit enough to divide?",
            type: "yes-no",
            answer: "نعم → ابدأ من العشرات | Yes → Start from tens",
            hint: "نبدأ دائماً من أقصى اليسار | Always start from the leftmost digit",
          },
          {
            question: "هل الخرزات المتاحة تكفي للطرح المباشر؟ | Are available beads enough for direct subtraction?",
            type: "comparison",
            actual: "الخرزات المتاحة ≥ ناتج الضرب | Available beads ≥ product",
            answer: "نعم → اطرح مباشرة | Yes → Subtract directly",
          },
        ],
        decision: "قسمة بسيطة — عشرات أولاً ثم آحاد! | Direct division — Tens first, then units!",
      },
      watchPhase: {
        examples: [
          {
            id: "S07-m1-E1",
            question: "84 ÷ 2",
            discrimination: "العشرات: 8÷2=4 · الآحاد: 4÷2=2 | Tens: 8÷2=4 · Units: 4÷2=2",
            rule: "اقسم من الكبار للصغار وطرح مباشر | Divide high to low with direct subtraction",
            fingerMovement: "ضع 4 في عشرات الخارج 👍 · اطرح 8 بكماشة 🗜️ · ضع 2 في آحاد الخارج 👍 · اطرح 4 بالسبابة ⬇️ | Set 4 in tens quotient 👍 · Subtract 8 with pinch 🗜️ · Set 2 in units quotient 👍 · Subtract 4 with index ⬇️",
            steps: [
              "العشرات ÷ 2: 8 ÷ 2 = 4 → ضع 4 في عشرات الخارج 👍 | Tens ÷ 2: 8 ÷ 2 = 4 → Set 4 in tens quotient 👍",
              "الخصم: 4 × 2 = 8 → اطرح 8 من العشرات بكماشة مغلقة 🗜️ | Subtraction: 4 × 2 = 8 → Subtract 8 from tens with closed pinch 🗜️",
              "الآحاد ÷ 2: 4 ÷ 2 = 2 → ضع 2 في آحاد الخارج 👍 | Units ÷ 2: 4 ÷ 2 = 2 → Set 2 in units quotient 👍",
              "الخصم: 2 × 2 = 4 → اطرح 4 من الآحاد بسحبة سبابة ⬇️ | Subtraction: 2 × 2 = 4 → Subtract 4 from units with index pull ⬇️",
              "الناتج النهائي: 42 | Final Result: 42",
            ],
            result: 42,
            beadVisual: "4 عشرات + 2 آحاد في الخارج | 4 tens + 2 units in quotient",
          },
          {
            id: "S07-m1-E2",
            question: "69 ÷ 3",
            discrimination: "العشرات: 6÷3=2 · الآحاد: 9÷3=3 | Tens: 6÷3=2 · Units: 9÷3=3",
            rule: "اقسم من الكبار للصغار وطرح مباشر | Divide high to low with direct subtraction",
            fingerMovement: "ضع 2 في عشرات الخارج 👍 · اطرح 6 بكماشة 🗜️ · ضع 3 في آحاد الخارج 👍 · اطرح 9 بكماشة 🗜️ | Set 2 in tens quotient 👍 · Subtract 6 with pinch 🗜️ · Set 3 in units quotient 👍 · Subtract 9 with pinch 🗜️",
            steps: [
              "العشرات ÷ 3: 6 ÷ 3 = 2 → ضع 2 في عشرات الخارج 👍 | Tens ÷ 3: 6 ÷ 3 = 2 → Set 2 in tens quotient 👍",
              "الخصم: 2 × 3 = 6 → اطرح 6 من العشرات بكماشة مغلقة 🗜️ | Subtraction: 2 × 3 = 6 → Subtract 6 from tens with closed pinch 🗜️",
              "الآحاد ÷ 3: 9 ÷ 3 = 3 → ضع 3 في آحاد الخارج 👍 | Units ÷ 3: 9 ÷ 3 = 3 → Set 3 in units quotient 👍",
              "الخصم: 3 × 3 = 9 → اطرح 9 من الآحاد بكماشة مغلقة 🗜️ | Subtraction: 3 × 3 = 9 → Subtract 9 from units with closed pinch 🗜️",
              "الناتج النهائي: 23 | Final Result: 23",
            ],
            result: 23,
            beadVisual: "2 عشرات + 3 آحاد في الخارج | 2 tens + 3 units in quotient",
          },
          {
            id: "S07-m1-E3",
            question: "48 ÷ 4",
            discrimination: "العشرات: 4÷4=1 · الآحاد: 8÷4=2 | Tens: 4÷4=1 · Units: 8÷4=2",
            rule: "اقسم من الكبار للصغار وطرح مباشر | Divide high to low with direct subtraction",
            fingerMovement: "ضع 1 في عشرات الخارج 👍 · اطرح 4 بالسبابة ⬇️ · ضع 2 في آحاد الخارج 👍 · اطرح 8 بكماشة 🗜️ | Set 1 in tens quotient 👍 · Subtract 4 with index ⬇️ · Set 2 in units quotient 👍 · Subtract 8 with pinch 🗜️",
            steps: [
              "العشرات ÷ 4: 4 ÷ 4 = 1 → ضع 1 في عشرات الخارج 👍 | Tens ÷ 4: 4 ÷ 4 = 1 → Set 1 in tens quotient 👍",
              "الخصم: 1 × 4 = 4 → اطرح 4 من العشرات بسحبة سبابة ⬇️ | Subtraction: 1 × 4 = 4 → Subtract 4 from tens with index pull ⬇️",
              "الآحاد ÷ 4: 8 ÷ 4 = 2 → ضع 2 في آحاد الخارج 👍 | Units ÷ 4: 8 ÷ 4 = 2 → Set 2 in units quotient 👍",
              "الخصم: 2 × 4 = 8 → اطرح 8 من الآحاد بكماشة مغلقة 🗜️ | Subtraction: 2 × 4 = 8 → Subtract 8 from units with closed pinch 🗜️",
              "الناتج النهائي: 12 | Final Result: 12",
            ],
            result: 12,
            beadVisual: "1 عشرات + 2 آحاد في الخارج | 1 tens + 2 units in quotient",
          },
          {
            id: "S07-m1-E4",
            question: "96 ÷ 3",
            discrimination: "العشرات: 9÷3=3 · الآحاد: 6÷3=2 | Tens: 9÷3=3 · Units: 6÷3=2",
            rule: "اقسم من الكبار للصغار وطرح مباشر | Divide high to low with direct subtraction",
            fingerMovement: "ضع 3 في عشرات الخارج 👍 · اطرح 9 بكماشة 🗜️ · ضع 2 في آحاد الخارج 👍 · اطرح 6 بكماشة 🗜️ | Set 3 in tens quotient 👍 · Subtract 9 with pinch 🗜️ · Set 2 in units quotient 👍 · Subtract 6 with pinch 🗜️",
            steps: [
              "العشرات ÷ 3: 9 ÷ 3 = 3 → ضع 3 في عشرات الخارج 👍 | Tens ÷ 3: 9 ÷ 3 = 3 → Set 3 in tens quotient 👍",
              "الخصم: 3 × 3 = 9 → اطرح 9 من العشرات بكماشة مغلقة 🗜️ | Subtraction: 3 × 3 = 9 → Subtract 9 from tens with closed pinch 🗜️",
              "الآحاد ÷ 3: 6 ÷ 3 = 2 → ضع 2 في آحاد الخارج 👍 | Units ÷ 3: 6 ÷ 3 = 2 → Set 2 in units quotient 👍",
              "الخصم: 2 × 3 = 6 → اطرح 6 من الآحاد بكماشة مغلقة 🗜️ | Subtraction: 2 × 3 = 6 → Subtract 6 from units with closed pinch 🗜️",
              "الناتج النهائي: 32 | Final Result: 32",
            ],
            result: 32,
            beadVisual: "3 عشرات + 2 آحاد في الخارج | 3 tens + 2 units in quotient",
          },
          {
            id: "S07-m1-E5",
            question: "88 ÷ 4",
            discrimination: "العشرات: 8÷4=2 · الآحاد: 8÷4=2 | Tens: 8÷4=2 · Units: 8÷4=2",
            rule: "اقسم من الكبار للصغار وطرح مباشر | Divide high to low with direct subtraction",
            fingerMovement: "ضع 2 في عشرات الخارج 👍 · اطرح 8 بكماشة 🗜️ · ضع 2 في آحاد الخارج 👍 · اطرح 8 بكماشة 🗜️ | Set 2 in tens quotient 👍 · Subtract 8 with pinch 🗜️ · Set 2 in units quotient 👍 · Subtract 8 with pinch 🗜️",
            steps: [
              "العشرات ÷ 4: 8 ÷ 4 = 2 → ضع 2 في عشرات الخارج 👍 | Tens ÷ 4: 8 ÷ 4 = 2 → Set 2 in tens quotient 👍",
              "الخصم: 2 × 4 = 8 → اطرح 8 من العشرات بكماشة مغلقة 🗜️ | Subtraction: 2 × 4 = 8 → Subtract 8 from tens with closed pinch 🗜️",
              "الآحاد ÷ 4: 8 ÷ 4 = 2 → ضع 2 في آحاد الخارج 👍 | Units ÷ 4: 8 ÷ 4 = 2 → Set 2 in units quotient 👍",
              "الخصم: 2 × 4 = 8 → اطرح 8 من الآحاد بكماشة مغلقة 🗜️ | Subtraction: 2 × 4 = 8 → Subtract 8 from units with closed pinch 🗜️",
              "الناتج النهائي: 22 | Final Result: 22",
            ],
            result: 22,
            beadVisual: "2 عشرات + 2 آحاد في الخارج | 2 tens + 2 units in quotient",
          },
        ],
      },
      tryPhase: {
        exercises: [
          {
            id: "S07-m1-T1",
            question: "86 ÷ 2",
            discrimination: "8÷2=4 · 6÷2=3 | 8÷2=4 · 6÷2=3",
            steps: [
              "العشرات: 8 ÷ 2 = 4 → ضع 4 في عشرات الخارج 👍 | Tens: 8 ÷ 2 = 4 → Set 4 in tens quotient 👍",
              "الخصم: 4 × 2 = 8 → اطرح 8 بكماشة مغلقة 🗜️ | Subtraction: 4 × 2 = 8 → Subtract 8 with pinch 🗜️",
              "الآحاد: 6 ÷ 2 = 3 → ضع 3 في آحاد الخارج 👍 | Units: 6 ÷ 2 = 3 → Set 3 in units quotient 👍",
              "الخصم: 3 × 2 = 6 → اطرح 6 بكماشة مغلقة 🗜️ | Subtraction: 3 × 2 = 6 → Subtract 6 with pinch 🗜️",
              "الناتج النهائي: 43 | Final Result: 43",
            ],
            result: 43,
          },
          {
            id: "S07-m1-T2",
            question: "66 ÷ 3",
            discrimination: "6÷3=2 · 6÷3=2 | 6÷3=2 · 6÷3=2",
            steps: [
              "العشرات: 6 ÷ 3 = 2 → ضع 2 في عشرات الخارج 👍 | Tens: 6 ÷ 3 = 2 → Set 2 in tens quotient 👍",
              "الخصم: 2 × 3 = 6 → اطرح 6 بكماشة مغلقة 🗜️ | Subtraction: 2 × 3 = 6 → Subtract 6 with pinch 🗜️",
              "الآحاد: 6 ÷ 3 = 2 → ضع 2 في آحاد الخارج 👍 | Units: 6 ÷ 3 = 2 → Set 2 in units quotient 👍",
              "الخصم: 2 × 3 = 6 → اطرح 6 بكماشة مغلقة 🗜️ | Subtraction: 2 × 3 = 6 → Subtract 6 with pinch 🗜️",
              "الناتج النهائي: 22 | Final Result: 22",
            ],
            result: 22,
          },
          {
            id: "S07-m1-T3",
            question: "44 ÷ 2",
            discrimination: "4÷2=2 · 4÷2=2 | 4÷2=2 · 4÷2=2",
            steps: [
              "العشرات: 4 ÷ 2 = 2 → ضع 2 في عشرات الخارج 👍 | Tens: 4 ÷ 2 = 2 → Set 2 in tens quotient 👍",
              "الخصم: 2 × 2 = 4 → اطرح 4 بسحبة سبابة ⬇️ | Subtraction: 2 × 2 = 4 → Subtract 4 with index ⬇️",
              "الآحاد: 4 ÷ 2 = 2 → ضع 2 في آحاد الخارج 👍 | Units: 4 ÷ 2 = 2 → Set 2 in units quotient 👍",
              "الخصم: 2 × 2 = 4 → اطرح 4 بسحبة سبابة ⬇️ | Subtraction: 2 × 2 = 4 → Subtract 4 with index ⬇️",
              "الناتج النهائي: 22 | Final Result: 22",
            ],
            result: 22,
          },
          {
            id: "S07-m1-T4",
            question: "63 ÷ 3",
            discrimination: "6÷3=2 · 3÷3=1 | 6÷3=2 · 3÷3=1",
            steps: [
              "العشرات: 6 ÷ 3 = 2 → ضع 2 في عشرات الخارج 👍 | Tens: 6 ÷ 3 = 2 → Set 2 in tens quotient 👍",
              "الخصم: 2 × 3 = 6 → اطرح 6 بكماشة مغلقة 🗜️ | Subtraction: 2 × 3 = 6 → Subtract 6 with pinch 🗜️",
              "الآحاد: 3 ÷ 3 = 1 → ضع 1 في آحاد الخارج 👍 | Units: 3 ÷ 3 = 1 → Set 1 in units quotient 👍",
              "الخصم: 1 × 3 = 3 → اطرح 3 بسحبة سبابة ⬇️ | Subtraction: 1 × 3 = 3 → Subtract 3 with index ⬇️",
              "الناتج النهائي: 21 | Final Result: 21",
            ],
            result: 21,
          },
          {
            id: "S07-m1-T5",
            question: "39 ÷ 3",
            discrimination: "3÷3=1 · 9÷3=3 | 3÷3=1 · 9÷3=3",
            steps: [
              "العشرات: 3 ÷ 3 = 1 → ضع 1 في عشرات الخارج 👍 | Tens: 3 ÷ 3 = 1 → Set 1 in tens quotient 👍",
              "الخصم: 1 × 3 = 3 → اطرح 3 بسحبة سبابة ⬇️ | Subtraction: 1 × 3 = 3 → Subtract 3 with index ⬇️",
              "الآحاد: 9 ÷ 3 = 3 → ضع 3 في آحاد الخارج 👍 | Units: 9 ÷ 3 = 3 → Set 3 in units quotient 👍",
              "الخصم: 3 × 3 = 9 → اطرح 9 بكماشة مغلقة 🗜️ | Subtraction: 3 × 3 = 9 → Subtract 9 with pinch 🗜️",
              "الناتج النهائي: 13 | Final Result: 13",
            ],
            result: 13,
          },
        ],
      },
    },

    // ═══════════════════════════════════════════════════════════
    // m2 — القسمة بأصدقاء 5
    // ═══════════════════════════════════════════════════════════
    {
      id: "m2",
      ruleCategory: "small_friends",
      title: "القسمة بأصدقاء 5 | Division with Friends of 5",
      titleEn: "Division with Friends of 5",
      emoji: "🤝",
      miniStory: {
        title: "مفتاح الجدة 5 - التبادل الذكي | Grandma 5's Key - Smart Exchange",
        emoji: "👵",
        story: "في الغرفة الثانية، أراد الأبطال قسمة 54 حلوى على 3 أصدقاء. 5 قسمة 3 تساوي 1، لكن الخصم يحتاج طرح 3 من 5! ابتسمت الجدة 5 من السطح وقالت: ارفعوني لأعلى وارفعوا صديقي 2 معكم بحركة رفع مزدوج! | In room 2, heroes wanted to divide 54 candies among 3 friends. 5 ÷ 3 = 1, but subtracting 3 from 5 needs help! Grandma 5 smiled from above: Lift me up and lift my friend 2 with a Double Lift!",
        storyAudioText: "أربع وخمسون حلوى على ثلاثة أصدقاء. خمس عشرات قسمة ثلاثة تساوي عشرة واحدة. لكن الطرح يحتاج طرح ثلاثة من خمسة. الجدة خمسة تتدخل: ارفع خمسة وارفع اثنين. الناتج ثمانية عشر. | 54 candies shared among 3 friends. 5 tens divided by 3 equals 1 ten. Subtracting 3 from 5 needs Grandma 5: Lift 5 and lift 2. Result is 18.",
        storyAudioId: null,
      },
      rule: {
        description: "أصدقاء 5 👵: عندما لا تكفي السفليات للطرح، ارفع الخرزة الخماسية بالسبابة وارفع الصديق بالإبهام بحركة رفع مزدوج ⬆️⬆️! | Friends of 5 👵: When lower beads are insufficient, lift 5 with index and lift friend with thumb in a Double Lift ⬆️⬆️!",
        cases: [
          { from: 1, formula: "−1 = −5 + 4" },
          { from: 2, formula: "−2 = −5 + 3" },
          { from: 3, formula: "−3 = −5 + 2" },
          { from: 4, formula: "−4 = −5 + 1" },
        ],
      },
      condition: {
        formula: "السفليات غير كافية · العلوية 5 مفعّلة | Lower beads insufficient · Upper 5 active",
        explanation: "نستخدم أصدقاء 5 عندما تكون الخرزة الخماسية منزلة والخرزات السفلية المرفوعة أقل من المطلوب طرحه! | Use Friends of 5 when Upper 5 is down and active lower beads are less than needed!",
      },
      discrimination: {
        steps: [
          {
            question: "هل الخرزات السفلية غير كافية للطرح؟ | Are lower beads insufficient for subtraction?",
            type: "comparison",
            actual: "السفليات < المطلوب | Lower beads < Subtrahend",
            answer: "نعم → استخدم أصدقاء 5 | Yes → Use Friends of 5",
          },
          {
            question: "هل الخرزة العلوية 5 مفعّلة؟ | Is Upper 5 active?",
            type: "yes-no",
            answer: "نعم → نفذ حركة رفع مزدوج ⬆️⬆️ | Yes → Perform Double Lift ⬆️⬆️",
          },
        ],
        decision: "أصدقاء 5 — ارفع 5 وارفع الصديق! | Friends of 5 — Lift 5 and lift friend!",
      },
      watchPhase: {
        examples: [
          {
            id: "S07-m2-E1",
            question: "54 ÷ 3",
            discrimination: "5÷3=1 · طرح 3 من 5 → أصدقاء 5 | 5÷3=1 · Subtract 3 from 5 → Friends of 5",
            rule: "−3 = −5 + 2",
            fingerMovement: "ضع 1 في عشرات الخارج 👍 · رفع مزدوج ⬆️⬆️ (ارفع 5 وارفع 2) · ضع 8 في آحاد الخارج 🗜️ · اطرح 24 مباشرة | Set 1 in tens quotient 👍 · Double Lift ⬆️⬆️ (lift 5 & lift 2) · Set 8 in units quotient 🗜️ · Subtract 24 directly",
            steps: [
              "العشرات ÷ 3: 5 ÷ 3 = 1 → ضع 1 في عشرات الخارج 👍 | Tens ÷ 3: 5 ÷ 3 = 1 → Set 1 in tens quotient 👍",
              "الخصم: 1 × 3 = 3 → اطرح 3 من 5 عشرات بحركة «رفع مزدوج» ⬆️⬆️ (−3 = −5 + 2) → العشرات = 2 | Subtraction: 1 × 3 = 3 → Subtract 3 from 5 tens with «Double Lift» ⬆️⬆️ (−3 = −5 + 2) → Tens = 2",
              "الآحاد + المرحّل: 24 ÷ 3 = 8 → ضع 8 في آحاد الخارج بكماشة مغلقة 🗜️ | Units + Remainder: 24 ÷ 3 = 8 → Set 8 in units quotient with closed pinch 🗜️",
              "الخصم: 8 × 3 = 24 → اطرح 2 من العشرات و4 من الآحاد مباشرة ⬇️ | Subtraction: 8 × 3 = 24 → Subtract 2 from tens and 4 from units directly ⬇️",
              "الناتج النهائي: 18 | Final Result: 18",
            ],
            result: 18,
            beadVisual: "1 عشرات + 8 آحاد في الخارج | 1 tens + 8 units in quotient",
          },
          {
            id: "S07-m2-E2",
            question: "52 ÷ 2",
            discrimination: "5÷2=2 · طرح 4 من 5 → أصدقاء 5 | 5÷2=2 · Subtract 4 from 5 → Friends of 5",
            rule: "−4 = −5 + 1",
            fingerMovement: "ضع 2 في عشرات الخارج 👍 · رفع مزدوج ⬆️⬆️ (ارفع 5 وارفع 1) · ضع 6 في آحاد الخارج 🗜️ · اطرح 12 مباشرة | Set 2 in tens quotient 👍 · Double Lift ⬆️⬆️ (lift 5 & lift 1) · Set 6 in units quotient 🗜️ · Subtract 12 directly",
            steps: [
              "العشرات ÷ 2: 5 ÷ 2 = 2 → ضع 2 في عشرات الخارج 👍 | Tens ÷ 2: 5 ÷ 2 = 2 → Set 2 in tens quotient 👍",
              "الخصم: 2 × 2 = 4 → اطرح 4 من 5 عشرات بحركة «رفع مزدوج» ⬆️⬆️ (−4 = −5 + 1) → العشرات = 1 | Subtraction: 2 × 2 = 4 → Subtract 4 from 5 tens with «Double Lift» ⬆️⬆️ (−4 = −5 + 1) → Tens = 1",
              "الآحاد + المرحّل: 12 ÷ 2 = 6 → ضع 6 في آحاد الخارج بكماشة مغلقة 🗜️ | Units + Remainder: 12 ÷ 2 = 6 → Set 6 in units quotient with closed pinch 🗜️",
              "الخصم: 6 × 2 = 12 → اطرح 1 من العشرات و2 من الآحاد مباشرة ⬇️ | Subtraction: 6 × 2 = 12 → Subtract 1 from tens and 2 from units directly ⬇️",
              "الناتج النهائي: 26 | Final Result: 26",
            ],
            result: 26,
            beadVisual: "2 عشرات + 6 آحاد في الخارج | 2 tens + 6 units in quotient",
          },
          {
            id: "S07-m2-E3",
            question: "56 ÷ 4",
            discrimination: "5÷4=1 · طرح 4 من 5 → أصدقاء 5 | 5÷4=1 · Subtract 4 from 5 → Friends of 5",
            rule: "−4 = −5 + 1",
            fingerMovement: "ضع 1 في عشرات الخارج 👍 · رفع مزدوج ⬆️⬆️ (ارفع 5 وارفع 1) · ضع 4 في آحاد الخارج 👍 · اطرح 16 مباشرة | Set 1 in tens quotient 👍 · Double Lift ⬆️⬆️ (lift 5 & lift 1) · Set 4 in units quotient 👍 · Subtract 16 directly",
            steps: [
              "العشرات ÷ 4: 5 ÷ 4 = 1 → ضع 1 في عشرات الخارج 👍 | Tens ÷ 4: 5 ÷ 4 = 1 → Set 1 in tens quotient 👍",
              "الخصم: 1 × 4 = 4 → اطرح 4 من 5 عشرات بحركة «رفع مزدوج» ⬆️⬆️ (−4 = −5 + 1) → العشرات = 1 | Subtraction: 1 × 4 = 4 → Subtract 4 from 5 tens with «Double Lift» ⬆️⬆️ (−4 = −5 + 1) → Tens = 1",
              "الآحاد + المرحّل: 16 ÷ 4 = 4 → ضع 4 في آحاد الخارج بدفعة إبهام 👍 | Units + Remainder: 16 ÷ 4 = 4 → Set 4 in units quotient with thumb push 👍",
              "الخصم: 4 × 4 = 16 → اطرح 1 من العشرات و6 من الآحاد مباشرة 🗜️ | Subtraction: 4 × 4 = 16 → Subtract 1 from tens and 6 from units directly 🗜️",
              "الناتج النهائي: 14 | Final Result: 14",
            ],
            result: 14,
            beadVisual: "1 عشرات + 4 آحاد في الخارج | 1 tens + 4 units in quotient",
          },
          {
            id: "S07-m2-E4",
            question: "68 ÷ 4",
            discrimination: "6÷4=1 · طرح 4 من 6 → أصدقاء 5 | 6÷4=1 · Subtract 4 from 6 → Friends of 5",
            rule: "−4 = −5 + 1",
            fingerMovement: "ضع 1 في عشرات الخارج 👍 · رفع مزدوج ⬆️⬆️ (ارفع 5 وارفع 1) · ضع 7 في آحاد الخارج 🗜️ · اطرح 28 مباشرة | Set 1 in tens quotient 👍 · Double Lift ⬆️⬆️ (lift 5 & lift 1) · Set 7 in units quotient 🗜️ · Subtract 28 directly",
            steps: [
              "العشرات ÷ 4: 6 ÷ 4 = 1 → ضع 1 في عشرات الخارج 👍 | Tens ÷ 4: 6 ÷ 4 = 1 → Set 1 in tens quotient 👍",
              "الخصم: 1 × 4 = 4 → اطرح 4 من 6 عشرات بحركة «رفع مزدوج» ⬆️⬆️ (−4 = −5 + 1) → العشرات = 2 | Subtraction: 1 × 4 = 4 → Subtract 4 from 6 tens with «Double Lift» ⬆️⬆️ (−4 = −5 + 1) → Tens = 2",
              "الآحاد + المرحّل: 28 ÷ 4 = 7 → ضع 7 في آحاد الخارج بكماشة مغلقة 🗜️ | Units + Remainder: 28 ÷ 4 = 7 → Set 7 in units quotient with closed pinch 🗜️",
              "الخصم: 7 × 4 = 28 → اطرح 2 من العشرات و8 من الآحاد مباشرة 🗜️ | Subtraction: 7 × 4 = 28 → Subtract 2 from tens and 8 from units directly 🗜️",
              "الناتج النهائي: 17 | Final Result: 17",
            ],
            result: 17,
            beadVisual: "1 عشرات + 7 آحاد في الخارج | 1 tens + 7 units in quotient",
          },
          {
            id: "S07-m2-E5",
            question: "51 ÷ 3",
            discrimination: "5÷3=1 · طرح 3 من 5 → أصدقاء 5 | 5÷3=1 · Subtract 3 from 5 → Friends of 5",
            rule: "−3 = −5 + 2",
            fingerMovement: "ضع 1 في عشرات الخارج 👍 · رفع مزدوج ⬆️⬆️ (ارفع 5 وارفع 2) · ضع 7 في آحاد الخارج 🗜️ · اطرح 21 مباشرة | Set 1 in tens quotient 👍 · Double Lift ⬆️⬆️ (lift 5 & lift 2) · Set 7 in units quotient 🗜️ · Subtract 21 directly",
            steps: [
              "العشرات ÷ 3: 5 ÷ 3 = 1 → ضع 1 في عشرات الخارج 👍 | Tens ÷ 3: 5 ÷ 3 = 1 → Set 1 in tens quotient 👍",
              "الخصم: 1 × 3 = 3 → اطرح 3 من 5 عشرات بحركة «رفع مزدوج» ⬆️⬆️ (−3 = −5 + 2) → العشرات = 2 | Subtraction: 1 × 3 = 3 → Subtract 3 from 5 tens with «Double Lift» ⬆️⬆️ (−3 = −5 + 2) → Tens = 2",
              "الآحاد + المرحّل: 21 ÷ 3 = 7 → ضع 7 في آحاد الخارج بكماشة مغلقة 🗜️ | Units + Remainder: 21 ÷ 3 = 7 → Set 7 in units quotient with closed pinch 🗜️",
              "الخصم: 7 × 3 = 21 → اطرح 2 من العشرات و1 من الآحاد مباشرة ⬇️ | Subtraction: 7 × 3 = 21 → Subtract 2 from tens and 1 from units directly ⬇️",
              "الناتج النهائي: 17 | Final Result: 17",
            ],
            result: 17,
            beadVisual: "1 عشرات + 7 آحاد في الخارج | 1 tens + 7 units in quotient",
          },
        ],
      },
      tryPhase: {
        exercises: [
          {
            id: "S07-m2-T1",
            question: "58 ÷ 2",
            discrimination: "−4 = −5 + 1",
            steps: [
              "العشرات: 5 ÷ 2 = 2 → ضع 2 في عشرات الخارج 👍 | Tens: 5 ÷ 2 = 2 → Set 2 in tens quotient 👍",
              "الخصم: 4 → رفع مزدوج ⬆️⬆️ (−4 = −5 + 1) → العشرات = 1 | Subtraction: 4 → Double Lift ⬆️⬆️ (−4 = −5 + 1) → Tens = 1",
              "الآحاد: 18 ÷ 2 = 9 → ضع 9 في آحاد الخارج 🗜️ | Units: 18 ÷ 2 = 9 → Set 9 in units quotient 🗜️",
              "الخصم: اطرح 18 مباشرة 🗜️ | Subtraction: Subtract 18 directly 🗜️",
              "الناتج النهائي: 29 | Final Result: 29",
            ],
            result: 29,
          },
          {
            id: "S07-m2-T2",
            question: "54 ÷ 2",
            discrimination: "−4 = −5 + 1",
            steps: [
              "العشرات: 5 ÷ 2 = 2 → ضع 2 في عشرات الخارج 👍 | Tens: 5 ÷ 2 = 2 → Set 2 in tens quotient 👍",
              "الخصم: 4 → رفع مزدوج ⬆️⬆️ (−4 = −5 + 1) → العشرات = 1 | Subtraction: 4 → Double Lift ⬆️⬆️ (−4 = −5 + 1) → Tens = 1",
              "الآحاد: 14 ÷ 2 = 7 → ضع 7 في آحاد الخارج 🗜️ | Units: 14 ÷ 2 = 7 → Set 7 in units quotient 🗜️",
              "الخصم: اطرح 14 مباشرة ⬇️ | Subtraction: Subtract 14 directly ⬇️",
              "الناتج النهائي: 27 | Final Result: 27",
            ],
            result: 27,
          },
          {
            id: "S07-m2-T3",
            question: "57 ÷ 3",
            discrimination: "−3 = −5 + 2",
            steps: [
              "العشرات: 5 ÷ 3 = 1 → ضع 1 في عشرات الخارج 👍 | Tens: 5 ÷ 3 = 1 → Set 1 in tens quotient 👍",
              "الخصم: 3 → رفع مزدوج ⬆️⬆️ (−3 = −5 + 2) → العشرات = 2 | Subtraction: 3 → Double Lift ⬆️⬆️ (−3 = −5 + 2) → Tens = 2",
              "الآحاد: 27 ÷ 3 = 9 → ضع 9 في آحاد الخارج 🗜️ | Units: 27 ÷ 3 = 9 → Set 9 in units quotient 🗜️",
              "الخصم: اطرح 27 مباشرة 🗜️ | Subtraction: Subtract 27 directly 🗜️",
              "الناتج النهائي: 19 | Final Result: 19",
            ],
            result: 19,
          },
          {
            id: "S07-m2-T4",
            question: "60 ÷ 4",
            discrimination: "−4 = −5 + 1",
            steps: [
              "العشرات: 6 ÷ 4 = 1 → ضع 1 في عشرات الخارج 👍 | Tens: 6 ÷ 4 = 1 → Set 1 in tens quotient 👍",
              "الخصم: 4 → رفع مزدوج ⬆️⬆️ (−4 = −5 + 1) → العشرات = 2 | Subtraction: 4 → Double Lift ⬆️⬆️ (−4 = −5 + 1) → Tens = 2",
              "الآحاد: 20 ÷ 4 = 5 → ضع 5 في آحاد الخارج ⬇️ | Units: 20 ÷ 4 = 5 → Set 5 in units quotient ⬇️",
              "الخصم: اطرح 20 مباشرة ⬇️ | Subtraction: Subtract 20 directly ⬇️",
              "الناتج النهائي: 15 | Final Result: 15",
            ],
            result: 15,
          },
          {
            id: "S07-m2-T5",
            question: "64 ÷ 4",
            discrimination: "−4 = −5 + 1",
            steps: [
              "العشرات: 6 ÷ 4 = 1 → ضع 1 في عشرات الخارج 👍 | Tens: 6 ÷ 4 = 1 → Set 1 in tens quotient 👍",
              "الخصم: 4 → رفع مزدوج ⬆️⬆️ (−4 = −5 + 1) → العشرات = 2 | Subtraction: 4 → Double Lift ⬆️⬆️ (−4 = −5 + 1) → Tens = 2",
              "الآحاد: 24 ÷ 4 = 6 → ضع 6 في آحاد الخارج 🗜️ | Units: 24 ÷ 4 = 6 → Set 6 in units quotient 🗜️",
              "الخصم: اطرح 24 مباشرة ⬇️ | Subtraction: Subtract 24 directly ⬇️",
              "الناتج النهائي: 16 | Final Result: 16",
            ],
            result: 16,
          },
        ],
      },
    },

    // ═══════════════════════════════════════════════════════════
    // m3 — القسمة بأصدقاء 10
    // ═══════════════════════════════════════════════════════════
    {
      id: "m3",
      ruleCategory: "big_friends",
      title: "القسمة بأصدقاء 10 | Division with Friends of 10",
      titleEn: "Division with Friends of 10",
      emoji: "🌟",
      miniStory: {
        title: "مفتاح العملاق 10 - الاستعارة الكبرى | Giant 10's Key - Big Borrowing",
        emoji: "🦶",
        story: "في المحطة الثالثة، واجه الأبطال مسألة 152 ÷ 8. 15 عشرات قسمة 8 تساوي 1، لكن طرح 8 من 5 غير ممكن مباشرة! نادى البطل العملاق 10 يساراً: اطرح 10 من المئات بسحبة سبابة ⬇️ وأضف الصديق 2 في العشرات بالإبهام! | In stage 3, heroes faced 152 ÷ 8. 15 tens ÷ 8 = 1, but subtracting 8 from 5 is impossible directly! The hero called Giant 10 on the left: Subtract 10 from hundreds with index pull ⬇️ and add friend 2 to tens with thumb!",
        storyAudioText: "مئة واثنان وخمسون حلوى على ثمانية أصدقاء. خمس عشرة عشرة قسمة ثمانية تساوي عشرة واحدة. طرح ثمانية يحتاج استعارة من المئات. اطرح عشرة وأضف اثنين. الناتج تسعة عشر. | 152 candies shared among 8 friends. 15 tens divided by 8 equals 1 ten. Subtracting 8 needs borrowing from hundreds. Subtract 10 and add 2. Result is 19.",
        storyAudioId: null,
      },
      rule: {
        description: "أصدقاء 10 🌟: عندما لا تكفي الخرزات للطرح، اطرح 10 من العمود الأيسر بسحبة سبابة ⬇️ وأضف الصديق (مكمل 10) في عمودك بالإبهام! | Friends of 10 🌟: When beads are insufficient, subtract 10 from the left column with index pull ⬇️ and add friend (complement of 10) to your column with thumb!",
        cases: [
          { from: 1, formula: "−1 = −10 + 9" },
          { from: 2, formula: "−2 = −10 + 8" },
          { from: 3, formula: "−3 = −10 + 7" },
          { from: 4, formula: "−4 = −10 + 6" },
          { from: 5, formula: "−5 = −10 + 5" },
          { from: 6, formula: "−6 = −10 + 4" },
          { from: 7, formula: "−7 = −10 + 3" },
          { from: 8, formula: "−8 = −10 + 2" },
          { from: 9, formula: "−9 = −10 + 1" },
        ],
      },
      condition: {
        formula: "المطلوب > خرزات العمود · العمود الأيسر مفعّل | Subtrahend > Column beads · Left column active",
        explanation: "نستعير 10 من العمود الأيسر عندما تتجاوز قيمة الخصم الخرزات المتاحة في العمود الحالي! | Borrow 10 from the left column when subtraction exceeds current available beads!",
      },
      discrimination: {
        steps: [
          {
            question: "هل الخرزات المتاحة بالعمود أقل من المطلوب طرحه؟ | Are available column beads less than required?",
            type: "yes-no",
            answer: "نعم → استخدم أصدقاء 10 | Yes → Use Friends of 10",
          },
          {
            question: "هل العمود الأيسر يحتوي على خرزة للاستعارة؟ | Does the left column have a bead to borrow?",
            type: "yes-no",
            answer: "نعم → اطرح 10 من اليسار وأضف صديق 10 | Yes → Subtract 10 from left and add Friend of 10",
          },
        ],
        decision: "أصدقاء 10 — اطرح 10 بسحبة سبابة وأضف الصديق! | Friends of 10 — Subtract 10 with index pull and add Friend!",
      },
      watchPhase: {
        examples: [
          {
            id: "S07-m3-E1",
            question: "152 ÷ 8",
            discrimination: "15÷8=1 · طرح 8 من 15 → أصدقاء 10 | 15÷8=1 · Subtract 8 from 15 → Friends of 10",
            rule: "−8 = −10 + 2",
            fingerMovement: "ضع 1 في عشرات الخارج 👍 · اطرح 1 مئات بسحبة سبابة ⬇️ · ارفع 2 عشرات بالإبهام ⬆️ · ضع 9 في آحاد الخارج | Set 1 in tens quotient 👍 · Subtract 1 hundreds with index pull ⬇️ · Lift 2 tens with thumb ⬆️ · Set 9 in units quotient",
            steps: [
              "العشرات ÷ 8: 15 ÷ 8 = 1 → ضع 1 في عشرات الخارج 👍 | Tens ÷ 8: 15 ÷ 8 = 1 → Set 1 in tens quotient 👍",
              "الخصم: 1 × 8 = 8 → اطرح 8 من 15 بسحبة سبابة ⬇️ لخصم 10 من المئات (1→0) وإضافة 2 إلى العشرات بالإبهام (5+2=7) → العداد = 72 | Subtraction: 1 × 8 = 8 → Subtract 8 from 15 by index pull ⬇️ to deduct 10 from hundreds and adding 2 to tens with thumb → Abacus = 72",
              "الآحاد: 72 ÷ 8 = 9 → ضع 9 في آحاد الخارج بكماشة مغلقة 🗜️ | Units: 72 ÷ 8 = 9 → Set 9 in units quotient with closed pinch 🗜️",
              "الخصم: 9 × 8 = 72 → اطرح 72 مباشرة 🗜️ | Subtraction: 9 × 8 = 72 → Subtract 72 directly 🗜️",
              "الناتج النهائي: 19 | Final Result: 19",
            ],
            result: 19,
            beadVisual: "1 عشرات + 9 آحاد في الخارج | 1 tens + 9 units in quotient",
          },
          {
            id: "S07-m3-E2",
            question: "144 ÷ 9",
            discrimination: "14÷9=1 · طرح 9 من 14 → أصدقاء 10 | 14÷9=1 · Subtract 9 from 14 → Friends of 10",
            rule: "−9 = −10 + 1",
            fingerMovement: "ضع 1 في عشرات الخارج 👍 · اطرح 1 مئات بسحبة سبابة ⬇️ · ارفع 1 عشرات بالإبهام ⬆️ · ضع 6 في آحاد الخارج 🗜️ | Set 1 in tens quotient 👍 · Subtract 1 hundreds with index pull ⬇️ · Lift 1 tens with thumb ⬆️ · Set 6 in units quotient 🗜️",
            steps: [
              "العشرات ÷ 9: 14 ÷ 9 = 1 → ضع 1 في عشرات الخارج 👍 | Tens ÷ 9: 14 ÷ 9 = 1 → Set 1 in tens quotient 👍",
              "الخصم: 1 × 9 = 9 → اطرح 9 من 14 بسحبة سبابة ⬇️ لخصم 10 من المئات وإضافة 1 إلى العشرات بالإبهام (4+1=5) → العداد = 54 | Subtraction: 1 × 9 = 9 → Subtract 9 from 14 by index pull ⬇️ to deduct 10 from hundreds and adding 1 to tens with thumb → Abacus = 54",
              "الآحاد: 54 ÷ 9 = 6 → ضع 6 في آحاد الخارج بكماشة مغلقة 🗜️ | Units: 54 ÷ 9 = 6 → Set 6 in units quotient with closed pinch 🗜️",
              "الخصم: 6 × 9 = 54 → اطرح 54 مباشرة 🗜️ | Subtraction: 6 × 9 = 54 → Subtract 54 directly 🗜️",
              "الناتج النهائي: 16 | Final Result: 16",
            ],
            result: 16,
            beadVisual: "1 عشرات + 6 آحاد في الخارج | 1 tens + 6 units in quotient",
          },
          {
            id: "S07-m3-E3",
            question: "135 ÷ 9",
            discrimination: "13÷9=1 · طرح 9 من 13 → أصدقاء 10 | 13÷9=1 · Subtract 9 from 13 → Friends of 10",
            rule: "−9 = −10 + 1",
            fingerMovement: "ضع 1 في عشرات الخارج 👍 · اطرح 1 مئات بسحبة سبابة ⬇️ · ارفع 1 عشرات بالإبهام ⬆️ · ضع 5 في آحاد الخارج ⬇️ | Set 1 in tens quotient 👍 · Subtract 1 hundreds with index pull ⬇️ · Lift 1 tens with thumb ⬆️ · Set 5 in units quotient ⬇️",
            steps: [
              "العشرات ÷ 9: 13 ÷ 9 = 1 → ضع 1 في عشرات الخارج 👍 | Tens ÷ 9: 13 ÷ 9 = 1 → Set 1 in tens quotient 👍",
              "الخصم: 1 × 9 = 9 → اطرح 9 من 13 بسحبة سبابة ⬇️ لخصم 10 من المئات وإضافة 1 إلى العشرات بالإبهام (3+1=4) → العداد = 45 | Subtraction: 1 × 9 = 9 → Subtract 9 from 13 by index pull ⬇️ to deduct 10 from hundreds and adding 1 to tens with thumb → Abacus = 45",
              "الآحاد: 45 ÷ 9 = 5 → ضع 5 في آحاد الخارج بسحبة سبابة ⬇️ | Units: 45 ÷ 9 = 5 → Set 5 in units quotient with index ⬇️",
              "الخصم: 5 × 9 = 45 → اطرح 45 مباشرة 🗜️ | Subtraction: 5 × 9 = 45 → Subtract 45 directly 🗜️",
              "الناتج النهائي: 15 | Final Result: 15",
            ],
            result: 15,
            beadVisual: "1 عشرات + 5 آحاد في الخارج | 1 tens + 5 units in quotient",
          },
          {
            id: "S07-m3-E4",
            question: "153 ÷ 9",
            discrimination: "15÷9=1 · طرح 9 من 15 → أصدقاء 10 | 15÷9=1 · Subtract 9 from 15 → Friends of 10",
            rule: "−9 = −10 + 1",
            fingerMovement: "ضع 1 في عشرات الخارج 👍 · اطرح 1 مئات بسحبة سبابة ⬇️ · ارفع 1 عشرات بالإبهام ⬆️ · ضع 7 في آحاد الخارج 🗜️ | Set 1 in tens quotient 👍 · Subtract 1 hundreds with index pull ⬇️ · Lift 1 tens with thumb ⬆️ · Set 7 in units quotient 🗜️",
            steps: [
              "العشرات ÷ 9: 15 ÷ 9 = 1 → ضع 1 في عشرات الخارج 👍 | Tens ÷ 9: 15 ÷ 9 = 1 → Set 1 in tens quotient 👍",
              "الخصم: 1 × 9 = 9 → اطرح 9 من 15 بسحبة سبابة ⬇️ لخصم 10 من المئات وإضافة 1 إلى العشرات بالإبهام (5+1=6) → العداد = 63 | Subtraction: 1 × 9 = 9 → Subtract 9 from 15 by index pull ⬇️ to deduct 10 from hundreds and adding 1 to tens with thumb → Abacus = 63",
              "الآحاد: 63 ÷ 9 = 7 → ضع 7 في آحاد الخارج بكماشة مغلقة 🗜️ | Units: 63 ÷ 9 = 7 → Set 7 in units quotient with closed pinch 🗜️",
              "الخصم: 7 × 9 = 63 → اطرح 63 مباشرة 🗜️ | Subtraction: 7 × 9 = 63 → Subtract 63 directly 🗜️",
              "الناتج النهائي: 17 | Final Result: 17",
            ],
            result: 17,
            beadVisual: "1 عشرات + 7 آحاد في الخارج | 1 tens + 7 units in quotient",
          },
          {
            id: "S07-m3-E5",
            question: "162 ÷ 9",
            discrimination: "16÷9=1 · طرح 9 من 16 → أصدقاء 10 | 16÷9=1 · Subtract 9 from 16 → Friends of 10",
            rule: "−9 = −10 + 1",
            fingerMovement: "ضع 1 في عشرات الخارج 👍 · اطرح 1 مئات بسحبة سبابة ⬇️ · ارفع 1 عشرات بالإبهام ⬆️ · ضع 8 في آحاد الخارج 🗜️ | Set 1 in tens quotient 👍 · Subtract 1 hundreds with index pull ⬇️ · Lift 1 tens with thumb ⬆️ · Set 8 in units quotient 🗜️",
            steps: [
              "العشرات ÷ 9: 16 ÷ 9 = 1 → ضع 1 في عشرات الخارج 👍 | Tens ÷ 9: 16 ÷ 9 = 1 → Set 1 in tens quotient 👍",
              "الخصم: 1 × 9 = 9 → اطرح 9 من 16 بسحبة سبابة ⬇️ لخصم 10 من المئات وإضافة 1 إلى العشرات بالإبهام (6+1=7) → العداد = 72 | Subtraction: 1 × 9 = 9 → Subtract 9 from 16 by index pull ⬇️ to deduct 10 from hundreds and adding 1 to tens with thumb → Abacus = 72",
              "الآحاد: 72 ÷ 9 = 8 → ضع 8 في آحاد الخارج بكماشة مغلقة 🗜️ | Units: 72 ÷ 9 = 8 → Set 8 in units quotient with closed pinch 🗜️",
              "الخصم: 8 × 9 = 72 → اطرح 72 مباشرة 🗜️ | Subtraction: 8 × 9 = 72 → Subtract 72 directly 🗜️",
              "الناتج النهائي: 18 | Final Result: 18",
            ],
            result: 18,
            beadVisual: "1 عشرات + 8 آحاد في الخارج | 1 tens + 8 units in quotient",
          },
        ],
      },
      tryPhase: {
        exercises: [
          {
            id: "S07-m3-T1",
            question: "152 ÷ 8",
            discrimination: "−8 = −10 + 2",
            steps: [
              "15 ÷ 8 = 1 → ضع 1 في عشرات الخارج 👍 | 15 ÷ 8 = 1 → Set 1 in tens quotient 👍",
              "−8 = −10 + 2 → اطرح 1 مئات بسحبة سبابة ⬇️ وارفع 2 عشرات بالإبهام (العداد = 72) | −8 = −10 + 2 → Subtract 1 hundreds with index pull ⬇️ & add 2 tens with thumb (Abacus = 72)",
              "72 ÷ 8 = 9 → ضع 9 في آحاد الخارج 🗜️ | 72 ÷ 8 = 9 → Set 9 in units quotient 🗜️",
              "اطرح 72 مباشرة → الناتج 19 | Subtract 72 directly → Result 19",
            ],
            result: 19,
          },
          {
            id: "S07-m3-T2",
            question: "144 ÷ 9",
            discrimination: "−9 = −10 + 1",
            steps: [
              "14 ÷ 9 = 1 → ضع 1 في عشرات الخارج 👍 | 14 ÷ 9 = 1 → Set 1 in tens quotient 👍",
              "−9 = −10 + 1 → اطرح 1 مئات بسحبة سبابة ⬇️ وارفع 1 عشرات بالإبهام (العداد = 54) | −9 = −10 + 1 → Subtract 1 hundreds with index pull ⬇️ & add 1 tens with thumb (Abacus = 54)",
              "54 ÷ 9 = 6 → ضع 6 في آحاد الخارج 🗜️ | 54 ÷ 9 = 6 → Set 6 in units quotient 🗜️",
              "اطرح 54 مباشرة → الناتج 16 | Subtract 54 directly → Result 16",
            ],
            result: 16,
          },
          {
            id: "S07-m3-T3",
            question: "135 ÷ 9",
            discrimination: "−9 = −10 + 1",
            steps: [
              "13 ÷ 9 = 1 → ضع 1 في عشرات الخارج 👍 | 13 ÷ 9 = 1 → Set 1 in tens quotient 👍",
              "−9 = −10 + 1 → اطرح 1 مئات بسحبة سبابة ⬇️ وارفع 1 عشرات بالإبهام (العداد = 45) | −9 = −10 + 1 → Subtract 1 hundreds with index pull ⬇️ & add 1 tens with thumb (Abacus = 45)",
              "45 ÷ 9 = 5 → ضع 5 في آحاد الخارج ⬇️ | 45 ÷ 9 = 5 → Set 5 in units quotient ⬇️",
              "اطرح 45 مباشرة → الناتج 15 | Subtract 45 directly → Result 15",
            ],
            result: 15,
          },
          {
            id: "S07-m3-T4",
            question: "153 ÷ 9",
            discrimination: "−9 = −10 + 1",
            steps: [
              "15 ÷ 9 = 1 → ضع 1 في عشرات الخارج 👍 | 15 ÷ 9 = 1 → Set 1 in tens quotient 👍",
              "−9 = −10 + 1 → اطرح 1 مئات بسحبة سبابة ⬇️ وارفع 1 عشرات بالإبهام (العداد = 63) | −9 = −10 + 1 → Subtract 1 hundreds with index pull ⬇️ & add 1 tens with thumb (Abacus = 63)",
              "63 ÷ 9 = 7 → ضع 7 في آحاد الخارج 🗜️ | 63 ÷ 9 = 7 → Set 7 in units quotient 🗜️",
              "اطرح 63 مباشرة → الناتج 17 | Subtract 63 directly → Result 17",
            ],
            result: 17,
          },
          {
            id: "S07-m3-T5",
            question: "162 ÷ 9",
            discrimination: "−9 = −10 + 1",
            steps: [
              "16 ÷ 9 = 1 → ضع 1 في عشرات الخارج 👍 | 16 ÷ 9 = 1 → Set 1 in tens quotient 👍",
              "−9 = −10 + 1 → اطرح 1 مئات بسحبة سبابة ⬇️ وارفع 1 عشرات بالإبهام (العداد = 72) | −9 = −10 + 1 → Subtract 1 hundreds with index pull ⬇️ & add 1 tens with thumb (Abacus = 72)",
              "72 ÷ 9 = 8 → ضع 8 في آحاد الخارج 🗜️ | 72 ÷ 9 = 8 → Set 8 in units quotient 🗜️",
              "اطرح 72 مباشرة → الناتج 18 | Subtract 72 directly → Result 18",
            ],
            result: 18,
          },
        ],
      },
    },

    // ═══════════════════════════════════════════════════════════
    // m4 — القسمة المركّبة
    // ═══════════════════════════════════════════════════════════
    {
      id: "m4",
      ruleCategory: "combined",
      title: "القسمة المركّبة | Compound Division",
      titleEn: "Compound Division",
      emoji: "🎯",
      miniStory: {
        title: "مفتاح التحالف المزدوج - قوة أصدقاء 10 و5 | Dual Alliance Key - Power of Friends of 10 & 5",
        emoji: "👑",
        story: "في التحدي النهائي الغرفة السرية 216 ÷ 8: 21 قسمة 8 تساوي 2، لكن طرح 16 يحتاج استعارة 10 AND أصدقاء 5 لإضافة المكمل! اتحد الجدة 5 والعملاق 10 لفتح الباب: اطرح 10 من اليسار بسحبة سبابة ⬇️، وتفعيل 5 بالسبابة وطرد الخرزات الزائدة بنزول مزدوج ⬇️⬇️! | In the final room 216 ÷ 8: 21 ÷ 8 = 2, but subtracting 16 requires borrowing 10 AND using Friends of 5 to add the complement! Grandma 5 and Giant 10 united: Subtract 10 from left with index pull ⬇️, activate 5 and push excess beads down with Double Drop ⬇️⬇️!",
        storyAudioText: "مئتان وستة عشر حلوى على ثمانية أصدقاء. واحد وعشرون قسمة ثمانية تساوي اثنين. لكن طرح ستة عشر يحتاج استعارة عشرة وأيضا صديق خمسة. الجدة خمسة والعملاق عشرة يتعاونان. الناتج سبعة وعشرون. | 216 candies shared among 8 friends. 21 divided by 8 equals 2. Subtracting 16 needs borrowing 10 and Friend of 5. Grandma 5 and Giant 10 cooperate. Result is 27.",
        storyAudioId: null,
      },
      rule: {
        description: "التحالف المزدوج 👑: عندما تستعير 10 ولا تكفي السفليات لإضافة المكمل، استخدم الصيغة المركبة: −10 + 5 − (5−k) باستعارة 10 بسحبة سبابة ⬇️، ثم نزول مزدوج ⬇️⬇️ لتفعيل 5 وطرد الزائد! | Dual Alliance 👑: When borrowing 10 and lower beads can't hold the complement, use compound rule: −10 + 5 − (5−k) by borrowing 10 with index pull ⬇️, then Double Drop ⬇️⬇️ to activate 5 and push excess down!",
        cases: [
          { from: 6, formula: "−6 = −10 + 5 − 1" },
          { from: 7, formula: "−7 = −10 + 5 − 2" },
          { from: 8, formula: "−8 = −10 + 5 − 3" },
          { from: 9, formula: "−9 = −10 + 5 − 4" },
        ],
      },
      condition: {
        formula: "المطلوب > خرزات العمود · المتمّم > السفليات المتاحة | Subtrahend > Column beads · Complement > Free lower beads",
        explanation: "نحتاج للجمع المركب عندما نستعير 10 ولكن إضافة المكمّل تتطلب استخدام صديق 5 في نفس الوقت! | We need compound rule when borrowing 10 requires using Friend of 5 to add the complement simultaneously!",
      },
      discrimination: {
        steps: [
          {
            question: "هل الخرزات المتاحة أقل من المطلوب طرحه؟ | Are available beads less than required?",
            type: "yes-no",
            answer: "نعم → نحتاج استعارة 10 | Yes → Need to borrow 10",
          },
          {
            question: "هل الخرزات السفلية غير كافية لإضافة المكمل المباشر؟ | Are lower beads insufficient to add the direct complement?",
            type: "yes-no",
            answer: "نعم → استخدم التحالف المزدوج (−10 + 5 − k) | Yes → Use Dual Alliance (−10 + 5 − k)",
          },
        ],
        decision: "تحالف مزدوج — سحبة سبابة للاستعارة 10 + نزول مزدوج لتفعيل 5 وطرد الزائد! | Dual Alliance — Index pull to borrow 10 + Double drop to activate 5 & push excess down!",
      },
      watchPhase: {
        examples: [
          {
            id: "S07-m4-E1",
            question: "216 ÷ 8",
            discrimination: "21÷8=2 · طرح 16 من 21 → استعارة 10 + أصدقاء 5 | 21÷8=2 · Subtract 16 from 21 → Borrow 10 + Friends of 5",
            rule: "−6 = −10 + 5 − 1",
            fingerMovement: "ضع 2 في عشرات الخارج 👍 · اطرح 1 عشرات ⬇️ · سحبة سبابة ☝️⬇️ على المئات (استعارة 10) + نزول مزدوج ⬇️⬇️ على العشرات (سبابة تفعّل 5 ⬇️ + إبهام يطرد 1 ⬇️) · ضع 7 في آحاد الخارج 🗜️ | Set 2 in tens quotient 👍 · Subtract 1 tens ⬇️ · Index pull ☝️⬇️ on hundreds (borrow 10) + Double Drop ⬇️⬇️ on tens (index activates 5 ⬇️ + thumb pushes 1 down ⬇️) · Set 7 in units quotient 🗜️",
            steps: [
              "العشرات ÷ 8: 21 ÷ 8 = 2 → ضع 2 في عشرات الخارج 👍 | Tens ÷ 8: 21 ÷ 8 = 2 → Set 2 in tens quotient 👍",
              "الخصم: 2 × 8 = 16 → اطرح 16 من 21: اطرح 1 عشرات (2−1=1)، ثم سحبة سبابة ☝️⬇️ على المئات (استعارة 10)، ونزول مزدوج ⬇️⬇️ على العشرات (السبابة تفعّل 5 ⬇️ والإبهام يطرد 1 ⬇️) → العداد = 56 | Subtraction: 2 × 8 = 16 → Subtract 16 from 21: Deduct 1 tens (2−1=1), index pull ☝️⬇️ on hundreds (borrow 10), and Double Drop ⬇️⬇️ on tens (index activates 5 ⬇️ & thumb pushes 1 down ⬇️) → Abacus = 56",
              "الآحاد: 56 ÷ 8 = 7 → ضع 7 في آحاد الخارج بكماشة مغلقة 🗜️ | Units: 56 ÷ 8 = 7 → Set 7 in units quotient with closed pinch 🗜️",
              "الخصم: 7 × 8 = 56 → اطرح 56 مباشرة 🗜️ | Subtraction: 7 × 8 = 56 → Subtract 56 directly 🗜️",
              "الناتج النهائي: 27 | Final Result: 27",
            ],
            result: 27,
            beadVisual: "2 عشرات + 7 آحاد في الخارج | 2 tens + 7 units in quotient",
          },
          {
            id: "S07-m4-E2",
            question: "224 ÷ 8",
            discrimination: "22÷8=2 · طرح 16 من 22 → استعارة 10 + أصدقاء 5 | 22÷8=2 · Subtract 16 from 22 → Borrow 10 + Friends of 5",
            rule: "−6 = −10 + 5 − 1",
            fingerMovement: "ضع 2 في عشرات الخارج 👍 · اطرح 1 عشرات ⬇️ · سحبة سبابة ☝️⬇️ على المئات (استعارة 10) + نزول مزدوج ⬇️⬇️ على العشرات (سبابة تفعّل 5 ⬇️ + إبهام يطرد 1 ⬇️) · ضع 8 في آحاد الخارج 🗜️ | Set 2 in tens quotient 👍 · Subtract 1 tens ⬇️ · Index pull ☝️⬇️ on hundreds (borrow 10) + Double Drop ⬇️⬇️ on tens (index activates 5 ⬇️ + thumb pushes 1 down ⬇️) · Set 8 in units quotient 🗜️",
            steps: [
              "العشرات ÷ 8: 22 ÷ 8 = 2 → ضع 2 في عشرات الخارج 👍 | Tens ÷ 8: 22 ÷ 8 = 2 → Set 2 in tens quotient 👍",
              "الخصم: 2 × 8 = 16 → اطرح 16 من 22: اطرح 1 عشرات (2−1=1)، ثم سحبة سبابة ☝️⬇️ على المئات (استعارة 10)، ونزول مزدوج ⬇️⬇️ على العشرات (السبابة تفعّل 5 ⬇️ والإبهام يطرد 1 ⬇️) → العداد = 64 | Subtraction: 2 × 8 = 16 → Subtract 16 from 22: Deduct 1 tens (2−1=1), index pull ☝️⬇️ on hundreds (borrow 10), and Double Drop ⬇️⬇️ on tens (index activates 5 ⬇️ & thumb pushes 1 down ⬇️) → Abacus = 64",
              "الآحاد: 64 ÷ 8 = 8 → ضع 8 في آحاد الخارج بكماشة مغلقة 🗜️ | Units: 64 ÷ 8 = 8 → Set 8 in units quotient with closed pinch 🗜️",
              "الخصم: 8 × 8 = 64 → اطرح 64 مباشرة ⬇️ | Subtraction: 8 × 8 = 64 → Subtract 64 directly ⬇️",
              "الناتج النهائي: 28 | Final Result: 28",
            ],
            result: 28,
            beadVisual: "2 عشرات + 8 آحاد في الخارج | 2 tens + 8 units in quotient",
          },
          {
            id: "S07-m4-E3",
            question: "232 ÷ 8",
            discrimination: "23÷8=2 · طرح 16 من 23 → استعارة 10 + أصدقاء 5 | 23÷8=2 · Subtract 16 from 23 → Borrow 10 + Friends of 5",
            rule: "−6 = −10 + 5 − 1",
            fingerMovement: "ضع 2 في عشرات الخارج 👍 · اطرح 1 عشرات ⬇️ · سحبة سبابة ☝️⬇️ على المئات (استعارة 10) + نزول مزدوج ⬇️⬇️ على العشرات (سبابة تفعّل 5 ⬇️ + إبهام يطرد 1 ⬇️) · ضع 9 في آحاد الخارج 🗜️ | Set 2 in tens quotient 👍 · Subtract 1 tens ⬇️ · Index pull ☝️⬇️ on hundreds (borrow 10) + Double Drop ⬇️⬇️ on tens (index activates 5 ⬇️ + thumb pushes 1 down ⬇️) · Set 9 in units quotient 🗜️",
            steps: [
              "العشرات ÷ 8: 23 ÷ 8 = 2 → ضع 2 في عشرات الخارج 👍 | Tens ÷ 8: 23 ÷ 8 = 2 → Set 2 in tens quotient 👍",
              "الخصم: 2 × 8 = 16 → اطرح 16 من 23: اطرح 1 عشرات (2−1=1)، ثم سحبة سبابة ☝️⬇️ على المئات (استعارة 10)، ونزول مزدوج ⬇️⬇️ على العشرات (السبابة تفعّل 5 ⬇️ والإبهام يطرد 1 ⬇️) → العداد = 72 | Subtraction: 2 × 8 = 16 → Subtract 16 from 23: Deduct 1 tens (2−1=1), index pull ☝️⬇️ on hundreds (borrow 10), and Double Drop ⬇️⬇️ on tens (index activates 5 ⬇️ & thumb pushes 1 down ⬇️) → Abacus = 72",
              "الآحاد: 72 ÷ 8 = 9 → ضع 9 في آحاد الخارج بكماشة مغلقة 🗜️ | Units: 72 ÷ 8 = 9 → Set 9 in units quotient with closed pinch 🗜️",
              "الخصم: 9 × 8 = 72 → اطرح 72 مباشرة 🗜️ | Subtraction: 9 × 8 = 72 → Subtract 72 directly 🗜️",
              "الناتج النهائي: 29 | Final Result: 29",
            ],
            result: 29,
            beadVisual: "2 عشرات + 9 آحاد في الخارج | 2 tens + 9 units in quotient",
          },
          {
            id: "S07-m4-E4",
            question: "234 ÷ 6",
            discrimination: "23÷6=3 · طرح 18 من 23 → استعارة 10 + أصدقاء 5 | 23÷6=3 · Subtract 18 from 23 → Borrow 10 + Friends of 5",
            rule: "−8 = −10 + 5 − 3",
            fingerMovement: "ضع 3 في عشرات الخارج 👍 · اطرح 1 عشرات ⬇️ · سحبة سبابة ☝️⬇️ على المئات (استعارة 10) + نزول مزدوج ⬇️⬇️ على العشرات (سبابة تفعّل 5 ⬇️ + إبهام يطرد 3 ⬇️) · ضع 9 في آحاد الخارج 🗜️ | Set 3 in tens quotient 👍 · Subtract 1 tens ⬇️ · Index pull ☝️⬇️ on hundreds (borrow 10) + Double Drop ⬇️⬇️ on tens (index activates 5 ⬇️ + thumb pushes 3 down ⬇️) · Set 9 in units quotient 🗜️",
            steps: [
              "العشرات ÷ 6: 23 ÷ 6 = 3 → ضع 3 في عشرات الخارج 👍 | Tens ÷ 6: 23 ÷ 6 = 3 → Set 3 in tens quotient 👍",
              "الخصم: 3 × 6 = 18 → اطرح 18 من 23: اطرح 1 عشرات (2−1=1)، ثم سحبة سبابة ☝️⬇️ على المئات (استعارة 10)، ونزول مزدوج ⬇️⬇️ على العشرات (السبابة تفعّل 5 ⬇️ والإبهام يطرد 3 ⬇️) → العداد = 54 | Subtraction: 3 × 6 = 18 → Subtract 18 from 23: Deduct 1 tens (2−1=1), index pull ☝️⬇️ on hundreds (borrow 10), and Double Drop ⬇️⬇️ on tens (index activates 5 ⬇️ & thumb pushes 3 down ⬇️) → Abacus = 54",
              "الآحاد: 54 ÷ 6 = 9 → ضع 9 في آحاد الخارج بكماشة مغلقة 🗜️ | Units: 54 ÷ 6 = 9 → Set 9 in units quotient with closed pinch 🗜️",
              "الخصم: 9 × 6 = 54 → اطرح 54 مباشرة 🗜️ | Subtraction: 9 × 6 = 54 → Subtract 54 directly 🗜️",
              "الناتج النهائي: 39 | Final Result: 39",
            ],
            result: 39,
            beadVisual: "3 عشرات + 9 آحاد في الخارج | 3 tens + 9 units in quotient",
          },
          {
            id: "S07-m4-E5",
            question: "324 ÷ 9",
            discrimination: "32÷9=3 · طرح 27 من 32 → استعارة 10 + أصدقاء 5 | 32÷9=3 · Subtract 27 from 32 → Borrow 10 + Friends of 5",
            rule: "−7 = −10 + 5 − 2",
            fingerMovement: "ضع 3 في عشرات الخارج 👍 · اطرح 2 عشرات ⬇️ · سحبة سبابة ☝️⬇️ على المئات (استعارة 10) + نزول مزدوج ⬇️⬇️ على العشرات (سبابة تفعّل 5 ⬇️ + إبهام يطرد 2 ⬇️) · ضع 6 في آحاد الخارج 🗜️ | Set 3 in tens quotient 👍 · Subtract 2 tens ⬇️ · Index pull ☝️⬇️ on hundreds (borrow 10) + Double Drop ⬇️⬇️ on tens (index activates 5 ⬇️ + thumb pushes 2 down ⬇️) · Set 6 in units quotient 🗜️",
            steps: [
              "العشرات ÷ 9: 32 ÷ 9 = 3 → ضع 3 في عشرات الخارج 👍 | Tens ÷ 9: 32 ÷ 9 = 3 → Set 3 in tens quotient 👍",
              "الخصم: 3 × 9 = 27 → اطرح 27 من 32: اطرح 2 عشرات (3−2=1)، ثم سحبة سبابة ☝️⬇️ على المئات (استعارة 10)، ونزول مزدوج ⬇️⬇️ على العشرات (السبابة تفعّل 5 ⬇️ والإبهام يطرد 2 ⬇️) → العداد = 54 | Subtraction: 3 × 9 = 27 → Subtract 27 from 32: Deduct 2 tens (3−2=1), index pull ☝️⬇️ on hundreds (borrow 10), and Double Drop ⬇️⬇️ on tens (index activates 5 ⬇️ & thumb pushes 2 down ⬇️) → Abacus = 54",
              "الآحاد: 54 ÷ 9 = 6 → ضع 6 في آحاد الخارج بكماشة مغلقة 🗜️ | Units: 54 ÷ 9 = 6 → Set 6 in units quotient with closed pinch 🗜️",
              "الخصم: 6 × 9 = 54 → اطرح 54 مباشرة 🗜️ | Subtraction: 6 × 9 = 54 → Subtract 54 directly 🗜️",
              "الناتج النهائي: 36 | Final Result: 36",
            ],
            result: 36,
            beadVisual: "3 عشرات + 6 آحاد في الخارج | 3 tens + 6 units in quotient",
          },
        ],
      },
      tryPhase: {
        exercises: [
          {
            id: "S07-m4-T1",
            question: "216 ÷ 8",
            discrimination: "−6 = −10 + 5 − 1",
            steps: [
              "21 ÷ 8 = 2 → ضع 2 في عشرات الخارج 👍 | 21 ÷ 8 = 2 → Set 2 in tens quotient 👍",
              "−16: اطرح 1 عشرات واخصم 6 بسحبة سبابة ☝️⬇️ (استعارة 10) + نزول مزدوج ⬇️⬇️ (تفعيل 5 وطرد 1) (العداد = 56) | −16: Subtract 1 tens & deduct 6 with index pull ☝️⬇️ (borrow 10) + Double Drop ⬇️⬇️ (activate 5 & push 1 down) (Abacus = 56)",
              "56 ÷ 8 = 7 → ضع 7 في آحاد الخارج 🗜️ | 56 ÷ 8 = 7 → Set 7 in units quotient 🗜️",
              "اطرح 56 مباشرة → الناتج 27 | Subtract 56 directly → Result 27",
            ],
            result: 27,
          },
          {
            id: "S07-m4-T2",
            question: "224 ÷ 8",
            discrimination: "−6 = −10 + 5 − 1",
            steps: [
              "22 ÷ 8 = 2 → ضع 2 في عشرات الخارج 👍 | 22 ÷ 8 = 2 → Set 2 in tens quotient 👍",
              "−16: اطرح 1 عشرات واخصم 6 بسحبة سبابة ☝️⬇️ (استعارة 10) + نزول مزدوج ⬇️⬇️ (تفعيل 5 وطرد 1) (العداد = 64) | −16: Subtract 1 tens & deduct 6 with index pull ☝️⬇️ (borrow 10) + Double Drop ⬇️⬇️ (activate 5 & push 1 down) (Abacus = 64)",
              "64 ÷ 8 = 8 → ضع 8 في آحاد الخارج 🗜️ | 64 ÷ 8 = 8 → Set 8 in units quotient 🗜️",
              "اطرح 64 مباشرة → الناتج 28 | Subtract 64 directly → Result 28",
            ],
            result: 28,
          },
          {
            id: "S07-m4-T3",
            question: "232 ÷ 8",
            discrimination: "−6 = −10 + 5 − 1",
            steps: [
              "23 ÷ 8 = 2 → ضع 2 في عشرات الخارج 👍 | 23 ÷ 8 = 2 → Set 2 in tens quotient 👍",
              "−16: اطرح 1 عشرات واخصم 6 بسحبة سبابة ☝️⬇️ (استعارة 10) + نزول مزدوج ⬇️⬇️ (تفعيل 5 وطرد 1) (العداد = 72) | −16: Subtract 1 tens & deduct 6 with index pull ☝️⬇️ (borrow 10) + Double Drop ⬇️⬇️ (activate 5 & push 1 down) (Abacus = 72)",
              "72 ÷ 8 = 9 → ضع 9 في آحاد الخارج 🗜️ | 72 ÷ 8 = 9 → Set 9 in units quotient 🗜️",
              "اطرح 72 مباشرة → الناتج 29 | Subtract 72 directly → Result 29",
            ],
            result: 29,
          },
          {
            id: "S07-m4-T4",
            question: "234 ÷ 6",
            discrimination: "−8 = −10 + 5 − 3",
            steps: [
              "23 ÷ 6 = 3 → ضع 3 في عشرات الخارج 👍 | 23 ÷ 6 = 3 → Set 3 in tens quotient 👍",
              "−18: اطرح 1 عشرات واخصم 8 بسحبة سبابة ☝️⬇️ (استعارة 10) + نزول مزدوج ⬇️⬇️ (تفعيل 5 وطرد 3) (العداد = 54) | −18: Subtract 1 tens & deduct 8 with index pull ☝️⬇️ (borrow 10) + Double Drop ⬇️⬇️ (activate 5 & push 3 down) (Abacus = 54)",
              "54 ÷ 6 = 9 → ضع 9 في آحاد الخارج 🗜️ | 54 ÷ 6 = 9 → Set 9 in units quotient 🗜️",
              "اطرح 54 مباشرة → الناتج 39 | Subtract 54 directly → Result 39",
            ],
            result: 39,
          },
          {
            id: "S07-m4-T5",
            question: "324 ÷ 9",
            discrimination: "−7 = −10 + 5 − 2",
            steps: [
              "32 ÷ 9 = 3 → ضع 3 في عشرات الخارج 👍 | 32 ÷ 9 = 3 → Set 3 in tens quotient 👍",
              "−27: اطرح 2 عشرات واخصم 7 بسحبة سبابة ☝️⬇️ (استعارة 10) + نزول مزدوج ⬇️⬇️ (تفعيل 5 وطرد 2) (العداد = 54) | −27: Subtract 2 tens & deduct 7 with index pull ☝️⬇️ (borrow 10) + Double Drop ⬇️⬇️ (activate 5 & push 2 down) (Abacus = 54)",
              "54 ÷ 9 = 6 → ضع 6 في آحاد الخارج 🗜️ | 54 ÷ 9 = 6 → Set 6 in units quotient 🗜️",
              "اطرح 54 مباشرة → الناتج 36 | Subtract 54 directly → Result 36",
            ],
            result: 36,
          },
        ],
      },
    },
  ],

  outro: {
    summary: "أتقنت القسمة على رقم واحد: بسيطة · أصدقاء 5 · أصدقاء 10 · مركّبة! | Mastered division by one digit: Direct, Friends of 5, Friends of 10, and Compound!",
    encouragement: "🎉 أنت بطل القسمة! حان وقت تمرين المزيد. | 🎉 You are a division champion! Time to practice more.",
    totalExamples: 20,
  },

  estimatedMinutes: 20,
  xpReward: 15,
};

export default S07_LESSON;
