// src/curriculum/lessons/L0/S2.ts
// 📖 درس S2: القيمة المكانية وبناء الأعداد

import type { LessonNode, LessonExample, TryQuestion } from '../types';

// ═══════════════════════════════════════════════════════════
// 📝 الأمثلة المحلولة (10 أمثلة — "شاهد")
// ═══════════════════════════════════════════════════════════

const EXAMPLES: LessonExample[] = [
  // ─── 1) مثّل 12 ───
  {
    id: 'SRB-L0-S02-E-001',
    problemText: 'مثّل الرقم 12',
    answer: 12,
    ruleCategory: 'build',
    steps: [
      {
        stepIndex: 1,
        instructionText: 'حدد عدد المراتب: عشرات وآحاد',
        fingerUsed: 'index',
        direction: 'down',
        targetColumn: 'units',
        beadsAffected: [],
        expectedValueAfter: 0,
      },
      {
        stepIndex: 2,
        instructionText: 'في الآحاد: ارفع خرزتين (2)',
        fingerUsed: 'thumb',
        direction: 'up',
        targetColumn: 'units',
        beadsAffected: [1, 2],
        expectedValueAfter: 2,
      },
      {
        stepIndex: 3,
        instructionText: 'في العشرات: ارفع خرزة واحدة (10)',
        fingerUsed: 'thumb',
        direction: 'up',
        targetColumn: 'tens',
        beadsAffected: [1],
        expectedValueAfter: 12,
      },
    ],
    explanation: 'الرقم 12 = 10 + 2. خرزة عشرات واحدة + خرزتان آحاد.',
  },

  // ─── 2) مثّل 34 ───
  {
    id: 'SRB-L0-S02-E-002',
    problemText: 'مثّل الرقم 34',
    answer: 34,
    ruleCategory: 'build',
    steps: [
      {
        stepIndex: 1,
        instructionText: 'في الآحاد: ارفع أربع خرزات (4)',
        fingerUsed: 'thumb',
        direction: 'up',
        targetColumn: 'units',
        beadsAffected: [1, 2, 3, 4],
        expectedValueAfter: 4,
      },
      {
        stepIndex: 2,
        instructionText: 'في العشرات: ارفع ثلاث خرزات (30)',
        fingerUsed: 'thumb',
        direction: 'up',
        targetColumn: 'tens',
        beadsAffected: [1, 2, 3],
        expectedValueAfter: 34,
      },
    ],
    explanation: 'الرقم 34 = 30 + 4.',
  },

  // ─── 3) مثّل 58 ───
  {
    id: 'SRB-L0-S02-E-003',
    problemText: 'مثّل الرقم 58',
    answer: 58,
    ruleCategory: 'build',
    steps: [
      {
        stepIndex: 1,
        instructionText: 'في الآحاد: أنزل الخرزة العلوية (5) + ارفع 3 (7)',
        fingerUsed: 'both_pinch',
        direction: 'pinch_in',
        targetColumn: 'units',
        beadsAffected: [5, 1, 2, 3],
        expectedValueAfter: 8,
      },
      {
        stepIndex: 2,
        instructionText: 'في العشرات: أنزل الخرزة العلوية (50)',
        fingerUsed: 'index',
        direction: 'down',
        targetColumn: 'tens',
        beadsAffected: [5],
        expectedValueAfter: 58,
      },
    ],
    explanation: 'الرقم 58 = 50 + 8.',
  },

  // ─── 4) مثّل 70 ───
  {
    id: 'SRB-L0-S02-E-004',
    problemText: 'مثّل الرقم 70',
    answer: 70,
    ruleCategory: 'build',
    steps: [
      {
        stepIndex: 1,
        instructionText: 'في الآحاد: لا خرزة (0)',
        fingerUsed: 'index',
        direction: 'down',
        targetColumn: 'units',
        beadsAffected: [],
        expectedValueAfter: 0,
      },
      {
        stepIndex: 2,
        instructionText: 'في العشرات: أنزل الخرزة العلوية (50) + ارفع 2 (70)',
        fingerUsed: 'both_pinch',
        direction: 'pinch_in',
        targetColumn: 'tens',
        beadsAffected: [5, 1, 2],
        expectedValueAfter: 70,
      },
    ],
    explanation: 'الرقم 70 = 70 + 0. صفر في الآحاد يعني لا خرزة.',
  },

  // ─── 5) مثّل 91 ───
  {
    id: 'SRB-L0-S02-E-005',
    problemText: 'مثّل الرقم 91',
    answer: 91,
    ruleCategory: 'build',
    steps: [
      {
        stepIndex: 1,
        instructionText: 'في الآحاد: ارفع خرزة واحدة (1)',
        fingerUsed: 'thumb',
        direction: 'up',
        targetColumn: 'units',
        beadsAffected: [1],
        expectedValueAfter: 1,
      },
      {
        stepIndex: 2,
        instructionText: 'في العشرات: أنزل العلوية (50) + ارفع 4 (90)',
        fingerUsed: 'both_pinch',
        direction: 'pinch_in',
        targetColumn: 'tens',
        beadsAffected: [5, 1, 2, 3, 4],
        expectedValueAfter: 91,
      },
    ],
    explanation: 'الرقم 91 = 90 + 1.',
  },

  // ─── 6) مثّل 205 ───
  {
    id: 'SRB-L0-S02-E-006',
    problemText: 'مثّل الرقم 205',
    answer: 205,
    ruleCategory: 'build',
    steps: [
      {
        stepIndex: 1,
        instructionText: 'في الآحاد: أنزل العلوية (5)',
        fingerUsed: 'index',
        direction: 'down',
        targetColumn: 'units',
        beadsAffected: [5],
        expectedValueAfter: 5,
      },
      {
        stepIndex: 2,
        instructionText: 'في العشرات: صفر (لا خرزة)',
        fingerUsed: 'index',
        direction: 'down',
        targetColumn: 'tens',
        beadsAffected: [],
        expectedValueAfter: 5,
      },
      {
        stepIndex: 3,
        instructionText: 'في المئات: ارفع خرزتين (200)',
        fingerUsed: 'thumb',
        direction: 'up',
        targetColumn: 'hundreds',
        beadsAffected: [1, 2],
        expectedValueAfter: 205,
      },
    ],
    explanation: 'الرقم 205 = 200 + 0 + 5. الصفر في العشرات مهم!',
  },

  // ─── 7) مثّل 340 ───
  {
    id: 'SRB-L0-S02-E-007',
    problemText: 'مثّل الرقم 340',
    answer: 340,
    ruleCategory: 'build',
    steps: [
      {
        stepIndex: 1,
        instructionText: 'في الآحاد: صفر',
        fingerUsed: 'index',
        direction: 'down',
        targetColumn: 'units',
        beadsAffected: [],
        expectedValueAfter: 0,
      },
      {
        stepIndex: 2,
        instructionText: 'في العشرات: ارفع أربع خرزات (40)',
        fingerUsed: 'thumb',
        direction: 'up',
        targetColumn: 'tens',
        beadsAffected: [1, 2, 3, 4],
        expectedValueAfter: 40,
      },
      {
        stepIndex: 3,
        instructionText: 'في المئات: ارفع ثلاث خرزات (300)',
        fingerUsed: 'thumb',
        direction: 'up',
        targetColumn: 'hundreds',
        beadsAffected: [1, 2, 3],
        expectedValueAfter: 340,
      },
    ],
    explanation: 'الرقم 340 = 300 + 40 + 0.',
  },

  // ─── 8) مثّل 406 ───
  {
    id: 'SRB-L0-S02-E-008',
    problemText: 'مثّل الرقم 406',
    answer: 406,
    ruleCategory: 'build',
    steps: [
      {
        stepIndex: 1,
        instructionText: 'في الآحاد: أنزل العلوية + ارفع 1 (6)',
        fingerUsed: 'both_pinch',
        direction: 'pinch_in',
        targetColumn: 'units',
        beadsAffected: [5, 1],
        expectedValueAfter: 6,
      },
      {
        stepIndex: 2,
        instructionText: 'في العشرات: صفر',
        fingerUsed: 'index',
        direction: 'down',
        targetColumn: 'tens',
        beadsAffected: [],
        expectedValueAfter: 6,
      },
      {
        stepIndex: 3,
        instructionText: 'في المئات: ارفع أربع خرزات (400)',
        fingerUsed: 'thumb',
        direction: 'up',
        targetColumn: 'hundreds',
        beadsAffected: [1, 2, 3, 4],
        expectedValueAfter: 406,
      },
    ],
    explanation: 'الرقم 406 = 400 + 0 + 6.',
  },

  // ─── 9) مثّل 583 ───
  {
    id: 'SRB-L0-S02-E-009',
    problemText: 'مثّل الرقم 583',
    answer: 583,
    ruleCategory: 'build',
    steps: [
      {
        stepIndex: 1,
        instructionText: 'في الآحاد: أنزل العلوية + ارفع 3 (8)',
        fingerUsed: 'both_pinch',
        direction: 'pinch_in',
        targetColumn: 'units',
        beadsAffected: [5, 1, 2, 3],
        expectedValueAfter: 8,
      },
      {
        stepIndex: 2,
        instructionText: 'في العشرات: أنزل العلوية + ارفع 3 (80)',
        fingerUsed: 'both_pinch',
        direction: 'pinch_in',
        targetColumn: 'tens',
        beadsAffected: [5, 1, 2, 3],
        expectedValueAfter: 88,
      },
      {
        stepIndex: 3,
        instructionText: 'في المئات: أنزل العلوية (500)',
        fingerUsed: 'index',
        direction: 'down',
        targetColumn: 'hundreds',
        beadsAffected: [5],
        expectedValueAfter: 583,
      },
    ],
    explanation: 'الرقم 583 = 500 + 80 + 3.',
  },

  // ─── 10) مثّل 709 ───
  {
    id: 'SRB-L0-S02-E-010',
    problemText: 'مثّل الرقم 709',
    answer: 709,
    ruleCategory: 'build',
    steps: [
      {
        stepIndex: 1,
        instructionText: 'في الآحاد: أنزل العلوية + ارفع 4 (9)',
        fingerUsed: 'both_pinch',
        direction: 'pinch_in',
        targetColumn: 'units',
        beadsAffected: [5, 1, 2, 3, 4],
        expectedValueAfter: 9,
      },
      {
        stepIndex: 2,
        instructionText: 'في العشرات: صفر',
        fingerUsed: 'index',
        direction: 'down',
        targetColumn: 'tens',
        beadsAffected: [],
        expectedValueAfter: 9,
      },
      {
        stepIndex: 3,
        instructionText: 'في المئات: أنزل العلوية + ارفع 2 (700)',
        fingerUsed: 'both_pinch',
        direction: 'pinch_in',
        targetColumn: 'hundreds',
        beadsAffected: [5, 1, 2],
        expectedValueAfter: 709,
      },
    ],
    explanation: 'الرقم 709 = 700 + 0 + 9.',
  },
];

// ═══════════════════════════════════════════════════════════
// ✏️ أسئلة "جرّب" (10 أسئلة — مثّل الرقم على المعداد)
// ═══════════════════════════════════════════════════════════

const TRY_QUESTIONS: TryQuestion[] = [
  {
    id: 'SRB-L0-S02-T-001',
    type: 'build',
    prompt: 'مثّل الرقم 1024 على المعداد',
    expectedValue: 1024,
    steps: [
      {
        stepIndex: 1,
        instructionText: 'آحاد: ارفع 4',
        fingerUsed: 'thumb',
        direction: 'up',
        targetColumn: 'units',
        beadsAffected: [1, 2, 3, 4],
        expectedValueAfter: 4,
      },
      {
        stepIndex: 2,
        instructionText: 'عشرات: ارفع 2',
        fingerUsed: 'thumb',
        direction: 'up',
        targetColumn: 'tens',
        beadsAffected: [1, 2],
        expectedValueAfter: 24,
      },
      {
        stepIndex: 3,
        instructionText: 'مئات: صفر',
        fingerUsed: 'index',
        direction: 'down',
        targetColumn: 'hundreds',
        beadsAffected: [],
        expectedValueAfter: 24,
      },
      {
        stepIndex: 4,
        instructionText: 'آلاف: ارفع 1',
        fingerUsed: 'thumb',
        direction: 'up',
        targetColumn: 'thousands',
        beadsAffected: [1],
        expectedValueAfter: 1024,
      },
    ],
    explanation: '1024 = 1000 + 0 + 20 + 4',
  },
  {
    id: 'SRB-L0-S02-T-002',
    type: 'build',
    prompt: 'مثّل الرقم 2350 على المعداد',
    expectedValue: 2350,
    steps: [
      {
        stepIndex: 1,
        instructionText: 'آحاد: صفر',
        fingerUsed: 'index',
        direction: 'down',
        targetColumn: 'units',
        beadsAffected: [],
        expectedValueAfter: 0,
      },
      {
        stepIndex: 2,
        instructionText: 'عشرات: أنزل العلوية (50)',
        fingerUsed: 'index',
        direction: 'down',
        targetColumn: 'tens',
        beadsAffected: [5],
        expectedValueAfter: 50,
      },
      {
        stepIndex: 3,
        instructionText: 'مئات: ارفع 3 (300)',
        fingerUsed: 'thumb',
        direction: 'up',
        targetColumn: 'hundreds',
        beadsAffected: [1, 2, 3],
        expectedValueAfter: 350,
      },
      {
        stepIndex: 4,
        instructionText: 'آلاف: ارفع 2 (2000)',
        fingerUsed: 'thumb',
        direction: 'up',
        targetColumn: 'thousands',
        beadsAffected: [1, 2],
        expectedValueAfter: 2350,
      },
    ],
    explanation: '2350 = 2000 + 300 + 50 + 0',
  },
  {
    id: 'SRB-L0-S02-T-003',
    type: 'build',
    prompt: 'مثّل الرقم 4007 على المعداد',
    expectedValue: 4007,
    steps: [
      {
        stepIndex: 1,
        instructionText: 'آحاد: أنزل العلوية + ارفع 2 (7)',
        fingerUsed: 'both_pinch',
        direction: 'pinch_in',
        targetColumn: 'units',
        beadsAffected: [5, 1, 2],
        expectedValueAfter: 7,
      },
      {
        stepIndex: 2,
        instructionText: 'عشرات: صفر',
        fingerUsed: 'index',
        direction: 'down',
        targetColumn: 'tens',
        beadsAffected: [],
        expectedValueAfter: 7,
      },
      {
        stepIndex: 3,
        instructionText: 'مئات: صفر',
        fingerUsed: 'index',
        direction: 'down',
        targetColumn: 'hundreds',
        beadsAffected: [],
        expectedValueAfter: 7,
      },
      {
        stepIndex: 4,
        instructionText: 'آلاف: ارفع 4 (4000)',
        fingerUsed: 'thumb',
        direction: 'up',
        targetColumn: 'thousands',
        beadsAffected: [1, 2, 3, 4],
        expectedValueAfter: 4007,
      },
    ],
    explanation: '4007 = 4000 + 0 + 0 + 7',
  },
  {
    id: 'SRB-L0-S02-T-004',
    type: 'build',
    prompt: 'مثّل الرقم 6080 على المعداد',
    expectedValue: 6080,
    steps: [
      {
        stepIndex: 1,
        instructionText: 'آحاد: صفر',
        fingerUsed: 'index',
        direction: 'down',
        targetColumn: 'units',
        beadsAffected: [],
        expectedValueAfter: 0,
      },
      {
        stepIndex: 2,
        instructionText: 'عشرات: أنزل العلوية + ارفع 3 (80)',
        fingerUsed: 'both_pinch',
        direction: 'pinch_in',
        targetColumn: 'tens',
        beadsAffected: [5, 1, 2, 3],
        expectedValueAfter: 80,
      },
      {
        stepIndex: 3,
        instructionText: 'مئات: صفر',
        fingerUsed: 'index',
        direction: 'down',
        targetColumn: 'hundreds',
        beadsAffected: [],
        expectedValueAfter: 80,
      },
      {
        stepIndex: 4,
        instructionText: 'آلاف: أنزل العلوية + ارفع 1 (6000)',
        fingerUsed: 'both_pinch',
        direction: 'pinch_in',
        targetColumn: 'thousands',
        beadsAffected: [5, 1],
        expectedValueAfter: 6080,
      },
    ],
    explanation: '6080 = 6000 + 0 + 80 + 0',
  },
  {
    id: 'SRB-L0-S02-T-005',
    type: 'build',
    prompt: 'مثّل الرقم 9999 على المعداد',
    expectedValue: 9999,
    steps: [
      {
        stepIndex: 1,
        instructionText: 'آحاد: 9',
        fingerUsed: 'both_pinch',
        direction: 'pinch_in',
        targetColumn: 'units',
        beadsAffected: [5, 1, 2, 3, 4],
        expectedValueAfter: 9,
      },
      {
        stepIndex: 2,
        instructionText: 'عشرات: 9',
        fingerUsed: 'both_pinch',
        direction: 'pinch_in',
        targetColumn: 'tens',
        beadsAffected: [5, 1, 2, 3, 4],
        expectedValueAfter: 99,
      },
      {
        stepIndex: 3,
        instructionText: 'مئات: 9',
        fingerUsed: 'both_pinch',
        direction: 'pinch_in',
        targetColumn: 'hundreds',
        beadsAffected: [5, 1, 2, 3, 4],
        expectedValueAfter: 999,
      },
      {
        stepIndex: 4,
        instructionText: 'آلاف: 9',
        fingerUsed: 'both_pinch',
        direction: 'pinch_in',
        targetColumn: 'thousands',
        beadsAffected: [5, 1, 2, 3, 4],
        expectedValueAfter: 9999,
      },
    ],
    explanation: '9999 = أكبر رقم من 4 مراتب',
  },
  {
    id: 'SRB-L0-S02-T-006',
    type: 'build',
    prompt: 'مثّل الرقم 5020 على المعداد',
    expectedValue: 5020,
    steps: [
      {
        stepIndex: 1,
        instructionText: 'آحاد: صفر',
        fingerUsed: 'index',
        direction: 'down',
        targetColumn: 'units',
        beadsAffected: [],
        expectedValueAfter: 0,
      },
      {
        stepIndex: 2,
        instructionText: 'عشرات: ارفع 2 (20)',
        fingerUsed: 'thumb',
        direction: 'up',
        targetColumn: 'tens',
        beadsAffected: [1, 2],
        expectedValueAfter: 20,
      },
      {
        stepIndex: 3,
        instructionText: 'مئات: صفر',
        fingerUsed: 'index',
        direction: 'down',
        targetColumn: 'hundreds',
        beadsAffected: [],
        expectedValueAfter: 20,
      },
      {
        stepIndex: 4,
        instructionText: 'آلاف: أنزل العلوية (5000)',
        fingerUsed: 'index',
        direction: 'down',
        targetColumn: 'thousands',
        beadsAffected: [5],
        expectedValueAfter: 5020,
      },
    ],
    explanation: '5020 = 5000 + 0 + 20 + 0',
  },
  {
    id: 'SRB-L0-S02-T-007',
    type: 'build',
    prompt: 'مثّل الرقم 7840 على المعداد',
    expectedValue: 7840,
    steps: [
      {
        stepIndex: 1,
        instructionText: 'آحاد: صفر',
        fingerUsed: 'index',
        direction: 'down',
        targetColumn: 'units',
        beadsAffected: [],
        expectedValueAfter: 0,
      },
      {
        stepIndex: 2,
        instructionText: 'عشرات: ارفع 4 (40)',
        fingerUsed: 'thumb',
        direction: 'up',
        targetColumn: 'tens',
        beadsAffected: [1, 2, 3, 4],
        expectedValueAfter: 40,
      },
      {
        stepIndex: 3,
        instructionText: 'مئات: أنزل العلوية + ارفع 3 (800)',
        fingerUsed: 'both_pinch',
        direction: 'pinch_in',
        targetColumn: 'hundreds',
        beadsAffected: [5, 1, 2, 3],
        expectedValueAfter: 840,
      },
      {
        stepIndex: 4,
        instructionText: 'آلاف: أنزل العلوية + ارفع 2 (7000)',
        fingerUsed: 'both_pinch',
        direction: 'pinch_in',
        targetColumn: 'thousands',
        beadsAffected: [5, 1, 2],
        expectedValueAfter: 7840,
      },
    ],
    explanation: '7840 = 7000 + 800 + 40 + 0',
  },
  {
    id: 'SRB-L0-S02-T-008',
    type: 'build',
    prompt: 'مثّل الرقم 3056 على المعداد',
    expectedValue: 3056,
    steps: [
      {
        stepIndex: 1,
        instructionText: 'آحاد: أنزل العلوية + ارفع 1 (6)',
        fingerUsed: 'both_pinch',
        direction: 'pinch_in',
        targetColumn: 'units',
        beadsAffected: [5, 1],
        expectedValueAfter: 6,
      },
      {
        stepIndex: 2,
        instructionText: 'عشرات: أنزل العلوية (50)',
        fingerUsed: 'index',
        direction: 'down',
        targetColumn: 'tens',
        beadsAffected: [5],
        expectedValueAfter: 56,
      },
      {
        stepIndex: 3,
        instructionText: 'مئات: صفر',
        fingerUsed: 'index',
        direction: 'down',
        targetColumn: 'hundreds',
        beadsAffected: [],
        expectedValueAfter: 56,
      },
      {
        stepIndex: 4,
        instructionText: 'آلاف: ارفع 3 (3000)',
        fingerUsed: 'thumb',
        direction: 'up',
        targetColumn: 'thousands',
        beadsAffected: [1, 2, 3],
        expectedValueAfter: 3056,
      },
    ],
    explanation: '3056 = 3000 + 0 + 50 + 6',
  },
  {
    id: 'SRB-L0-S02-T-009',
    type: 'build',
    prompt: 'مثّل الرقم 8412 على المعداد',
    expectedValue: 8412,
    steps: [
      {
        stepIndex: 1,
        instructionText: 'آحاد: ارفع 2',
        fingerUsed: 'thumb',
        direction: 'up',
        targetColumn: 'units',
        beadsAffected: [1, 2],
        expectedValueAfter: 2,
      },
      {
        stepIndex: 2,
        instructionText: 'عشرات: ارفع 1 (10)',
        fingerUsed: 'thumb',
        direction: 'up',
        targetColumn: 'tens',
        beadsAffected: [1],
        expectedValueAfter: 12,
      },
      {
        stepIndex: 3,
        instructionText: 'مئات: ارفع 4 (400)',
        fingerUsed: 'thumb',
        direction: 'up',
        targetColumn: 'hundreds',
        beadsAffected: [1, 2, 3, 4],
        expectedValueAfter: 412,
      },
      {
        stepIndex: 4,
        instructionText: 'آلاف: أنزل العلوية + ارفع 3 (8000)',
        fingerUsed: 'both_pinch',
        direction: 'pinch_in',
        targetColumn: 'thousands',
        beadsAffected: [5, 1, 2, 3],
        expectedValueAfter: 8412,
      },
    ],
    explanation: '8412 = 8000 + 400 + 10 + 2',
  },
  {
    id: 'SRB-L0-S02-T-010',
    type: 'build',
    prompt: 'مثّل الرقم 7008 على المعداد',
    expectedValue: 7008,
    steps: [
      {
        stepIndex: 1,
        instructionText: 'آحاد: أنزل العلوية + ارفع 3 (8)',
        fingerUsed: 'both_pinch',
        direction: 'pinch_in',
        targetColumn: 'units',
        beadsAffected: [5, 1, 2, 3],
        expectedValueAfter: 8,
      },
      {
        stepIndex: 2,
        instructionText: 'عشرات: صفر',
        fingerUsed: 'index',
        direction: 'down',
        targetColumn: 'tens',
        beadsAffected: [],
        expectedValueAfter: 8,
      },
      {
        stepIndex: 3,
        instructionText: 'مئات: صفر',
        fingerUsed: 'index',
        direction: 'down',
        targetColumn: 'hundreds',
        beadsAffected: [],
        expectedValueAfter: 8,
      },
      {
        stepIndex: 4,
        instructionText: 'آلاف: أنزل العلوية + ارفع 2 (7000)',
        fingerUsed: 'both_pinch',
        direction: 'pinch_in',
        targetColumn: 'thousands',
        beadsAffected: [5, 1, 2],
        expectedValueAfter: 7008,
      },
    ],
    explanation: '7008 = 7000 + 0 + 0 + 8',
  },
];

// ═══════════════════════════════════════════════════════════
// 🎯 الدرس الكامل
// ═══════════════════════════════════════════════════════════

export const L0_S2: LessonNode = {
  // ───── الهوية ─────
  id: 'SRB-L0-S02',
  skillId: 'S02',
  levelId: 'L0',
  order: 3,

  // ───── العنوان ─────
  title: {
    ar: 'القيمة المكانية وبناء الأعداد',
    en: 'Place Value and Building Numbers',
  },

  // ───── القصة (من learnModules.level2) ─────
  story: {
    ar: 'قال حارس القلعة: تذكّروا القاعدة الذهبية — الخرزة التي تلمس الجسر هي التي تُحسب، والباقي نائم لا قيمة له. كل عمود يمثّل منزلة: آحاد، وعشرات، ومئات، وآلاف.',
    en: 'The castle guard said: Remember the golden rule — only beads touching the beam are counted, the rest sleep with no value. Each column represents a place: units, tens, hundreds, and thousands.',
  },
  storyAudioId: 2, // story-2.mp3

  // ───── المفهوم ─────
  concept: {
    ar: 'كل عمود يمثّل منزلة عددية. الانتقال إلى العمود التالي يساراً يضرب القيمة في 10. الأعمدة من اليمين: آحاد ← عشرات ← مئات ← آلاف.',
    en: 'Each column represents a number place. Moving to the next column to the left multiplies the value by 10. From right: units → tens → hundreds → thousands.',
  },

  // ───── القاعدة ─────
  rule: {
    ar: 'لوضع رقم متعدد المراتب: ابدأ من الآحاد (يمين)، ثم العشرات، ثم المئات. أرقام الصفر لا تُحرّك أي خرزة.',
    en: 'To place a multi-digit number: start from units (right), then tens, then hundreds. Zero digits do not move any bead.',
  },

  // ───── المحتوى التفاعلي ─────
  examples: EXAMPLES,
  tryQuestions: TRY_QUESTIONS,

  // ───── معلومات ─────
  estimatedMinutes: 15,
  xpReward: 10,
  isTheoretical: false,
};

export default L0_S2;